### PR TITLE
Plumbing engine continued

### PR DESCRIPTION
**Pull request by wendi-yu**
Implemented the rest of the plumbing engine editing functions, and cleaned up the code a bit by pulling functionality out into the new functions.
Also cleaned up testing and implemented checking for error messages, instead of just errors.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/12)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
Coming along nicely!

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-:-M5A1vupD320PvUTxsTG:b-5o7xja)* status: 0 of 7 files reviewed, 11 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[topside/plumbing/plumbing_engine.py, line 65 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M59nyiU3AupfZ7bhD4P:-M59nyiVDkVLY788zVTZ:b-9hp7pr) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/plumbing_engine.py#L65)):*
> ```
>                 error = invalid.InvalidNodePressure(
>                     err.args[0], node_name)
> ```
Nit: one line
___
*[topside/plumbing/plumbing_engine.py, line 188 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M59oain2VPuC0vEm8Ae:-M59oain2VPuC0vEm8Af:b-gc3aon) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/plumbing_engine.py#L188)):*
> ```
>     def is_valid(self):
>         '''Returns whether the plumbing engine is valid'''
>         return self.valid
> ```

If we make this

```
def valid(self):
    return len(self.error_set) == 0
```

we can get rid of the `valid` class member entirely, and then we won't need to update it all over the place.
___
*[topside/plumbing/plumbing_engine.py, line 199 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M59rBBf8i--SeBIxriu:-M59rBBf8i--SeBIxriv:b86m0pn) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/plumbing_engine.py#L199)):*
> ```
>         og_name = component_name  # In case of errors
>         component_name = component.name
> ```

This is a bit confusing - I think this would be a bit more clear without the reassigning of variables. Is there any reason that we need to reuse the `component_name` variable? Can we just create a new one instead (call it `actual_name` or something), and keep `component_name` as the one the user passed in?
___
*[topside/plumbing/plumbing_engine.py, line 214 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M59rzCH7VJcd6hpBYbG:-M59rzCH7VJcd6hpBYbH:b-hvilgy) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/plumbing_engine.py#L214)):*
> ```Python
>             if not list(self.plumbing_graph.neighbors(node)):
>                 to_remove.append(node)
> ```

Nit: there's a newline here, but there isn't one in the corresponding place in the similarly-formatted "remove edges" block above.
___
*[topside/plumbing/plumbing_engine.py, line 239 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M59s_gY8q50dKbfQe0F:-M59s_gY8q50dKbfQe0G:b-xac1vk) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/plumbing_engine.py#L239)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>             elif hasattr(error, 'node_name'):
>                 mapped_nodes = [self.mapping[component][node] for node in component.component_graph]
>                 if error.node_name in mapped_nodes:
>                     to_remove.append(error)
> ```
</details>


We should only enter this branch of the `if` for errors that have a `node_name` but no `component_name`, which implies that this error is a `InvalidNodePressure` error. If that's the case, I don't think we should be clearing the error here, because node pressure isn't associated with any particular component.

Consider the following snippet of PDL:

```
B:
  connections:
  - initial_pressure: -100
  - [remote_fill_valve, 1]
  - [series_fill_valve, 0]
```

If we were to remove `series_fill_valve`, node `B` doesn't go away (since it's still connected to `remote_fill_valve`), and the `-100` pressure value doesn't go away either.
___
*[topside/plumbing/plumbing_engine.py, line 246 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M59twtQ64nYA9K_oe-Y:-M59twtQ64nYA9K_oe-Z:bf8mg59) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/plumbing_engine.py#L246)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         for error in self.error_set:
>             if isinstance(error, invalid.DuplicateError) and error.original_error in to_remove:
>                 to_remove.append(error)
> 
>         for error in to_remove:
>             self.error_set.remove(error)
> ```
</details>


I think you can probably do the whole thing in one pass if you use a really fat if statement, but this might be more extensible anyways.
___
*[topside/plumbing/plumbing_engine.py, line 321 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M59yYkA65mDYR_4d1ru:-M59yYkA65mDYR_4d1rv:b397iro) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/plumbing_engine.py#L321)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>     def list_toggles(self):
>         toggles = []
>         for component in self.component_dict.values():
>             if len(component.states.keys()) > 1:
>                 toggles.append(component.name)
> 
>         return toggles
> ```
</details>


I think this can just be:

```
return [c for c in self.component_dict.values() if len(c.states) > 1]
```
___
*[topside/plumbing/tests/test_plumbing_component.py, line 73 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M59ynPV5n9eD6TQ6xpd:-M59ynPV5n9eD6TQ6xpe:b-eznlzq) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/tests/test_plumbing_component.py#L73)):*
> ```
> 'closed'
> ```
Should this also be `utils.CLOSED_KEYWORD`?
___
*[topside/plumbing/tests/test_plumbing_engine_editing.py, line 13 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M5A-BMoCQynu_ypGb_2:-M5A-BMoCQynu_ypGb_3:bpzrzan) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/tests/test_plumbing_engine_editing.py#L13)):*
> ```
> def test_add_component():
> ```

This is a good test, but it's good practice to also have a "minimal" test every time you add functionality; I think in this case a minimal test would be adding to an empty engine. A minimal test would complement this more complicated one nicely and would actually make it a bit easier to understand since the reviewer can directly look at what changes between the minimal test and the more complicated one.
___
*[topside/plumbing/tests/test_plumbing_engine_editing.py, line 134 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M5A1O_h9IptsS84AJPd:-M5A1O_h9IptsS84AJPe:b-2wsuwu) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/tests/test_plumbing_engine_editing.py#L134)):*
> ```Python
> 
> 
> def test_remove_nonexistent_component():
> ```

Very nice
___
*[topside/plumbing/tests/test_plumbing_engine_editing.py, line 459 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M5A1lqZCAfYiEtdyX_O:-M5A1lqZCAfYiEtdyX_P:b-fmt0fb) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/tests/test_plumbing_engine_editing.py#L459)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
> def test_toggle_listing():
>     plumb = test_utils.two_valve_setup(
>         0.5, 0.2, 10, utils.CLOSED_KEYWORD, 0.5, 0.2, 10, utils.CLOSED_KEYWORD)
> 
>     toggles = plumb.list_toggles()
> 
>     assert len(toggles) == 2
>     assert 'valve1' in toggles
>     assert 'valve2' in toggles
> ```
</details>


You also want to test that components with only one state don't get listed
___
*[topside/plumbing/tests/test_plumbing_engine_creation.py, line 3 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M59ysxN-oKK6xNOwZE4:-M59ysxN-oKK6xNOwZE5:bliji9t) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/tests/test_plumbing_engine_creation.py#L3)):*
> ```
> import topside as ops
> ```

Why'd you change this?

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/12)* status: 0 of 7 files reviewed, 9 unresolved discussions (waiting on @jacobdeery)

___
*[topside/plumbing/plumbing_engine.py, line 188 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M59oain2VPuC0vEm8Ae:-M5B-cJB-2jnIZJxxOdU:b-orumjy) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/plumbing_engine.py#L188)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>     def is_valid(self):
>         '''Returns whether the plumbing engine is valid'''
>         return self.valid
> ```

If we make this

```
def valid(self):
    return len(self.error_set) == 0
```

we can get rid of the `valid` class member entirely, and then we won't need to update it all over the place.
</blockquote></details>

Good point
___
*[topside/plumbing/plumbing_engine.py, line 199 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M59rBBf8i--SeBIxriu:-M5BAJ92-ne2cWBKJEqn:b-g22o0o) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/plumbing_engine.py#L199)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>         og_name = component_name  # In case of errors
>         component_name = component.name
> ```

This is a bit confusing - I think this would be a bit more clear without the reassigning of variables. Is there any reason that we need to reuse the `component_name` variable? Can we just create a new one instead (call it `actual_name` or something), and keep `component_name` as the one the user passed in?
</blockquote></details>

Yeah, we only needed the original to be able to delete from the dict at the end if the name they entered didn't match up with the corresponding component's `name` attribute. I changed it to avoid renaming; the user now passes in `input_component_name` and the one that gets used to actually do things throughout stayed as `component_name`.
___
*[topside/plumbing/plumbing_engine.py, line 239 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M59s_gY8q50dKbfQe0F:-M5B17dN7vIm_Z7f56nY:b7m0fv3) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/plumbing_engine.py#L239)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>             elif hasattr(error, 'node_name'):
>                 mapped_nodes = [self.mapping[component][node] for node in component.component_graph]
>                 if error.node_name in mapped_nodes:
>                     to_remove.append(error)
> ```

We should only enter this branch of the `if` for errors that have a `node_name` but no `component_name`, which implies that this error is a `InvalidNodePressure` error. If that's the case, I don't think we should be clearing the error here, because node pressure isn't associated with any particular component.

Consider the following snippet of PDL:

```
B:
  connections:
  - initial_pressure: -100
  - [remote_fill_valve, 1]
  - [series_fill_valve, 0]
```

If we were to remove `series_fill_valve`, node `B` doesn't go away (since it's still connected to `remote_fill_valve`), and the `-100` pressure value doesn't go away either.
</blockquote></details>

That's a good point, the idea behind the `mapped_nodes` list was to only remove `InvalidNodePressure` errors associated with nodes that would have gotten removed with the component as well, but I forgot to account for overlap. I'll add in a check to fix that - otherwise if the node is being removed altogether we should be good to clear the associated `InvalidNodePressure` errors still?
___
*[topside/plumbing/plumbing_engine.py, line 246 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M59twtQ64nYA9K_oe-Y:-M5B2EiK03Thh-Z8BGgG:b-z71ejl) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/plumbing_engine.py#L246)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>         for error in self.error_set:
>             if isinstance(error, invalid.DuplicateError) and error.original_error in to_remove:
>                 to_remove.append(error)
> 
>         for error in to_remove:
>             self.error_set.remove(error)
> ```

I think you can probably do the whole thing in one pass if you use a really fat if statement, but this might be more extensible anyways.
</blockquote></details>

Huh I always thought removing while iterating was illegal
___
*[topside/plumbing/plumbing_engine.py, line 321 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M59yYkA65mDYR_4d1ru:-M5B32uBCzN3sExoK-27:bo9oq67) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/plumbing_engine.py#L321)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>     def list_toggles(self):
>         toggles = []
>         for component in self.component_dict.values():
>             if len(component.states.keys()) > 1:
>                 toggles.append(component.name)
> 
>         return toggles
> ```

I think this can just be:

```
return [c for c in self.component_dict.values() if len(c.states) > 1]
```
</blockquote></details>

I always forget list comprehension is a thing in Python lmao
___
*[topside/plumbing/tests/test_plumbing_component.py, line 73 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M59ynPV5n9eD6TQ6xpd:-M5B3khtD6N1PZCvMbJD:bipqtcl) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/tests/test_plumbing_component.py#L73)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> 'closed'
> ```
Should this also be `utils.CLOSED_KEYWORD`?
</blockquote></details>

No, that `'closed'` refers to the 'closed' `state_id` rather than the teq keyword. This is exactly why I went through and changed them haha
___
*[topside/plumbing/tests/test_plumbing_engine_editing.py, line 13 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M5A-BMoCQynu_ypGb_2:-M5B9Dx5E7e3A_vGhzBa:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/tests/test_plumbing_engine_editing.py#L13)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> def test_add_component():
> ```

This is a good test, but it's good practice to also have a "minimal" test every time you add functionality; I think in this case a minimal test would be adding to an empty engine. A minimal test would complement this more complicated one nicely and would actually make it a bit easier to understand since the reviewer can directly look at what changes between the minimal test and the more complicated one.
</blockquote></details>

Done.
___
*[topside/plumbing/tests/test_plumbing_engine_editing.py, line 459 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M5A1lqZCAfYiEtdyX_O:-M5BA8zF4505ZAoRLVIW:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/tests/test_plumbing_engine_editing.py#L459)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> def test_toggle_listing():
>     plumb = test_utils.two_valve_setup(
>         0.5, 0.2, 10, utils.CLOSED_KEYWORD, 0.5, 0.2, 10, utils.CLOSED_KEYWORD)
> 
>     toggles = plumb.list_toggles()
> 
>     assert len(toggles) == 2
>     assert 'valve1' in toggles
>     assert 'valve2' in toggles
> ```

You also want to test that components with only one state don't get listed
</blockquote></details>

Done.
___
*[topside/plumbing/tests/test_plumbing_engine_creation.py, line 3 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M59ysxN-oKK6xNOwZE4:-M5B44Md21N1B1yjXOaD:byp34tl) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/tests/test_plumbing_engine_creation.py#L3)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> import topside as ops
> ```

Why'd you change this?
</blockquote></details>

Oops my bad

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/12)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @wendi-yu)

___
*[topside/plumbing/plumbing_engine.py, line 239 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M59s_gY8q50dKbfQe0F:-M5Dzl7C9J9vOyYMPA_0:bc3vmme) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/plumbing_engine.py#L239)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

That's a good point, the idea behind the `mapped_nodes` list was to only remove `InvalidNodePressure` errors associated with nodes that would have gotten removed with the component as well, but I forgot to account for overlap. I'll add in a check to fix that - otherwise if the node is being removed altogether we should be good to clear the associated `InvalidNodePressure` errors still?
</blockquote></details>

Yes, that should be good. Please leave a comment here to explain why we're removing the error, because it might seem a bit counterintuitive otherwise.
___
*[topside/plumbing/plumbing_engine.py, line 246 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M59twtQ64nYA9K_oe-Y:-M5DxsDv3SkEZ6pjB-zQ:b-9w940o) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/plumbing_engine.py#L246)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Huh I always thought removing while iterating was illegal
</blockquote></details>

You're right, for a set it will throw a `RuntimeError`.
___
*[topside/plumbing/tests/test_plumbing_component.py, line 73 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M59ynPV5n9eD6TQ6xpd:-M5Dybdt5qLEWyFXJA7Z:btn5jp1) ([raw file](https://github.com/waterloo-rocketry/topside/blob/483616a728f0723088432f73685413838f32c1f4/topside/plumbing/tests/test_plumbing_component.py#L73)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

No, that `'closed'` refers to the 'closed' `state_id` rather than the teq keyword. This is exactly why I went through and changed them haha
</blockquote></details>

Gotcha
___
*[topside/plumbing/tests/test_plumbing_engine_querying.py, line 0 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M5DzCb28Eydmd-Fs6gD:-M5DzCb28Eydmd-Fs6gE:b2ke420) ([raw file](https://github.com/waterloo-rocketry/topside/blob/b5ace9ec3fb1fcae80d9a6a9ec2573c3aa41e037/topside/plumbing/tests/test_plumbing_engine_querying.py#L0)):*
Is this empty file intentional?
___
*[topside/plumbing/tests/test_plumbing_engine_creation.py, line 208 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M5DyiPv6ZgaZLnaqRK8:-M5DyiPv6ZgaZLnaqRK9:b-t97kfk) ([raw file](https://github.com/waterloo-rocketry/topside/blob/b5ace9ec3fb1fcae80d9a6a9ec2573c3aa41e037/topside/plumbing/tests/test_plumbing_engine_creation.py#L208)):*
> ```
> test_wrong_node_mapping()
> 
> ```
intentional?

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/12)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @jacobdeery)

___
*[topside/plumbing/tests/test_plumbing_engine_querying.py, line  at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M5DzCb28Eydmd-Fs6gD:-M5E-Qg_4Dh8rhsiVAZF:ber2ekk) ([raw file](https://github.com/waterloo-rocketry/topside/blob/b5ace9ec3fb1fcae80d9a6a9ec2573c3aa41e037/topside/plumbing/tests/test_plumbing_engine_querying.py#L)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Is this empty file intentional?
</blockquote></details>

Yeah, I'll fill it in with unit tests for querying functions once I get those written.
___
*[topside/plumbing/tests/test_plumbing_engine_creation.py, line 208 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-M5DyiPv6ZgaZLnaqRK8:-M5E-oTRBOB-6iMCX1NM:bad8b1g) ([raw file](https://github.com/waterloo-rocketry/topside/blob/b5ace9ec3fb1fcae80d9a6a9ec2573c3aa41e037/topside/plumbing/tests/test_plumbing_engine_creation.py#L208)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> test_wrong_node_mapping()
> 
> ```
intentional?
</blockquote></details>

Oops, removed

**Review by jacobdeery — APPROVED** [review]
:lgtm_strong:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/12#-:-M5E57ssAKqUSdt0_cDJ:b-jbsf8z)* status: 3 of 7 files reviewed, all discussions resolved

**Pull request merged**
