### PR TITLE
app: Rewrite base application to be Widget-centric

### PR DESCRIPTION
**Pull request by jacobdeery**
There are two main ways to structure a Qt application: using QML or
using Qt Widgets in pure Python/C++. QML is simpler and more intuitive
for building GUIs, but it's less flexible and there isn't any way to
include Qt Widgets in a QML scene.

This commit removes the main application layout previously defined in
application.qml and instead defines an equivalent application using
pure Python. The QML used for the Plumbing and Procedures panes is used
unchanged in this new application; it's just loaded into separate
widgets by Python instead of being loaded by parent QML.

The main benefit of this change is flexibility; we can now use Qt Widget
functionality that doesn't exist in QML. In particular, this opens the
door to using widgets from the pyqtgraph package for DAQ plotting.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/103)

### CODE REVIEW

**Review by wendi-yu — COMMENTED** [review]
Looks good! The usual Qt disclaimer stands but I do review things outside Qt specifics :^) `main.py` works locally, but the built executable fails (I think you've mentioned it does for you as well).

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/103#-:-MMNldDMEyNevjJBpq3A:b7wz29k)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @chrissank, @jacobdeery, and @wendi-yu)

___
*[application/application.py, line 31 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/103#-MMNgevr6lml7eOMwHbR:-MMNgevr6lml7eOMwHbS:b2u83cs) ([raw file](https://github.com/waterloo-rocketry/topside/blob/203d52be16bd07892f7bd3002fb09bb599c234c1/application/application.py#L31)):*
> ```Python
>     widget.setResizeMode(QQuickWidget.SizeRootObjectToView)
> 
>     path = find_resource(f'{resource_name}.qml')
> ```

Is there a reason we don't just pass in the file name (with the `.qml`) directly? It seems like there's more room for error if the requirement that the internal code name is the same as the file name is implicit, but I dunno if this is Qt best practices or something like that.
___
*[application/application.py, line 68 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/103#-MMNji-y28_eQOEog6sP:-MMNji-y28_eQOEog6sQ:b-sqj858) ([raw file](https://github.com/waterloo-rocketry/topside/blob/203d52be16bd07892f7bd3002fb09bb599c234c1/application/application.py#L68)):*
> ```Python
>     def _make_main_window(self):
>         # TODO(jacob): Should we move this code somewhere else (maybe
>         # into a separate MainWindow class)?
> ```

I think the main window is pretty self explanatory, do you think we'll make it more complex? If so we could put it into a class, but as it stands now I think this is fine as a function. There isn't really much state and I think we have the main window components in already.
___
*[application/visualization_area.py, line 320 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/103#-MMNjLl59vXDfA-sstc4:-MMNjLl59vXDfA-sstc5:b-sb8o4a) ([raw file](https://github.com/waterloo-rocketry/topside/blob/203d52be16bd07892f7bd3002fb09bb599c234c1/application/visualization_area.py#L320)):*
> ```Python
> 
>     @Slot()
>     def setRescaleNeeded(self):
> ```

:0 was this the rescaling video you sent me, very cool
___
*[application/tests/test_application.py, line 5 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/103#-MMNkON828Mxw4FQ-iIr:-MMNkON9C5Widjjyzzf0:b-j01p0s) ([raw file](https://github.com/waterloo-rocketry/topside/blob/203d52be16bd07892f7bd3002fb09bb599c234c1/application/tests/test_application.py#L5)):*
> ```Python
> 
> def test_application_init():
>     # TODO(jacob): Investigate if there's any way to spoof GUI events
> ```

I also think there are ways to do this because I've been asked about frontend unit testing in interviews before :^)

**Review by jacobdeery — COMMENTED** [review]
With #104 merged and this PR rebased, the built application should work fine now.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/103#-:-MMTR6fc6tZkmgWE3__k:b-8xaas9)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @chrissank and @wendi-yu)

___
*[application/application.py, line 31 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/103#-MMNgevr6lml7eOMwHbR:-MMTQFnH9XMRhhv2hfDm:b3v1bc0) ([raw file](https://github.com/waterloo-rocketry/topside/blob/203d52be16bd07892f7bd3002fb09bb599c234c1/application/application.py#L31)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Is there a reason we don't just pass in the file name (with the `.qml`) directly? It seems like there's more room for error if the requirement that the internal code name is the same as the file name is implicit, but I dunno if this is Qt best practices or something like that.
</blockquote></details>

I mostly just wanted to be more concise. Changed to pass in the full filename.
___
*[application/application.py, line 68 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/103#-MMNji-y28_eQOEog6sP:-MMTQKqg8XHG8t20o46N:b-h61wvc) ([raw file](https://github.com/waterloo-rocketry/topside/blob/203d52be16bd07892f7bd3002fb09bb599c234c1/application/application.py#L68)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

I think the main window is pretty self explanatory, do you think we'll make it more complex? If so we could put it into a class, but as it stands now I think this is fine as a function. There isn't really much state and I think we have the main window components in already.
</blockquote></details>

I expect this function to continue to get longer, but I agree it probably can just be a function rather than a class. I do think we will soon want to move it out of this class and into a new file, and probably split it up a bit as well.
___
*[application/tests/test_application.py, line 5 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/103#-MMNkON828Mxw4FQ-iIr:-MMTQutc30MNOhWUlp1S:b-cfcyo2) ([raw file](https://github.com/waterloo-rocketry/topside/blob/203d52be16bd07892f7bd3002fb09bb599c234c1/application/tests/test_application.py#L5)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

I also think there are ways to do this because I've been asked about frontend unit testing in interviews before :^)
</blockquote></details>

The key part of the comment is "for controls defined in QML".

**Review by wendi-yu — APPROVED** [review]
Cool, looks good to me. `main.py` still works for me, as does the built executable now :0 :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/103#-:-MMcWTd10vxYE0vPHZjO:b-l31p0x)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @chrissank and @wendi-yu)

___
*[application/application.py, line 68 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/103#-MMNji-y28_eQOEog6sP:-MMcWFOU5pWfeEVSZUr2:b-r1rcye) ([raw file](https://github.com/waterloo-rocketry/topside/blob/203d52be16bd07892f7bd3002fb09bb599c234c1/application/application.py#L68)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

I expect this function to continue to get longer, but I agree it probably can just be a function rather than a class. I do think we will soon want to move it out of this class and into a new file, and probably split it up a bit as well.
</blockquote></details>

Yeah, that makes sense. We can do that the next time we expand on this function then? (unless you want to do it now, up to you)

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/103)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @chrissank)

___
*[application/application.py, line 68 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/103#-MMNji-y28_eQOEog6sP:-MMcmzyk5gp_Nj5cyFKW:b-fkckfr) ([raw file](https://github.com/waterloo-rocketry/topside/blob/203d52be16bd07892f7bd3002fb09bb599c234c1/application/application.py#L68)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Yeah, that makes sense. We can do that the next time we expand on this function then? (unless you want to do it now, up to you)
</blockquote></details>

Will leave it for later (that's why there's a TODO)

**Pull request merged**
