### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by wendi-yu**
Basically copied directly from the wiki, which we can probably change to say "unused" once this is in.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/95)

### CODE REVIEW

**Comment by jacobdeery** [comment]
Did you mean to put this file in `topside`? Shouldn't it be at the top level?

**Review by jacobdeery — COMMENTED** [review]
Looks mostly good, just a few things that I think we can update while we're at it

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/95#-:-MKTAJaL7o2g6wPdbDfY:b-94xd7y)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[CONTRIBUTING.md, line 24 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/95#-MKT8aczDSCPbhhZGcI3:-MKT8aczDSCPbhhZGcI4:b-y7yvfk) ([raw file](https://github.com/waterloo-rocketry/topside/blob/dae20ceef98bf8acc1e5adbe189ab2c2d121715e/CONTRIBUTING.md#L24)):*
> ```
> please don't merge to master until the CI checks complete
> ```
I don't think this is actually possible - I think our checks block merging until CI passes
___
*[CONTRIBUTING.md, line 31 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/95#-MKT8qXL4pojPrzWJmo8:-MKT8qXL4pojPrzWJmo9:b-8yw6y2) ([raw file](https://github.com/waterloo-rocketry/topside/blob/dae20ceef98bf8acc1e5adbe189ab2c2d121715e/CONTRIBUTING.md#L31)):*
> ```
> `<subsystem>: <Commit message>`
> ```
`<subsystem>: <Commit message> (#XX)`, where XX is the PR number
___
*[CONTRIBUTING.md, line 31 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/95#-MKT90ouENbvjivipGuK:-MKT90ouENbvjivipGuL:b-1ivedq) ([raw file](https://github.com/waterloo-rocketry/topside/blob/dae20ceef98bf8acc1e5adbe189ab2c2d121715e/CONTRIBUTING.md#L31)):*
> ```
> topside/` directory
> ```
or `application`
___
*[CONTRIBUTING.md, line 31 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/95#-MKT93bo4GdV4WCxxZPw:-MKT93bo4GdV4WCxxZPx:b-oe7qr0) ([raw file](https://github.com/waterloo-rocketry/topside/blob/dae20ceef98bf8acc1e5adbe189ab2c2d121715e/CONTRIBUTING.md#L31)):*
> ```
> ·
> ```
Trailing space
___
*[CONTRIBUTING.md, line 33 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/95#-MKT97uP9F0VEE9h-frl:-MKT97uP9F0VEE9h-frm:bk7nj1p) ([raw file](https://github.com/waterloo-rocketry/topside/blob/dae20ceef98bf8acc1e5adbe189ab2c2d121715e/CONTRIBUTING.md#L33)):*
> ```
> `plumbing: Add solving algorithm`
> ```
Add PR number

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/95)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @jacobdeery)

___
*[CONTRIBUTING.md, line 24 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/95#-MKT8aczDSCPbhhZGcI3:-MKTBRsN5M7dn8ivm3o4:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/dae20ceef98bf8acc1e5adbe189ab2c2d121715e/CONTRIBUTING.md#L24)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> please don't merge to master until the CI checks complete
> ```
I don't think this is actually possible - I think our checks block merging until CI passes
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 31 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/95#-MKT8qXL4pojPrzWJmo8:-MKTBqtF-XnX583mj7-1:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/dae20ceef98bf8acc1e5adbe189ab2c2d121715e/CONTRIBUTING.md#L31)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> `<subsystem>: <Commit message>`
> ```
`<subsystem>: <Commit message> (#XX)`, where XX is the PR number
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 31 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/95#-MKT90ouENbvjivipGuK:-MKTBsKlAdCCgxn9vSxu:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/dae20ceef98bf8acc1e5adbe189ab2c2d121715e/CONTRIBUTING.md#L31)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> topside/` directory
> ```
or `application`
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 31 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/95#-MKT93bo4GdV4WCxxZPw:-MKTC1fF5MOHraMFF0Kw:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/dae20ceef98bf8acc1e5adbe189ab2c2d121715e/CONTRIBUTING.md#L31)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> ·
> ```
Trailing space
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 33 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/95#-MKT97uP9F0VEE9h-frl:-MKTC2KD5H4EbMf3ew4K:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/dae20ceef98bf8acc1e5adbe189ab2c2d121715e/CONTRIBUTING.md#L33)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> `plumbing: Add solving algorithm`
> ```
Add PR number
</blockquote></details>

Done.

**Review by jacobdeery — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/95)* status: 0 of 1 files reviewed, all discussions resolved

**Pull request merged**
