### PR TITLE
 Add an optimization-based layout algorithm

### PR DESCRIPTION
**Pull request by jacobdeery**
This commit starts to flesh out topside.visualization with functions for
laying out and plotting a PlumbingEngine. The first implementation of a
layout algorithm poses component placement as an optimization problem,
penalizing component terminal placement based on nominal distances and
enforcing component orientation at right angles. Currently, this
algorithm is not implemented very efficiently and takes several seconds
to layout a moderately-sized engine (12 components); optimized code will
follow in a later change.

To see the new code in action, call `topside.layout_and_plot_plumbing_engine` on any `PlumbingEngine`, or run the `visualization/tests/layout_demo.py` script for a demo.

Example: 
image

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/16)

### CODE REVIEW

**Comment by wendi-yu** [comment]
Should we update `requirements.txt` with `scipy`?

**Comment by jacobdeery** [comment]
Good catch; updated with numpy, scipy, matplotlib.

**Review by wendi-yu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/16)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[topside/visualization/plotting.py, line 19 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/16#-M6rfKiRBPafgW-dZDRG:-M6rfKiRBPafgW-dZDRH:b-47kf0) ([raw file](https://github.com/waterloo-rocketry/topside/blob/774b5e6df1b62e226293ef2ec3f5f3e2e02f5c13/topside/visualization/plotting.py#L19)):*
> ```Python
>         ax.plot([p1[0], p2[0]], [p1[1], p2[1]], color='darkgrey', zorder=1)
> 
>     xmin = min([v[0] for k, v in pos.items()])
> ```

Just out of curiosity, is there a reason we're not using `pos.values()` here? Since we don't seem to be using `k`. Also it probably doesn't make a huge difference but we could probably pull these values out in one pass if we do optimize to that point :0
___
*[topside/visualization/plotting.py, line 34 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/16#-M6rh4s1EC8Wi_Lir4yN:-M6rh4s2BAPLVBBAeVvx:b9x03la) ([raw file](https://github.com/waterloo-rocketry/topside/blob/774b5e6df1b62e226293ef2ec3f5f3e2e02f5c13/topside/visualization/plotting.py#L34)):*
> ```Python
> 
> def plot_plumbing_engine(engine, pos):
>     t, _, __ = top.terminal_graph(engine)
> ```

oo I didn't know underscores were a thing in python :0 any reason for the two underscores in the third variable?
___
*[topside/visualization/optimization/optimization.py, line 75 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/16#-M6rojWNB8P8F6ecvo5z:-M6rojWNB8P8F6ecvo6-:b-19smc1) ([raw file](https://github.com/waterloo-rocketry/topside/blob/774b5e6df1b62e226293ef2ec3f5f3e2e02f5c13/topside/visualization/optimization/optimization.py#L75)):*
> ```Python
> 
>     node_component_neighbors = {n: [] for n in t.nodes}
>     for cname, cnodes in components.items():
> ```

Same thing with the `.values()` rather than `.items()`
___
*[topside/visualization/optimization/optimization.py, line 77 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/16#-M6rrvlb8ZWWJydvgxNo:-M6rrvlb8ZWWJydvgxNp:b-thp002) ([raw file](https://github.com/waterloo-rocketry/topside/blob/774b5e6df1b62e226293ef2ec3f5f3e2e02f5c13/topside/visualization/optimization/optimization.py#L77)):*
> ```Python
>     for cname, cnodes in components.items():
>         for n in cnodes:
>             node_component_neighbors[n] = [v for v in t.neighbors(n) if v in cnodes]
> ```

Is there a chance of any node in `t` not being in `cnodes`? It looks like `t` is a subset of the main graph (which `cnodes` is pulled from). Do we definitely need the distinction between node_component_neighbors and the direct `t.neighbors(node)` that sometimes gets used in the cost term functions?

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/16)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @wendi-yu)

___
*[topside/visualization/plotting.py, line 19 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/16#-M6rfKiRBPafgW-dZDRG:-M6tvXIp1K3Abq5dkoka:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/774b5e6df1b62e226293ef2ec3f5f3e2e02f5c13/topside/visualization/plotting.py#L19)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Just out of curiosity, is there a reason we're not using `pos.values()` here? Since we don't seem to be using `k`. Also it probably doesn't make a huge difference but we could probably pull these values out in one pass if we do optimize to that point :0
</blockquote></details>

Done.
___
*[topside/visualization/plotting.py, line 34 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/16#-M6rh4s1EC8Wi_Lir4yN:-M6tVsbv-fhdenVQqa6Q:bq16j3i) ([raw file](https://github.com/waterloo-rocketry/topside/blob/774b5e6df1b62e226293ef2ec3f5f3e2e02f5c13/topside/visualization/plotting.py#L34)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

oo I didn't know underscores were a thing in python :0 any reason for the two underscores in the third variable?
</blockquote></details>

I thought that you needed to name each variable differently - but apparently you don't. Removed them anyways, since `terminal_graph` should really only be returning the graph itself.
___
*[topside/visualization/optimization/optimization.py, line 75 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/16#-M6rojWNB8P8F6ecvo5z:-M6tWOrY5PBaASnXXO0J:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/774b5e6df1b62e226293ef2ec3f5f3e2e02f5c13/topside/visualization/optimization/optimization.py#L75)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Same thing with the `.values()` rather than `.items()`
</blockquote></details>

Done.
___
*[topside/visualization/optimization/optimization.py, line 77 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/16#-M6rrvlb8ZWWJydvgxNo:-M6tWRkl0GNq-_t0IXLO:b-us1d3p) ([raw file](https://github.com/waterloo-rocketry/topside/blob/774b5e6df1b62e226293ef2ec3f5f3e2e02f5c13/topside/visualization/optimization/optimization.py#L77)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Is there a chance of any node in `t` not being in `cnodes`? It looks like `t` is a subset of the main graph (which `cnodes` is pulled from). Do we definitely need the distinction between node_component_neighbors and the direct `t.neighbors(node)` that sometimes gets used in the cost term functions?
</blockquote></details>

`node_component_neighbors` is the set of nodes that are adjacent to a particular node _and_ are in the same component. For the example below, `node_component_neighbors['c6.1']` is `['c6.2']`, but `t.neighbors('c6.1')` is `[3, 'c6.2']`.

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/16)* status: 0 of 13 files reviewed, all discussions resolved

___
*[topside/visualization/optimization/optimization.py, line 77 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/16#-M6rrvlb8ZWWJydvgxNo:-M6v9vN-6nYGTGVHvMUx:bgj25c) ([raw file](https://github.com/waterloo-rocketry/topside/blob/774b5e6df1b62e226293ef2ec3f5f3e2e02f5c13/topside/visualization/optimization/optimization.py#L77)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

`node_component_neighbors` is the set of nodes that are adjacent to a particular node _and_ are in the same component. For the example below, `node_component_neighbors['c6.1']` is `['c6.2']`, but `t.neighbors('c6.1')` is `[3, 'c6.2']`.



</blockquote></details>

Ahh ok makes sense yeah

**Review by wendi-yu — APPROVED** [review]
:lgtm:

> Reviewed 8 of 12 files at r1, 1 of 1 files at r2, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/16#-:-M6vULaO25pmtISKeyBd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
