### PR TITLE
plumbing: add solving algorithm

### PR DESCRIPTION
**Pull request by wendi-yu**
I _finally_ wrote the solving algorithm :)

The solving algorithm now exists; it comes in two parts:

1. `step(timestep)`, which advances the engine by a certain time period (in increments of the engine's `time_resolution`). It returns a snapshot of the engine's state afterwards as a dict of `{node: pressure}`.
2. `solve(min_delta, max_time, return_resolution=None)`, which simulates the engine until steady state, or timeout. Timeout is determined by max_time, and steady state is reached when delta pressure over time is less than max_time for every node after a step is taken. Two different behaviours are possible, determined by `return_resolution`:

- if `return_resolution` is `None`, steps will be taken in increments of the engine's `time_resolution` and the return value will be a single pressure dict at steady state
- if `return_resolution` has a value, the return value will be a list of pressure dicts taken at increments of `return_resolution`

Those are the implementation details, the other main part is the unit tests. They don't currently test for the algorithm's accuracy in terms of values (since that would require coding up the actual algorithm again which is pretty chicken egg); however they do generally test for values at steady state, consistency between `step()` and `solve()`, and number of iterations on `solve()` to reach steady state. They test fairly simple situations right now, a possible future PR could be a crown jewel mega plumbing engine to test. As of right now though, I don't think that test would add a lot of value.

Some other miscellaneous changes I made include renaming keywords to be less verbose (which is why all the files are changed), and adding support for an `atm` node (that models the atmosphere). Its whole shtick is that it has to be 0 when added, and always stays at 0 on solves. I think that's it for now :)

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/26)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
Awesome! :clap:

Please add one more test for a plumbing engine that times out during solving, because I don't believe that's currently tested. It would also be cool to have a demo script that produces a nice plot, like the original algorithm demo, but that's not essential in this PR.

> Reviewed 12 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-:-M8Qe7Og56ATaB4NBwqi:b-rgg6t9)* status: 12 of 13 files reviewed, 11 unresolved discussions (waiting on @dwkletke, @jacobdeery, and @wendi-yu)

___
*[topside/plumbing/plumbing_engine.py, line 530 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8QYX3AEa6iZV-5Qvm5:-M8QYX3AEa6iZV-5Qvm6:b-awnkt3) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/plumbing_engine.py#L530)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>         if timestep is None:
>             timestep = self.time_resolution
>         if timestep < utils.MIN_TIME_RES_MICROS:
>             raise exceptions.BadInputError(
>                 f"timestep ({timestep}) too low, must be greater than"
>                 "{utils.MIN_TIME_RES_MICROS} us.")
>         if timestep < self.time_resolution:
>             self.time_resolution = timestep
> ```
</details>


Should we also ensure that `timestep` is an integer?
___
*[topside/plumbing/plumbing_engine.py, line 533 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8QT96uCQrME3opal8c:-M8QT96uCQrME3opal8d:b73zoao) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/plumbing_engine.py#L533)):*
> ```
> time = 0
> ```
Do we want to give the plumbing engine a time member variable (initializes to 0 and just keeps going up) rather than restarting at 0 each time we call `step`?
___
*[topside/plumbing/plumbing_engine.py, line 556 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8QTU6aAbVkocPzCFwN:-M8QTU6aAbVkocPzCFwO:brnzikc) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/plumbing_engine.py#L556)):*
> ```
> time += self.time_resolution
> ```
If `timestep` isn't a multiple of `time_resolution`, this will cause us to step by a different value. For example, if `time_res` is 2 and `timestep` is 5, we'll end up stepping by 6.
___
*[topside/plumbing/plumbing_engine.py, line 572 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8QYpHq2mkYqHptj7jF:-M8QYpHq2mkYqHptj7jG:b9msr2m) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/plumbing_engine.py#L572)):*
> ```
> pa
> ```

is this Pascals? if so, should be `Pa`
___
*[topside/plumbing/plumbing_engine.py, line 594 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8QYzM46GmICiA785Ex:-M8QYzM46GmICiA785Ey:b-2uf4s4) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/plumbing_engine.py#L594)):*
> ```
> time = 0
> ```
Using a time member variable would remove a bit of repetition here
___
*[topside/plumbing/tests/test_plumbing_utils.py, line 95 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8QZcQ29aI009ndFMAZ:-M8QZcQ29aI009ndFMA_:bakso03) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/tests/test_plumbing_utils.py#L95)):*
> ```
> 1000000
> ```
`1e6` might be a bit easier to read (until we add a duration type)
___
*[topside/plumbing/tests/test_solving_algorithm.py, line 3 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8Qdost1oVwKzzTy2_C:-M8Qdost1oVwKzzTy2_D:b-o4iqd8) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/tests/test_solving_algorithm.py#L3)):*
> ```
> import pytest
> 
> import datatest as dt
> ```
Nit: No blank line
___
*[topside/plumbing/tests/test_solving_algorithm.py, line 71 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8Q_7PjBehs71vWGsgZ:-M8Q_7PjBehs71vWGsg_:b-6quu4z) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/tests/test_solving_algorithm.py#L71)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     plumb = test.two_valve_setup(1, 1, 1, 1, 1, 1, 1, 1)
>     solve_state = plumb.solve()
>     plumb = test.two_valve_setup(1, 1, 1, 1, 1, 1, 1, 1)
>     step_state = plumb.step(steady_by)
> ```
</details>

Reusing variable names makes it harder to understand what's going on here; please use a different name
___
*[topside/plumbing/tests/test_solving_algorithm.py, line 101 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8QaD_ND7PLs1_5Xy19:-M8QaD_ND7PLs1_5Xy1A:b-2uy6ah) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/tests/test_solving_algorithm.py#L101)):*
> ```Python
>     step_state = plumb.step(1000000)
> 
>     plumb.set_pressure(1, 100)
> ```

Same thing here with "resetting" the plumbing engine - I would much prefer instead making a copy with a different name 
___
*[topside/plumbing/tests/test_solving_algorithm.py, line 116 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8Q_wr08BLFe3lQ7QwQ:-M8Q_wr08BLFe3lQ7QwR:b-t8gypm) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/tests/test_solving_algorithm.py#L116)):*
> ```
> 
> ```
Should these blank lines be here?
___
*[topside/plumbing/tests/test_solving_algorithm.py, line 151 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8Qd4yP5O9XpVpBwyEM:-M8Qd4yP5O9XpVpBwyEN:bj9xatm) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/tests/test_solving_algorithm.py#L151)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
>     with dt.accepted.tolerance(test.SOLVE_TOL):
>         dt.validate(solve_state, step_state)
> 
>     with dt.accepted.tolerance(5):
>         dt.validate(solve_state, converged)
> 
>     plumb.set_pressure(1, 100)
>     plumb.set_pressure(2, 0)
>     solve_len = plumb.solve(return_resolution=plumb.time_resolution)
>     assert len(solve_len) < 2 * steady_by / plumb.time_resolution
> ```
</details>


This boilerplate gets repeated across a few different tests - consider if there's a good way to extract it into a function (something like `validate_plumbing_engine(engine, steady_by, converged_state)`)

**Review by wendi-yu — COMMENTED** [review]
Yeah, I think in the interest of getting `solve` onto master we should leave the demo to another PR. I'll file an issue as a placeholder :0

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-:-M8Swnwa0Yc50stTgaza:b55vezn)* status: 12 of 13 files reviewed, 10 unresolved discussions (waiting on @dwkletke and @jacobdeery)

___
*[topside/plumbing/plumbing_engine.py, line 530 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8QYX3AEa6iZV-5Qvm5:-M8SnP4z8jRSSwN-SOPh:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/plumbing_engine.py#L530)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>         if timestep is None:
>             timestep = self.time_resolution
>         if timestep < utils.MIN_TIME_RES_MICROS:
>             raise exceptions.BadInputError(
>                 f"timestep ({timestep}) too low, must be greater than"
>                 "{utils.MIN_TIME_RES_MICROS} us.")
>         if timestep < self.time_resolution:
>             self.time_resolution = timestep
> ```

Should we also ensure that `timestep` is an integer?
</blockquote></details>

Done.
___
*[topside/plumbing/plumbing_engine.py, line 533 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8QT96uCQrME3opal8c:-M8Suf8s27n_RVKsgybi:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/plumbing_engine.py#L533)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> time = 0
> ```
Do we want to give the plumbing engine a time member variable (initializes to 0 and just keeps going up) rather than restarting at 0 each time we call `step`?
</blockquote></details>

Done.
___
*[topside/plumbing/plumbing_engine.py, line 556 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8QTU6aAbVkocPzCFwN:-M8SvTb65IUFaumLRKtr:bp1u62d) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/plumbing_engine.py#L556)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> time += self.time_resolution
> ```
If `timestep` isn't a multiple of `time_resolution`, this will cause us to step by a different value. For example, if `time_res` is 2 and `timestep` is 5, we'll end up stepping by 6.
</blockquote></details>

I patched the effects of this by setting `self.time` to the amount we're supposed to have stepped by after a call to `step` or `solve`. Otherwise, I don't think there's anything we can do about the slight calculation inaccuracy it introduces since the whole point of having a `time_res` is to control the granularity of our calculations.
___
*[topside/plumbing/plumbing_engine.py, line 572 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8QYpHq2mkYqHptj7jF:-M8SnThQBiD5J7MGVN8F:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/plumbing_engine.py#L572)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> pa
> ```

is this Pascals? if so, should be `Pa`
</blockquote></details>

Done.
___
*[topside/plumbing/plumbing_engine.py, line 594 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8QYzM46GmICiA785Ex:-M8SvJmB1l9okGygNNmO:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/plumbing_engine.py#L594)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> time = 0
> ```
Using a time member variable would remove a bit of repetition here
</blockquote></details>

Done.
___
*[topside/plumbing/tests/test_plumbing_utils.py, line 95 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8QZcQ29aI009ndFMAZ:-M8SnYx1CIXt0DGj2MLa:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/tests/test_plumbing_utils.py#L95)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> 1000000
> ```
`1e6` might be a bit easier to read (until we add a duration type)
</blockquote></details>

Done
___
*[topside/plumbing/tests/test_solving_algorithm.py, line 71 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8Q_7PjBehs71vWGsgZ:-M8SzefrBaZTtOtsFoOR:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/tests/test_solving_algorithm.py#L71)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>     plumb = test.two_valve_setup(1, 1, 1, 1, 1, 1, 1, 1)
>     solve_state = plumb.solve()
>     plumb = test.two_valve_setup(1, 1, 1, 1, 1, 1, 1, 1)
>     step_state = plumb.step(steady_by)
> ```
Reusing variable names makes it harder to understand what's going on here; please use a different name
</blockquote></details>

Done.
___
*[topside/plumbing/tests/test_solving_algorithm.py, line 101 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8QaD_ND7PLs1_5Xy19:-M8SzeJOCXzZsglfr4EZ:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/tests/test_solving_algorithm.py#L101)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Same thing here with "resetting" the plumbing engine - I would much prefer instead making a copy with a different name 
</blockquote></details>

Done.
___
*[topside/plumbing/tests/test_solving_algorithm.py, line 116 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8Q_wr08BLFe3lQ7QwQ:-M8SpeSv3FhYmGgX-4RM:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/tests/test_solving_algorithm.py#L116)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> 
> ```
Should these blank lines be here?
</blockquote></details>

Done.
___
*[topside/plumbing/tests/test_solving_algorithm.py, line 151 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8Qd4yP5O9XpVpBwyEM:-M8SvLjrEyyDPzeZQe-j:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/tests/test_solving_algorithm.py#L151)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>     with dt.accepted.tolerance(test.SOLVE_TOL):
>         dt.validate(solve_state, step_state)
> 
>     with dt.accepted.tolerance(5):
>         dt.validate(solve_state, converged)
> 
>     plumb.set_pressure(1, 100)
>     plumb.set_pressure(2, 0)
>     solve_len = plumb.solve(return_resolution=plumb.time_resolution)
>     assert len(solve_len) < 2 * steady_by / plumb.time_resolution
> ```

This boilerplate gets repeated across a few different tests - consider if there's a good way to extract it into a function (something like `validate_plumbing_engine(engine, steady_by, converged_state)`)
</blockquote></details>

Done.

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/26)* status: 7 of 13 files reviewed, 4 unresolved discussions (waiting on @dwkletke, @jacobdeery, and @wendi-yu)

___
*[topside/plumbing/plumbing_engine.py, line 530 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8QYX3AEa6iZV-5Qvm5:-M8T0TXx7Wbtu1jPQKvZ:b7h4opb) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/plumbing_engine.py#L530)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

could make it `if not int(timestep) == timestep` so that `10.0` is still considered valid
___
*[topside/plumbing/plumbing_engine.py, line 556 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8QTU6aAbVkocPzCFwN:-M8T1AxUE06dWhjpAXSJ:b93i1y8) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/plumbing_engine.py#L556)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

I patched the effects of this by setting `self.time` to the amount we're supposed to have stepped by after a call to `step` or `solve`. Otherwise, I don't think there's anything we can do about the slight calculation inaccuracy it introduces since the whole point of having a `time_res` is to control the granularity of our calculations.
</blockquote></details>

I think there's a way to do it for most cases - in the example above, we could decide to step by 1 instead at the last iteration to hit 5 exactly. This isn't necessary for this PR - we can do it as a followup.

I do think, however, that setting `self.time = max_time` is _not_ what we should do in this instance. If we've stepped by 6 instead of 5, we should be exposing that to whatever is using this data rather than pretending that we stepped by that amount.
___
*[topside/plumbing/plumbing_utils.py, line 3 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8T-k5_AQg9w6y1IdMm:-M8T-k5_AQg9w6y1IdMn:b-narrvg) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fb2149cc3875c780134190a000eef3cdd32d7a3b/topside/plumbing/plumbing_utils.py#L3)):*
> ```
> MIN_TIME_RES_MICROS = 100
> ```
What's the rationale for this change?
___
*[topside/plumbing/tests/test_plumbing_utils.py, line 95 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8QZcQ29aI009ndFMAZ:-M8T0cvh5GvXA6Eq7EF1:bfhqmln) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/tests/test_plumbing_utils.py#L95)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Not done?
___
*[topside/plumbing/tests/testing_utils.py, line 58 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8T0M-c8Or2qGuZSvuo:-M8T0M-c8Or2qGuZSvup:b101jiu) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fb2149cc3875c780134190a000eef3cdd32d7a3b/topside/plumbing/tests/testing_utils.py#L58)):*
> ```Python
> 
> 
> def no_change(plumb):
> ```

Function names should be imperative; consider `assert_no_change`

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/26)* status: 6 of 13 files reviewed, 4 unresolved discussions (waiting on @dwkletke and @jacobdeery)

___
*[topside/plumbing/plumbing_engine.py, line 556 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8QTU6aAbVkocPzCFwN:-M8THajfBz-bD507LzVb:b-9klv7n) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/plumbing_engine.py#L556)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

I think there's a way to do it for most cases - in the example above, we could decide to step by 1 instead at the last iteration to hit 5 exactly. This isn't necessary for this PR - we can do it as a followup.

I do think, however, that setting `self.time = max_time` is _not_ what we should do in this instance. If we've stepped by 6 instead of 5, we should be exposing that to whatever is using this data rather than pretending that we stepped by that amount.
</blockquote></details>

That's fair, I was thinking more about keeping the steps in sync but yeah that's a good point. The fix you mentioned was pretty simple so I did it, it cleans up results from `solve()` a fair bit too :) 
___
*[topside/plumbing/plumbing_utils.py, line 3 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8T-k5_AQg9w6y1IdMm:-M8TGYMBEm08Vjb80qnd:b-alouxh) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fb2149cc3875c780134190a000eef3cdd32d7a3b/topside/plumbing/plumbing_utils.py#L3)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> MIN_TIME_RES_MICROS = 100
> ```
What's the rationale for this change?
</blockquote></details>

Honestly the other `min_time` just seemed absurdly small, we'd be incrementing the engine by 0.000001 seconds. I was poking through and changed it because of that but it's purely arbitrary and we can change it back if you want?
___
*[topside/plumbing/tests/test_plumbing_utils.py, line 95 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8QZcQ29aI009ndFMAZ:-M8THBjgEznyTmsIuVTz:bto2wc3) ([raw file](https://github.com/waterloo-rocketry/topside/blob/5a61f97bbd3e0866b87bf57feace326d798acef9/topside/plumbing/tests/test_plumbing_utils.py#L95)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

AH I did the changes in the wrong file sorry my bad
___
*[topside/plumbing/tests/testing_utils.py, line 58 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8T0M-c8Or2qGuZSvuo:-M8THVk8E-Qyh90h8pnJ:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fb2149cc3875c780134190a000eef3cdd32d7a3b/topside/plumbing/tests/testing_utils.py#L58)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Function names should be imperative; consider `assert_no_change`
</blockquote></details>

Done.

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/26)* status: 6 of 13 files reviewed, 4 unresolved discussions (waiting on @dwkletke and @jacobdeery)

___
*[topside/plumbing/plumbing_utils.py, line 10 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8TMDWtDk_kIi2797DX:-M8TMDWuCTSP0oHeRcl8:b-s11noc) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fb2149cc3875c780134190a000eef3cdd32d7a3b/topside/plumbing/plumbing_utils.py#L10)):*
> ```Python
> 
> # TODO(wendi): provide functions for querying these min/max values
> ```

I figured they're accessible as constants in the topside namespace anyways so probably no need for querying functions

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/26)* status: 6 of 13 files reviewed, 1 unresolved discussion (waiting on @dwkletke, @jacobdeery, and @wendi-yu)

___
*[topside/plumbing/plumbing_utils.py, line 3 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8T-k5_AQg9w6y1IdMm:-M8TMXiw6xpKcFZetKV3:b-3mwn8k) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fb2149cc3875c780134190a000eef3cdd32d7a3b/topside/plumbing/plumbing_utils.py#L3)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Honestly the other `min_time` just seemed absurdly small, we'd be incrementing the engine by 0.000001 seconds. I was poking through and changed it because of that but it's purely arbitrary and we can change it back if you want?
</blockquote></details>

Is there any real problem that having a low min time will cause? We only ever use a resolution that low if requested in `step`, at which point I don't see any reason that we should reject it as invalid. If someone wants to step the engine by 5 microseconds, why would we say no?

In general I would discourage this sort of change unless we can point to something concrete that this will improve.

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/26)* status: 6 of 13 files reviewed, 1 unresolved discussion (waiting on @dwkletke and @jacobdeery)

___
*[topside/plumbing/plumbing_utils.py, line 3 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8T-k5_AQg9w6y1IdMm:-M8TW-xlDZvqofZLRR6i:bwrk8ek) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fb2149cc3875c780134190a000eef3cdd32d7a3b/topside/plumbing/plumbing_utils.py#L3)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Is there any real problem that having a low min time will cause? We only ever use a resolution that low if requested in `step`, at which point I don't see any reason that we should reject it as invalid. If someone wants to step the engine by 5 microseconds, why would we say no?

In general I would discourage this sort of change unless we can point to something concrete that this will improve.
</blockquote></details>

Sure, changed it back.

**Review by jacobdeery — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/26)* status: 6 of 13 files reviewed, all discussions resolved (waiting on @dwkletke and @jacobdeery)

**Review by jacobdeery — COMMENTED** [review]
I realized we're still missing a bit of test coverage - could you add a test that confirms that after calling `step` or `solve`, the result is equal to `current_pressures`?

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-:-M8a4kQD-C4DTLXLpHu8:b-kf8o2h)* status: 6 of 13 files reviewed, all discussions resolved (waiting on @dwkletke and @jacobdeery)

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/26)* status: 6 of 13 files reviewed, all discussions resolved (waiting on @dwkletke and @jacobdeery)

___
*[topside/plumbing/plumbing_engine.py, line 564 at r5](https://reviewable.io/reviews/waterloo-rocketry/topside/26#-M8ahoS0DA_QP-IiEjHB:-M8ahoS156doIvDd5_oP:blddde9) ([raw file](https://github.com/waterloo-rocketry/topside/blob/b1d19445d6094af24965fac0903c321893caca0b/topside/plumbing/plumbing_engine.py#L564)):*
> ```Python
>             self.time += time_res
> 
>         return self.current_pressures()
> ```

Changed this because `new_pressures` never includes the `atm` node when reporting back

**Review by jacobdeery — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/26)* status: 6 of 13 files reviewed, all discussions resolved (waiting on @dwkletke and @jacobdeery)

**Review by jacobdeery — APPROVED** [review]

**Pull request merged**
