### PR TITLE
Restructure tooling to support PyPI deployment

### PR DESCRIPTION
**Pull request by jacobdeery**
Full changes:
- Move scripts into a new tools/ directory to avoid cluttering the root
- Move cx_Freeze application packaging code from setup.py into
build_exe.py, fixing a bug in the process
- Add more classifiers to setup() in setup.py
- Add release_info.py to topside so that the release info can easily be
retrieved by Python scripts
- Add new scripts:
    - build_exe.sh replaces the old build.sh
    - package.sh packages the topside libraries in sdist and wheel form
    in preparation for PyPI deployment
    - deploy.sh uploads the resulting packages to PyPI (or alternatively
    to the PyPI test server)

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/14)

### CODE REVIEW

**Review by wendi-yu — COMMENTED** [review]
I know _very_ little about executables so not much to say there but `main.py` still works, as does building and running the executable :tada: 
Some small classifier comments but overall :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/14#-:-M5QCRkz9BkMMJCiWt80:ba8s8e6)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @wendi-yu)

___
*[setup.py, line 27 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/14#-M5QAQkzCoYWwm1BismN:-M5QAQkzCoYWwm1BismO:b3ih20w) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fd14ff21343a2345a18da6348f15b92b6e4a06e3/setup.py#L27)):*
> ```Python
>         'License :: OSI Approved :: MIT License',
> 
>         'Operating System :: OS Independent',
> ```

Would it help for searchability to also put MacOS and Windows? I don't think OS Independent searches include those two by default.
___
*[setup.py, line 29 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/14#-M5QC0zL5kz1ghnRKz3o:-M5QAmYV3xRZV79asMD0:bcs4q64) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fd14ff21343a2345a18da6348f15b92b6e4a06e3/setup.py#L29)):*
> ```Python
>         'Operating System :: OS Independent',
> 
>         'Programming Language :: Python :: 3',
> ```

Python 3.6 technically can work if you backport dataclasses (thought I don't know if it's actually worth mentioning)

**Review by wendi-yu — APPROVED** [review]
:lgtm:

My :lgtm: didn't work last time hmph

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/14#-:-M5QDG-d3YZOvwSe16r7:b-ogce)* status: 0 of 9 files reviewed, all discussions resolved

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/14)* status: 0 of 9 files reviewed, all discussions resolved

___
*[setup.py, line 27 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/14#-M5QAQkzCoYWwm1BismN:-M5SY9TCC1-cC1GvQcXu:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fd14ff21343a2345a18da6348f15b92b6e4a06e3/setup.py#L27)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Would it help for searchability to also put MacOS and Windows? I don't think OS Independent searches include those two by default.
</blockquote></details>

Done.
___
*[setup.py, line 29 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/14#-M5QC0zL5kz1ghnRKz3o:-M5SYAW9-e2oZZww2VUW:bkvzg3e) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fd14ff21343a2345a18da6348f15b92b6e4a06e3/setup.py#L29)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Python 3.6 technically can work if you backport dataclasses (thought I don't know if it's actually worth mentioning)
</blockquote></details>

I don't think it's worth mentioning, since `main.py` won't work out of the box on 3.6.

**Review by wendi-yu — COMMENTED** [review]
Yep sounds good to me :)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/14#-:-M5SvPQiBzvnhcszRjN6:bpbyhne)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @wendi-yu)

**Pull request merged**
