### PR TITLE
Adding a basic version of the undo button's functionality by adding a state stack into the procedures engine

### PR DESCRIPTION
**Pull request by KavinSatheeskumar**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/129)

### CODE REVIEW

**Comment by jacobdeery** [comment]
Can you please add unit tests for the new functionality?

**Review by wendi-yu — CHANGES_REQUESTED** [review]
I also have a few comments here and there, and I second Jacob's comment about unit tests. For the commented code throughout, I'd prefer not to commit it. If you're using it for development in progress, you can move it onto a new branch and remove the comments from the branch we're about to merge :)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-:-MbsLwf94R7gAwe6cb7f:btc89ve)* status: 0 of 2 files reviewed, 10 unresolved discussions (waiting on @jacobdeery and @KavinSatheeskumar)

___
*[application/procedures_bridge.py, line 91 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsHErUEeeMTsqdZJ-o:-MbsHErV3Rkle6YRGeq1:brpc18g) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/application/procedures_bridge.py#L91)):*
> ```Python
>         eng = self._proc_eng.pop_and_set_stack()
>         self.plumb.engine = eng
>         #self.plumb.load_engine(eng)
> ```

Not sure if you meant to commit this but let's not include commented code - if we don't need it, we can just remove it entirely.
___
*[topside/procedures/procedures_engine.py, line 40 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsHTwBCrGC6037EwoY:-MbsHTwBCrGC6037EwoZ:bnrzpb7) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/topside/procedures/procedures_engine.py#L40)):*
> ```Python
>         self.current_step = None
>         self.step_position = None
>         self.state_stack = None #queue.LifoQueue() ##I know, I also can't believe that they're called lifoQueue's and not stacks
> ```

Is this a type annotation? There's also no apostrophe when pluralizing, though it might be cleaner to avoid peppering the code with offtopic comments. Also, where do we actually set `self.state_stack` to its initial value?
___
*[topside/procedures/procedures_engine.py, line 56 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsIh4F2QSD21nefte8:-MbsIh4F2QSD21nefte9:bemkhst) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/topside/procedures/procedures_engine.py#L56)):*
> ```Python
>             self.step_position = StepPosition.Before
> 
>     def load_suite(self, suite):
> ```

I think loading a new suite should clear the state storing stack
___
*[topside/procedures/procedures_engine.py, line 109 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsHdHWD9P01DZ9pf4G:-MbsHdHWD9P01DZ9pf4H:bo3zx5o) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/topside/procedures/procedures_engine.py#L109)):*
> ```Python
>             return
> 
>         self.push_stack()
> ```

I think want the `push_stack()` in `execute()` rather than here, since `execute_current()` calls execute to do its thing. If we put it in `execute`, then we don't need to put a separate call to update the stack in every function that could change the state of the procedures engine.
___
*[topside/procedures/procedures_engine.py, line 150 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsL2Vn1xDxz27t3E18:-MbsL2Vo7UxS8P0SYdXL:b-yxftqr) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/topside/procedures/procedures_engine.py#L150)):*
> ```Python
>                 break
> 
>     def next_step(self):
> ```

This  function might add two states onto the stack, is that intended?
___
*[topside/procedures/procedures_engine.py, line 161 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsLSyCEZ1tBSl5HB0-:-MbsLSyCEZ1tBSl5HB00:b-9don0s) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/topside/procedures/procedures_engine.py#L161)):*
> ```Python
>         self.execute_current()
> 
>     def step_time(self, timestep=None):
> ```

This one updates the state of the plumbing engine, I think we may want to store here too?
___
*[topside/procedures/procedures_engine.py, line 192 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsJu4X0-wKpcvr48iz:-MbsJu4X0-wKpcvr48j-:boqxx1w) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/topside/procedures/procedures_engine.py#L192)):*
> ```Python
>         step_pos = self.step_position
> 
>         #self.state_stack.put((curent_plumb, prod_id, step, step_pos))
> ```

Same with commented code
___
*[topside/procedures/procedures_engine.py, line 198 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsI9-V4WjKZWwxyPaw:-MbsI9-V4WjKZWwxyPax:b-d7b8wu) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/topside/procedures/procedures_engine.py#L198)):*
> ```Python
>         if(not self.state_stack == None): ##not self.state_stack.empty()
>             stack_element = self.state_stack[0]
>             
> ```

Extra whitespace on this line, please remember to run `tools/format.sh`
___
*[topside/procedures/procedures_engine.py, line 200 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsLjCX88XcJcrdMn3A:-MbsLjCX88XcJcrdMn3B:bvpnok0) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/topside/procedures/procedures_engine.py#L200)):*
> ```Python
>             
>             self._plumb = stack_element[0]
>             self.current_procedure_id = stack_element[1]
> ```

Could be nice to make this a dataclass rather than just a tuple accessed by index, there are a few examples of dataclasses used throughout Topside)
___
*[topside/procedures/procedures_engine.py, line 206 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsIEhN2jgSZVTkX3Lk:-MbsIEhN2jgSZVTkX3Ll:b-7dl1iy) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/topside/procedures/procedures_engine.py#L206)):*
> ```Python
>             self.state_stack = self.state_stack[1]
> 
>             return stack_element[0]##debug
> ```

Debug? Also missing final newline

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/129)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[application/procedures_bridge.py, line 91 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsHErUEeeMTsqdZJ-o:-McWOZ033rRX6opdEKAE:b-7rl0jd) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/application/procedures_bridge.py#L91)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Not sure if you meant to commit this but let's not include commented code - if we don't need it, we can just remove it entirely.
</blockquote></details>

done.
___
*[topside/procedures/procedures_engine.py, line 40 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsHTwBCrGC6037EwoY:-McWOa8R0wsqBChMoCiq:bs53llo) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/topside/procedures/procedures_engine.py#L40)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Is this a type annotation? There's also no apostrophe when pluralizing, though it might be cleaner to avoid peppering the code with offtopic comments. Also, where do we actually set `self.state_stack` to its initial value?
</blockquote></details>

Initially, I was using the queue library to handle my stack, but when debugging I just used a bunch of nested tuples (IE linked list). Now that I have finished debugging, I have reinstated the queue library.
___
*[topside/procedures/procedures_engine.py, line 56 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsIh4F2QSD21nefte8:-McWP-7L1R3LCSlsECd1:b-7rl0jd) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/topside/procedures/procedures_engine.py#L56)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

I think loading a new suite should clear the state storing stack
</blockquote></details>

done.
___
*[topside/procedures/procedures_engine.py, line 109 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsHdHWD9P01DZ9pf4G:-McWP2269qKSupXpRQsK:b-7rl0jd) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/topside/procedures/procedures_engine.py#L109)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

I think want the `push_stack()` in `execute()` rather than here, since `execute_current()` calls execute to do its thing. If we put it in `execute`, then we don't need to put a separate call to update the stack in every function that could change the state of the procedures engine.
</blockquote></details>

done.
___
*[topside/procedures/procedures_engine.py, line 150 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsL2Vn1xDxz27t3E18:-McWP3f-8OAZrmKNleFC:bik5imj) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/topside/procedures/procedures_engine.py#L150)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

This  function might add two states onto the stack, is that intended?
</blockquote></details>

How so? Only one condition will be satisfied and so once that occurs then the the stack element will be pushed.
___
*[topside/procedures/procedures_engine.py, line 161 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsLSyCEZ1tBSl5HB0-:-McWPJJSBUNcJPuVlAFj:bi28pjq) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/topside/procedures/procedures_engine.py#L161)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

This one updates the state of the plumbing engine, I think we may want to store here too?
</blockquote></details>

I mean, if we store a new stack element every time we take a time step, the stack would get unwieldy and the user would have to press back too many times.
___
*[topside/procedures/procedures_engine.py, line 192 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsJu4X0-wKpcvr48iz:-McWPtG5Dm0DNqjSZN2X:b-7rl0jd) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/topside/procedures/procedures_engine.py#L192)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Same with commented code
</blockquote></details>

done.
___
*[topside/procedures/procedures_engine.py, line 198 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsI9-V4WjKZWwxyPaw:-McWQ2zP9PzSlN6OcQq3:b-7rl0jd) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/topside/procedures/procedures_engine.py#L198)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Extra whitespace on this line, please remember to run `tools/format.sh`
</blockquote></details>

done.
___
*[topside/procedures/procedures_engine.py, line 200 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsLjCX88XcJcrdMn3A:-McaH97O-92RxTxwc3EZ:begz5v3) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/topside/procedures/procedures_engine.py#L200)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Could be nice to make this a dataclass rather than just a tuple accessed by index, there are a few examples of dataclasses used throughout Topside)
</blockquote></details>

Added. Quick question, I didn't really know of a good way to make the class immutatble, I think it would be better as an immutable class, but hey, what are ya gonna do, amirite?
___
*[topside/procedures/procedures_engine.py, line 206 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsIEhN2jgSZVTkX3Lk:-McWQ51NCgB-aJ8lC4eq:b-7rl0jd) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/topside/procedures/procedures_engine.py#L206)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Debug? Also missing final newline
</blockquote></details>

done.

**Comment by KavinSatheeskumar** [comment]
Hey, just letting you know that there is actually a bug I found in this commit
- right now, when there is a condition action, the text no longer becomes green when the condition is sateisfied, however, it still lets you perform the action.
- Also, unit tests not done, this just fixes the changes suggested for this PR

Pls no merge thx

**Review by wendi-yu — COMMENTED** [review]
Thanks for adding unit tests! If you take a look at codecov, there are a few lines that aren't covered by the tests and it's bringing our overall coverage down. Do you mind adding tests that get these lines? Looks good otherwise.


> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-:-MeS9r_f16AsFVJJXdtK:b-cjfn5e)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @jacobdeery)

___
*[topside/procedures/procedures_engine.py, line 40 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsHTwBCrGC6037EwoY:-MeS9PlH4QgP7fAUArX-:bte1yi3) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/topside/procedures/procedures_engine.py#L40)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Initially, I was using the queue library to handle my stack, but when debugging I just used a bunch of nested tuples (IE linked list). Now that I have finished debugging, I have reinstated the queue library.
</blockquote></details>

Cool, makes sense. tbh I'd prefer if the comment wasn't in here, seems cluttery and kinda odd to have "I's" in the codebase 
___
*[topside/procedures/procedures_engine.py, line 200 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-MbsLjCX88XcJcrdMn3A:-MeS8UJi-p3G9UMspdYk:b-td9cnb) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9092a4ada118f863d39ee1596821bfb823168d5f/topside/procedures/procedures_engine.py#L200)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Added. Quick question, I didn't really know of a good way to make the class immutatble, I think it would be better as an immutable class, but hey, what are ya gonna do, amirite?
</blockquote></details>

the `frozen=True` annotation does that I'm pretty sure. You can Google it, up to you if you can include it or not

**Review by wendi-yu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/129#-:-Meh3fi4-Xeoi45rp67O:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @jacobdeery)

**Pull request merged**
