### PR TITLE
proc: Add ProcLang parser

### PR DESCRIPTION
**Pull request by jacobdeery**
Add the first revision of the Procedures Language grammar and a parser
for converting ProcLang documents into Topside ProcedureSuites.

This version of ProcLang is fairly rudimentary and is still missing some
features that we will eventually want: logical AND/OR conditions,
tolerance in equality comparison, in-document specification of procedure
suite metadata. However, this should still be good enough for a minimum
viable product.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/57)

### CODE REVIEW

**Comment by jacobdeery** [comment]
Stacking on top of #56 until that one gets merged.

**Review by wendi-yu — CHANGES_REQUESTED** [review]
Looks good overall. Might be useful to annotate some of the more complex `Transform` functions with what exactly `data` is :)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/57#-:-MH8U1w_E0ixphlL-Oaz:b1tpr3z)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[topside/procedures/proclang.py, line 29 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/57#-MH8NWT_BVxJ26YpW-Mq:-MH8NWT_BVxJ26YpW-Mr:bur9gac) ([raw file](https://github.com/waterloo-rocketry/topside/blob/93901f973dae4ddc75644ba4f2299f79e46eeded/topside/procedures/proclang.py#L29)):*
> ```Python
> transition: name "." step_id
> 
> condition: "[" (waituntil | comparison) "]" [":"]
> ```

Is the `:` optional after the condition? If so maybe include a unit test that uses it?
___
*[topside/procedures/proclang.py, line 97 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/57#-MH8Q06w7ImcfvHyd7H2:-MH8Q06x0uSw9Ra0xsT-:bupq5a7) ([raw file](https://github.com/waterloo-rocketry/topside/blob/93901f973dae4ddc75644ba4f2299f79e46eeded/topside/procedures/proclang.py#L97)):*
> ```Python
> 
>     def condition(self, data):
>         return data
> ```

Is this just a list with one element? Would it make more sense to just return the one element instead of the list? Would make a lot of the `cond[0]` and data[1][0] stuff down below easier to read.
___
*[topside/procedures/proclang.py, line 130 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/57#-MH8MCqGEaokNF2cUjlB:-MH8MCqGEaokNF2cUjlC:bcwcqfj) ([raw file](https://github.com/waterloo-rocketry/topside/blob/93901f973dae4ddc75644ba4f2299f79e46eeded/topside/procedures/proclang.py#L130)):*
> ```Python
>             deviations = data[2:]
>         else:  # Step has an attached entry condition
>             step_info['condition_in'] = data[1][0]
> ```

Is `data[1][0]` just a condition? Ties back to the comment on the condition() function - if we don't change it to just returning the element maybe comment what exactly `data[1][0]` is
___
*[topside/procedures/proclang.py, line 180 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/57#-MH8RyC65PkCm9fLaBSE:-MH8RyC65PkCm9fLaBSF:bovzpnn) ([raw file](https://github.com/waterloo-rocketry/topside/blob/93901f973dae4ddc75644ba4f2299f79e46eeded/topside/procedures/proclang.py#L180)):*
> ```Python
> 
> 
> def parse(text):
> ```

Maybe also make this able to take a file at some point in time? Again, doesn't have to be this PR
___
*[topside/procedures/tests/test_proclang.py, line 6 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/57#-MH8DbJy4ja1h58ZEhjZ:-MH8DbJy4ja1h58ZEhj_:b-a277rr) ([raw file](https://github.com/waterloo-rocketry/topside/blob/93901f973dae4ddc75644ba4f2299f79e46eeded/topside/procedures/tests/test_proclang.py#L6)):*
> ```Python
> 
> 
> def test_parse_one_step():
> ```

I think at some point (doesn't have to be this PR), it would be nice to have an "integration test" almost for the ProcLang, where we parse a complete proclang document that's using all the features we support. It would be nice in-code documentation of what the procedures language looks like as a whole without stepping on the granularity we get from testing each feature individually in the units tests.
___
*[topside/procedures/tests/test_proclang.py, line 132 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/57#-MH8GjDD0t6ml9J22qaw:-MH8GjDD0t6ml9J22qax:b-802u7u) ([raw file](https://github.com/waterloo-rocketry/topside/blob/93901f973dae4ddc75644ba4f2299f79e46eeded/topside/procedures/tests/test_proclang.py#L132)):*
> ```Python
>     main:
>         1. set injector_valve to open
>             - [p1 < 500] abort.1
> ```

Maybe worth eventually checking that the specified transition goes to a step that actually exists? Doesn't have to be in the minimum viable product, but this seems useful to have eventually.

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/57)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @wendi-yu)

___
*[topside/procedures/proclang.py, line 29 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/57#-MH8NWT_BVxJ26YpW-Mq:-MH9WOAY1vzIH4GMnS0w:b-hnmkcv) ([raw file](https://github.com/waterloo-rocketry/topside/blob/93901f973dae4ddc75644ba4f2299f79e46eeded/topside/procedures/proclang.py#L29)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Is the `:` optional after the condition? If so maybe include a unit test that uses it?
</blockquote></details>

It was optional. I've just removed it to make the language a bit simpler.
___
*[topside/procedures/proclang.py, line 97 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/57#-MH8Q06w7ImcfvHyd7H2:-MH9Wog66JduiYEVsncj:b-xocud0) ([raw file](https://github.com/waterloo-rocketry/topside/blob/93901f973dae4ddc75644ba4f2299f79e46eeded/topside/procedures/proclang.py#L97)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Is this just a list with one element? Would it make more sense to just return the one element instead of the list? Would make a lot of the `cond[0]` and data[1][0] stuff down below easier to read.
</blockquote></details>

Good catch. We can indeed just return the one element.

We could actually just flag `condition` with a leading `?` in the grammar so that Lark auto-inlines it and we wouldn't even need this function...but I'll leave it in for now for clarity.
___
*[topside/procedures/proclang.py, line 130 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/57#-MH8MCqGEaokNF2cUjlB:-MH9WrpiCmooBklDgB9a:b-4flt9q) ([raw file](https://github.com/waterloo-rocketry/topside/blob/93901f973dae4ddc75644ba4f2299f79e46eeded/topside/procedures/proclang.py#L130)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Is `data[1][0]` just a condition? Ties back to the comment on the condition() function - if we don't change it to just returning the element maybe comment what exactly `data[1][0]` is
</blockquote></details>

Done (adopted previous suggestion).
___
*[topside/procedures/proclang.py, line 180 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/57#-MH8RyC65PkCm9fLaBSE:-MHCP6UZ9FdJ4IwegS5l:bjru3r5) ([raw file](https://github.com/waterloo-rocketry/topside/blob/93901f973dae4ddc75644ba4f2299f79e46eeded/topside/procedures/proclang.py#L180)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Maybe also make this able to take a file at some point in time? Again, doesn't have to be this PR
</blockquote></details>

Added a `parse_from_file` function
___
*[topside/procedures/tests/test_proclang.py, line 6 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/57#-MH8DbJy4ja1h58ZEhjZ:-MHCP9KSDt5XUaG3jOnf:b-tf6l7y) ([raw file](https://github.com/waterloo-rocketry/topside/blob/93901f973dae4ddc75644ba4f2299f79e46eeded/topside/procedures/tests/test_proclang.py#L6)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

I think at some point (doesn't have to be this PR), it would be nice to have an "integration test" almost for the ProcLang, where we parse a complete proclang document that's using all the features we support. It would be nice in-code documentation of what the procedures language looks like as a whole without stepping on the granularity we get from testing each feature individually in the units tests.
</blockquote></details>

Done - added an `example.proc` file that gets parsed as part of the `parse_from_file` test.
___
*[topside/procedures/tests/test_proclang.py, line 132 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/57#-MH8GjDD0t6ml9J22qaw:-MH9X_S_1jd89zJts9Ga:b-8abma8) ([raw file](https://github.com/waterloo-rocketry/topside/blob/93901f973dae4ddc75644ba4f2299f79e46eeded/topside/procedures/tests/test_proclang.py#L132)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Maybe worth eventually checking that the specified transition goes to a step that actually exists? Doesn't have to be in the minimum viable product, but this seems useful to have eventually.
</blockquote></details>

I agree that we will want that check eventually. I think that check belongs in a `ProcedureSuite.validate()` function, not at the proclang level.

**Review by wendi-yu — APPROVED** [review]
Cool cool looks good!

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/57#-:-MHE1ZgY-oJngi101V5H:b-nl4mod)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @wendi-yu)

**Pull request merged**
