### PR TITLE
Update readme with new name

### PR DESCRIPTION
**Pull request by wendi-yu**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/11)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
We should probably update the name everywhere, not just the readme

**Comment by wendi-yu** [comment]
I checked `main.py`, `build.sh` (and the resulting executable), and pytest which all still work so I don't _think_ I broke anything during the renaming.

**Review by jacobdeery — COMMENTED** [review]
> Reviewed 14 of 17 files at r1, 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/11)* status: 27 of 30 files reviewed, 4 unresolved discussions (waiting on @wendi-yu)

___
*[application/application.py, line 7 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/11#-M4zvFlX0fG2U4X8kWdA:-M4zvFlX0fG2U4X8kWdB:b-cqyio) ([raw file](https://github.com/waterloo-rocketry/topside/blob/d50f4381699fb30404a1b686852acc5745cb29c2/application/application.py#L7)):*
> ```Python
> from PySide2.QtQml import QQmlApplicationEngine
> 
> import topside as ops
> ```

Perhaps `import topside as top` or `import topside as ts` instead?
___
*[topside/plumbing/tests/test_plumbing_component.py, line 1 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/11#-M4zvYH46-mJAn8dVaHa:-M4zvYH46-mJAn8dVaHb:b-e5xsmp) ([raw file](https://github.com/waterloo-rocketry/topside/blob/d50f4381699fb30404a1b686852acc5745cb29c2/topside/plumbing/tests/test_plumbing_component.py#L1)):*
> ```Python
> import topside as ops
> ```

Same as previous comment
___
*[topside/plumbing/tests/test_plumbing_engine.py, line 3 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/11#-M4zvbqfAC4XiDN475le:-M4zvbqfAC4XiDN475lf:bb73xfv) ([raw file](https://github.com/waterloo-rocketry/topside/blob/d50f4381699fb30404a1b686852acc5745cb29c2/topside/plumbing/tests/test_plumbing_engine.py#L3)):*
> ```Python
> import pytest
> 
> import topside as ops
> ```

Same
___
*[topside/plumbing/tests/test_plumbing_utils.py, line 1 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/11#-M4zveCp9JbC_bJTwcaQ:-M4zveCp9JbC_bJTwcaR:bb73xfv) ([raw file](https://github.com/waterloo-rocketry/topside/blob/d50f4381699fb30404a1b686852acc5745cb29c2/topside/plumbing/tests/test_plumbing_utils.py#L1)):*
> ```Python
> import topside as ops
> ```

Same

**Review by jacobdeery — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/11#-:-M5--nQV6vsXpmAaQ1KG:bnfp4nl)* status: 22 of 30 files reviewed, all discussions resolved (waiting on @jacobdeery)

**Pull request merged**
