### PR TITLE
Adding plumbing control panel

### LINKED ISSUE #117: Add plumbing control panel

### PR DESCRIPTION
**Pull request by James020118**
- Added a control panel that can control all the toggleable valves in a plumbing engine.

Closes #117 

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/130)

### CODE REVIEW

**Review by wendi-yu — COMMENTED** [review]
This looks really good, thanks for putting it together! I left a few comments here and there with formatting stuff. I did want to bring up whether we want to maintain a second set of state in the control bridge, since that's something we'll have to keep in sync with the actual plumbing engine. do you think it would be better to just pipe commands directly through to the plumbing engine?
Also really great job on the Qt/QML stuff!

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/130#-:-McbMFVL2ioNmD-5rksI:bo75811)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @James020118)

___
*[application/application.py, line 45 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/130#-McbK1wU0T-vtLn0SVNe:-McbK1wV1pd3akjp0kVZ:b-m3yq85) ([raw file](https://github.com/waterloo-rocketry/topside/blob/ea865cfff270999e95f1a66132bf709dfb2b2769/application/application.py#L45)):*
> ```Python
>         self.controls_bridge = ControlsBridge(self.plumbing_bridge)
>         self.procedures_bridge = ProceduresBridge(self.plumbing_bridge, self.controls_bridge)
>        
> ```

Bit of whitespace here, don't forget to run the `tools/format.sh` script to format
___
*[application/controls_bridge.py, line 30 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/130#-McbKYT-1sr3O8zzzKvg:-McbKYT-1sr3O8zzzKvh:b-t8o7xw) ([raw file](https://github.com/waterloo-rocketry/topside/blob/ea865cfff270999e95f1a66132bf709dfb2b2769/application/controls_bridge.py#L30)):*
> ```Python
>         self.plumbing_eng = self.plumbing_bridge.engine
>         self.toggleable_components = self.plumbing_eng.list_toggles()
>         self._isOpen = [False] * len(self.toggleable_components)
> ```

`[False for component in self.toggleable_components]`
___
*[application/controls_bridge.py, line 31 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/130#-McbKv-u4gfAWJs9P2HT:-McbKv-u4gfAWJs9P2HU:b-o2m1ia) ([raw file](https://github.com/waterloo-rocketry/topside/blob/ea865cfff270999e95f1a66132bf709dfb2b2769/application/controls_bridge.py#L31)):*
> ```Python
>         self.toggleable_components = self.plumbing_eng.list_toggles()
>         self._isOpen = [False] * len(self.toggleable_components)
>         for i in range(len(self.toggleable_components)):
> ```

you can have `for component, i in enumerate(self.toggleable_components)` to get a name for the component and its index more pythonically 
___
*[application/resources/ControlsPane.qml, line 38 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/130#-McbMm1A2I7F56mw3hqT:-McbMm1A2I7F56mw3hqU:b-9itt01) ([raw file](https://github.com/waterloo-rocketry/topside/blob/ea865cfff270999e95f1a66132bf709dfb2b2769/application/resources/ControlsPane.qml#L38)):*
> ```QML
> 
>         Repeater {
>             model: controlsBridge.numOfComponents
> ```

Any way we can scale distance between buttons with name? they're overlapping for me rn:


Resizing is also something we maybe want to consider:

Just control compression and add a scroll bar instead at a minimum size is my suggestions
___
*[application/resources/ControlsPane.qml, line 64 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/130#-McbLguL3VIQwNwyleFm:-McbLguL3VIQwNwyleFn:bl3xath) ([raw file](https://github.com/waterloo-rocketry/topside/blob/ea865cfff270999e95f1a66132bf709dfb2b2769/application/resources/ControlsPane.qml#L64)):*
> ```QML
>         }
>     }
> }
> ```

final newline

**Comment by James020118** [comment]
Note for my changes:
- I still left in a local array to track the states of the components, and I think it is needed because qml can only know about its state via this local array? (couldn't think of a better solution atm haha). I changed the implementation of the array a bit, so it communicates with plumbing engine better.
- I don't know how to make the row of buttons scrollable .. at least not inside a column. If I only have the row, it is scrollable. But with the title, somehow it isn't. I have no idea how that works and I couldn't find anything useful online. So please help me with that
- I couldn't get the overlapping of text to happen on my end, so it's kind of hard for me to fix it ... I added more spacing between the buttons but not sure if that fixes anything ..

**Comment by James020118** [comment]
This is what the `scrollView` looks like with the minimal window size:

https://user-images.githubusercontent.com/45859048/124051345-54032900-d9ea-11eb-9375-5cb77708d728.mov

Please let me know if there still are spacing/scrolling issues :)

**Review by wendi-yu — APPROVED** [review]
New changes look good - I think I fixed the overlapping text problem on Windows from my end - do you want to check and see if it still works on yours? The row seems scrollable to me, only when the window is too narrow to fit all the buttons, which seems like intended behaviour. Overall it looks good to me :)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/130#-:-MdZQg809Fzhb50P5NX5:bsabukb)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @James020118)

**Comment by James020118** [comment]
Yep it works, and yes that is the intended behaviour. Thanks and I will merge it now. :)

**Pull request merged**
