### PR TITLE
Unhardcode imports

### PR DESCRIPTION
**Pull request by wendi-yu**
Adds support for specifying the folder(s) from which imports are read, instead of having it hardcoded. The list of folders is now a property of the `Parser` structure, so different parsers can read from different folder. It's propagated down to packages on their initializations to actually perform the import.
As a prerequisite, this PR also adds support for reading imports from multiple folders (which entailed small changes to error handling on import reads).

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/109)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
Generally looks good, just a few minor comments

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/109#-:-MMs0TnJ2-MZ8biYoIl4:b-njh15f)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @jacobdeery, @KavinSatheeskumar, and @wendi-yu)

___
*[topside/pdl/package.py, line 47 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/109#-MMrziILBsa7sIdxUi59:-MMrziILBsa7sIdxUi5A:bclm6u2) ([raw file](https://github.com/waterloo-rocketry/topside/blob/553ffa6f9a3beb231b707eca052fb488301caee6/topside/pdl/package.py#L47)):*
> ```
> filenames = list(map(lambda fname: os.path.join(import_path, fname), filenames))
> ```
Is this doable with a list comprehension? I usually find those easier to read than `map`
___
*[topside/pdl/package.py, line 63 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/109#-MMs-O3x6AzhYmwMxixk:-MMs-O3x6AzhYmwMxixl:bfpx1an) ([raw file](https://github.com/waterloo-rocketry/topside/blob/553ffa6f9a3beb231b707eca052fb488301caee6/topside/pdl/package.py#L63)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>             for path in imports_folder:
>                 try:
>                     name = yaml.safe_load(open(path, 'r'))['name']
>                     if name in self.importable_files:
>                         self.importable_files[name].add(path)
>                     else:
>                         self.importable_files[name] = {path}
>                 except KeyError:
>                     warnings.warn(path + " does not describe a pdl file")
> ```
</details>

Is this block meant to be inside the `for import_path in self.import_paths:` loop? This would have us look at each import multiple times

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/109)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @jacobdeery, @KavinSatheeskumar, and @wendi-yu)

___
*[topside/pdl/package.py, line 47 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/109#-MMrziILBsa7sIdxUi59:-MMs6O8HB44AUq5PeaeQ:b-szxum8) ([raw file](https://github.com/waterloo-rocketry/topside/blob/553ffa6f9a3beb231b707eca052fb488301caee6/topside/pdl/package.py#L47)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> filenames = list(map(lambda fname: os.path.join(import_path, fname), filenames))
> ```
Is this doable with a list comprehension? I usually find those easier to read than `map`
</blockquote></details>

maybe
filenames = [for fname in filenames os.path.join(import_path, fname)]
if you want to keep it one line long

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/109)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[topside/pdl/parser.py, line 127 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/109#-MMs9ILZ0SmsfiUQtUbe:-MMs9ILZ0SmsfiUQtUbf:b9e6f6m) ([raw file](https://github.com/waterloo-rocketry/topside/blob/553ffa6f9a3beb231b707eca052fb488301caee6/topside/pdl/parser.py#L127)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     def add_import_path(self, newpaths):
>         '''Add a single path or iterable of paths to the import paths.'''
>         if not isinstance(newpaths, (list, tuple)):
>             newpaths = [newpaths]
>         self.import_paths.extend(newpaths)
> ```
</details>

Just a question, why do you make this a new list and then extend, rather than appending?

self.import_paths.append(newpaths)

**Review by KavinSatheeskumar — DISMISSED** [review]
Jacob covered it all, seems perfectly fine to me

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/109#-:-MMsCDbQC5h-j_-8sAeD:b-yxlyq4)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/109)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @jacobdeery)

___
*[topside/pdl/package.py, line 47 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/109#-MMrziILBsa7sIdxUi59:-MMwj-NuBONgXzgkIQH3:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/553ffa6f9a3beb231b707eca052fb488301caee6/topside/pdl/package.py#L47)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

maybe
filenames = [for fname in filenames os.path.join(import_path, fname)]
if you want to keep it one line long
</blockquote></details>

Done.
___
*[topside/pdl/package.py, line 63 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/109#-MMs-O3x6AzhYmwMxixk:-MMwjACI3-W2RTWEqWGu:b52460i) ([raw file](https://github.com/waterloo-rocketry/topside/blob/553ffa6f9a3beb231b707eca052fb488301caee6/topside/pdl/package.py#L63)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>             for path in imports_folder:
>                 try:
>                     name = yaml.safe_load(open(path, 'r'))['name']
>                     if name in self.importable_files:
>                         self.importable_files[name].add(path)
>                     else:
>                         self.importable_files[name] = {path}
>                 except KeyError:
>                     warnings.warn(path + " does not describe a pdl file")
> ```
Is this block meant to be inside the `for import_path in self.import_paths:` loop? This would have us look at each import multiple times
</blockquote></details>

Oops it's not, good catch 
___
*[topside/pdl/parser.py, line 127 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/109#-MMs9ILZ0SmsfiUQtUbe:-MMwjKd9ER7l3Y6APTlH:bq6kzig) ([raw file](https://github.com/waterloo-rocketry/topside/blob/553ffa6f9a3beb231b707eca052fb488301caee6/topside/pdl/parser.py#L127)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

> ```
>     def add_import_path(self, newpaths):
>         '''Add a single path or iterable of paths to the import paths.'''
>         if not isinstance(newpaths, (list, tuple)):
>             newpaths = [newpaths]
>         self.import_paths.extend(newpaths)
> ```
Just a question, why do you make this a new list and then extend, rather than appending?

self.import_paths.append(newpaths)
</blockquote></details>

I tried to set it up so that you could pass in either a single string path, or a list of string paths to add onto the import paths list. So basically if you pass in a single one, it'll change it to a list with a single element in it so that no matter what, in the next step we can extend `self.import_paths` with the new list.

**Review by jacobdeery — APPROVED** [review]
Apologies for the delay on the followup

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/109#-:-MN6i7kMCXaEwhKuq8Fu:b1ke07)* status: 0 of 5 files reviewed, all discussions resolved

**Pull request merged**
