### PR TITLE
Implement querying functions

### PR DESCRIPTION
**Pull request by wendi-yu**
Implemented querying functions to find node pressures, current states,
FC values at given parts of the graph.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/13)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
Sweet! Just one potential bug, but otherwise looks good

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/13#-:-M5NQ2G-5512ORskOhb8:bw90qly)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[topside/plumbing/plumbing_engine.py, line 39 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/13#-M5NLLFt2NAPjfTmzx3A:-M5NLLFt2NAPjfTmzx3B:b1otz5k) ([raw file](https://github.com/waterloo-rocketry/topside/blob/f63b10f2f462e4e19b6cd2c00882b511df0b4cbb/topside/plumbing/plumbing_engine.py#L39)):*
> ```Python
>         for name, component in self.component_dict.items():
>             name_valid = True
>             if name not in self.mapping:
> ```

this is much more pythonic, nice change
___
*[topside/plumbing/plumbing_engine.py, line 366 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/13#-M5NNTqhAlDeX1tLklEh:-M5NNTqhAlDeX1tLklEi:byk976h) ([raw file](https://github.com/waterloo-rocketry/topside/blob/f63b10f2f462e4e19b6cd2c00882b511df0b4cbb/topside/plumbing/plumbing_engine.py#L366)):*
> ```Python
>             if arg in self.component_dict:
>                 for edge in self.plumbing_graph.edges(keys=True):
>                     if arg in edge[2]:
> ```

This will fail if we ever have a component whose name is a substring of another component name (like `fill_valve` and `remote_fill_valve`). The user should pick better names than that, but we should still try to make this function robust against these cases.

Something like `edge[2].startswith(arg + '.')` should fully capture what we want.

(please add a unit test to guard against this case)
___
*[topside/plumbing/tests/test_plumbing_engine_querying.py, line 39 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/13#-M5NOYka-pQTnpnIqaWW:-M5NOYka-pQTnpnIqaWX:b-4wpvth) ([raw file](https://github.com/waterloo-rocketry/topside/blob/f63b10f2f462e4e19b6cd2c00882b511df0b4cbb/topside/plumbing/tests/test_plumbing_engine_querying.py#L39)):*
<details><summary><i alt="summary">Quoted 20 lines of code…</i></summary>

> ```
>     assert plumb.current_state('valve1') == 'open'
>     assert plumb.current_state(['valve1']) == 'open'
>     assert plumb.current_state() == {
>         'valve1': 'open',
>         'valve2': 'open'
>     }
>     assert plumb.current_state('valve1', 'valve2') == {
>         'valve1': 'open',
>         'valve2': 'open'
>     }
> 
>     assert plumb.current_state(['valve1', 'valve2']) == {
>         'valve1': 'open',
>         'valve2': 'open'
>     }
> 
>     assert plumb.current_state(['valve1'], 'valve2') == {
>         'valve1': 'open',
>         'valve2': 'open'
>     }
> ```
</details>


Nit: inconsistent newlines in this section

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/13)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @jacobdeery)

___
*[topside/plumbing/plumbing_engine.py, line 366 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/13#-M5NNTqhAlDeX1tLklEh:-M5NeW9-6TlF4ElphAVl:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/f63b10f2f462e4e19b6cd2c00882b511df0b4cbb/topside/plumbing/plumbing_engine.py#L366)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

This will fail if we ever have a component whose name is a substring of another component name (like `fill_valve` and `remote_fill_valve`). The user should pick better names than that, but we should still try to make this function robust against these cases.

Something like `edge[2].startswith(arg + '.')` should fully capture what we want.

(please add a unit test to guard against this case)
</blockquote></details>

Done.

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/13)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[topside/plumbing/tests/test_plumbing_engine_querying.py, line 147 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/13#-M5No6FF4vV4JL9iVh5C:-M5No6FF4vV4JL9iVh5D:bsdn8jm) ([raw file](https://github.com/waterloo-rocketry/topside/blob/94fa64499c80cd7f93e7ababb202142b2dabf6c3/topside/plumbing/tests/test_plumbing_engine_querying.py#L147)):*
> ```
>     assert (2, 3, 'remote_fill_valve.A1') not in plumb.current_FC('fill_valve')
>     assert (3, 2, 'remote_fill_valve.A2') not in plumb.current_FC('fill_valve')
> ```

should these be B1 and B2?

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/13)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @jacobdeery)

___
*[topside/plumbing/tests/test_plumbing_engine_querying.py, line 147 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/13#-M5No6FF4vV4JL9iVh5C:-M5O6DwcBh_nYcaRWDeH:bayb0dx) ([raw file](https://github.com/waterloo-rocketry/topside/blob/94fa64499c80cd7f93e7ababb202142b2dabf6c3/topside/plumbing/tests/test_plumbing_engine_querying.py#L147)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>     assert (2, 3, 'remote_fill_valve.A1') not in plumb.current_FC('fill_valve')
>     assert (3, 2, 'remote_fill_valve.A2') not in plumb.current_FC('fill_valve')
> ```

should these be B1 and B2?
</blockquote></details>

You're right my bad

**Review by jacobdeery — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/13#-:-M5OQbYIDv9z-6ZLS6dA:bnfp4nl)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @jacobdeery)

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/13)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[topside/plumbing/tests/test_plumbing_utils.py, line 43 at r4](https://reviewable.io/reviews/waterloo-rocketry/topside/13#-M5P3E4O-Pj8yhk4beGe:-M5P3E4O-Pj8yhk4beGf:bs3p4jz) ([raw file](https://github.com/waterloo-rocketry/topside/blob/f73a481f734a63c28c336d659f203aeab9414fbf/topside/plumbing/tests/test_plumbing_utils.py#L43)):*
> ```Python
> 
> 
> def test_flatten():
> ```

Can you add test cases here for `allow_tuples`?

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/13)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @jacobdeery)

___
*[topside/plumbing/tests/test_plumbing_utils.py, line 43 at r4](https://reviewable.io/reviews/waterloo-rocketry/topside/13#-M5P3E4O-Pj8yhk4beGe:-M5P8uj2EX8_P4M_wese:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/topside/blob/f73a481f734a63c28c336d659f203aeab9414fbf/topside/plumbing/tests/test_plumbing_utils.py#L43)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Can you add test cases here for `allow_tuples`?
</blockquote></details>

Done

**Review by jacobdeery — APPROVED** [review]
Unit tests are great

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/13#-:-M5PEBrF7N6sbegVf-3t:b-97cigl)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @jacobdeery)

**Pull request merged**
