### PR TITLE
app: Integrate plumbing engine and PDL loading

### PR DESCRIPTION
**Pull request by jacobdeery**
Adds the ability to load a plumbing engine from a PDL file and have it
visualized in the plumbing pane. The plumbing engine is connected to the
procedures engine and is affected by actions in the procedure. Also
adds time controls to the UI. Currently, only "step forward" and
"advance" do anything (step forward steps time by 100ms and advance runs
the plumbing engine to steady-state with a 30s timeout).

Depends on:

- [x] #58
- [x] #77
- [x] #78.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/79)

### CODE REVIEW

**Comment by jacobdeery** [comment]
This is stacked on top of 3 other PRs, so probably not worth reviewing until the others are merged and the diff is smaller.

**Review by wendi-yu — COMMENTED** [review]
The plumbing bits look good to me overall! Wow this is exciting we're getting all the parts wired together :)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/79#-:-MJh5GiZ-Ti9PGsg6oPg:b-y6tz8p)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @Code-Titan, @jacobdeery, and @wendi-yu)

___
*[application/plumbing_bridge.py, line 19 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/79#-MJh-rPw2_kpoKWiyA_y:-MJh-rPxE-rzssxc2SmA:b-eg378d) ([raw file](https://github.com/waterloo-rocketry/topside/blob/e9a0e8e801bd12c7a8ab329ce0a85ba5d3660d3e/application/plumbing_bridge.py#L19)):*
> ```Python
>         self.engineLoaded.emit(new_engine)
> 
>     def load_from_file(self, filepath):
> ```

It would be nice to support loading in multiple files at once through the application, since the parser can handle it. I think if you use `args` for the `filepath` inputs, it'll give you a list that you can feed directly to the `Parser`.  Not sure how to handle this on the Qt side though.
___
*[application/procedures_bridge.py, line 50 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/79#-MJh3tpP65UI3ic3MYC6:-MJh3tpP65UI3ic3MYC7:b-z3t9dl) ([raw file](https://github.com/waterloo-rocketry/topside/blob/e9a0e8e801bd12c7a8ab329ce0a85ba5d3660d3e/application/procedures_bridge.py#L50)):*
> ```Python
>         # able to notify the Qt engine when a condition ticks from
>         # unsatisfied to satisfied or vice-versa. This isn't the
>         # cleanest way to do it - is there a better alternative?
> ```

Yeah I agree that loose data associations feel messy, but I also think this is fine for now. Can be a brain teaser for an ambitious first year or something :)
___
*[application/procedures_bridge.py, line 217 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/79#-MJh4w2TD2SAgll3WMjX:-MJh4w2V6a2ymLofoCON:b-me4y6w) ([raw file](https://github.com/waterloo-rocketry/topside/blob/e9a0e8e801bd12c7a8ab329ce0a85ba5d3660d3e/application/procedures_bridge.py#L217)):*
> ```Python
>         step_size = 0.1e6  # TODO(jacob): Add a UI field for this.
>         self._proc_eng.step_time(step_size)
>         self._plumb.engine.current_pressures()
> ```

`current_pressures()` returns a dict of `{node : pressure}`, but it doesn't look like we're doing anything with the return value here? It doesn't make any in-place modifications either that I'm aware of?
___
*[application/resources/PlumbingPane.qml, line 84 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/79#-MJh1baG9s_tlOSkRtKt:-MJh1baG9s_tlOSkRtKu:bnvmg9g) ([raw file](https://github.com/waterloo-rocketry/topside/blob/e9a0e8e801bd12c7a8ab329ce0a85ba5d3660d3e/application/resources/PlumbingPane.qml#L84)):*
> ```QML
>                 property bool is_play: true
>                 icon.source: is_play ? "themes/default/play.png" : "themes/default/pause.png"
>                 
> ```

whitespace :0

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/79)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @Code-Titan and @wendi-yu)

___
*[application/plumbing_bridge.py, line 19 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/79#-MJh-rPw2_kpoKWiyA_y:-MJhBdX16SL1p5dPmXGJ:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/e9a0e8e801bd12c7a8ab329ce0a85ba5d3660d3e/application/plumbing_bridge.py#L19)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

It would be nice to support loading in multiple files at once through the application, since the parser can handle it. I think if you use `args` for the `filepath` inputs, it'll give you a list that you can feed directly to the `Parser`.  Not sure how to handle this on the Qt side though.
</blockquote></details>

Done.
___
*[application/procedures_bridge.py, line 217 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/79#-MJh4w2TD2SAgll3WMjX:-MJhAQd06m0aqbdjP84A:b7h1kzr) ([raw file](https://github.com/waterloo-rocketry/topside/blob/e9a0e8e801bd12c7a8ab329ce0a85ba5d3660d3e/application/procedures_bridge.py#L217)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

`current_pressures()` returns a dict of `{node : pressure}`, but it doesn't look like we're doing anything with the return value here? It doesn't make any in-place modifications either that I'm aware of?
</blockquote></details>

Not really sure what this was doing. At one point I was printing out the values for debug; this is probably just left over from then. Removed.
___
*[application/resources/PlumbingPane.qml, line 84 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/79#-MJh1baG9s_tlOSkRtKt:-MJhAixTDtdA7g4wIVkp:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/e9a0e8e801bd12c7a8ab329ce0a85ba5d3660d3e/application/resources/PlumbingPane.qml#L84)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

whitespace :0
</blockquote></details>

Done.

**Review by wendi-yu — APPROVED** [review]
Cool, looks awesome! I think it would be nice to just have the pressures of nodes printed to screen (doesn't have to be pretty or formatted, like we could just splat the `current_pressures()` dict on there) as a placeholder, just to be able to see the plumbing engine buttons doing something. Doesn't have to be this PR though, what we have now LGTM :)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/79#-:-MJhJHfT69xxTShpGNGm:b-vlpaxc)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @Code-Titan)

**Review by jacobdeery — COMMENTED** [review]
Sg, will leave to the next PR (primitive DAQ)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/79#-:-MJhNRLeBoswew20Oq0J:bf4ld3v)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @Code-Titan)

**Pull request merged**
