### PR TITLE
proc: Add string representations for conditions

### LINKED ISSUE #96: Add string representations for conditions
Right now, we display procedures like this:
image

Ideally, the `Greater` condition would be displayed much more concise; something like `D > 400`.

Changes required: In `topside/procedures/conditions.py`, add appropriate `__str__` methods for all of the condition classes.

### PR DESCRIPTION
**Pull request by abutchart**
Used the format in the export methods, modified where needed

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/110)

### CODE REVIEW

**Review by wendi-yu — COMMENTED** [review]
Wow imagine giving an unsolicited review :^) small comment but looks good overall, you said you're adding unit tests so I'll just sneak in a comment before that

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/110#-:-MNVnjmV7H8fViBoyWZK:b-3xla24)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @brianbutchart and @jacobdeery)

___
*[topside/procedures/conditions.py, line 41 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/110#-MNVlRp18c0K2F22BNDo:-MNVl3bK3Aa79rqjsRnW:b7kxsml) ([raw file](https://github.com/waterloo-rocketry/topside/blob/7bf197cee90ff7f19b566ac524f69f20f8e91743/topside/procedures/conditions.py#L41)):*
> ```Python
> 
>     def __str__(self):
>         return ' and '.join([cond for cond in self._conditions])
> ```

Nitpick but it I think we can nest conditions, so it might be helpful to have brackets around the whole clause. That way we can remove ambiguity in case we ever nest ands and ors together. It's a little uglier when it's just one condition on its own though, and I don't think nesting will be super common - so up to you? Same goes for the `Or` class.

**Review by abutchart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/110)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jacobdeery and @wendi-yu)

___
*[topside/procedures/conditions.py, line 41 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/110#-MNVlRp18c0K2F22BNDo:-MNVxRVAE7QHR94UVLCq:b4eteqm) ([raw file](https://github.com/waterloo-rocketry/topside/blob/7bf197cee90ff7f19b566ac524f69f20f8e91743/topside/procedures/conditions.py#L41)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Nitpick but it I think we can nest conditions, so it might be helpful to have brackets around the whole clause. That way we can remove ambiguity in case we ever nest ands and ors together. It's a little uglier when it's just one condition on its own though, and I don't think nesting will be super common - so up to you? Same goes for the `Or` class.
</blockquote></details>

Added brackets.

**Review by jacobdeery — COMMENTED** [review]
Tests look good, just one tiny comment

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/110#-:-MNlAL_QAYc7S-z7lWZP:b-azvujl)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @brianbutchart, @jacobdeery, and @wendi-yu)

___
*[topside/procedures/conditions.py, line 8 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/110#-MNl9rmx4yMJuxOfWkMh:-MNl9rmx4yMJuxOfWkMi:bexzlgu) ([raw file](https://github.com/waterloo-rocketry/topside/blob/1457c9601287cb981186530c6b2ef4b36750c0ef/topside/procedures/conditions.py#L8)):*
> ```
> Condition always satisfied
> ```
I think just "Immediately" might be cleaner

**Review by abutchart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/110)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[topside/procedures/conditions.py, line 8 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/110#-MNl9rmx4yMJuxOfWkMh:-MNlCWNX0KRI0VkYzfNC:b-a2ujfl) ([raw file](https://github.com/waterloo-rocketry/topside/blob/1457c9601287cb981186530c6b2ef4b36750c0ef/topside/procedures/conditions.py#L8)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> Condition always satisfied
> ```
I think just "Immediately" might be cleaner
</blockquote></details>

Changed.

**Review by jacobdeery — APPROVED** [review]
:lgtm:, thanks!

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/110#-:-MNlCkpa4ACTnR6pLXXg:bpqxd5f)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

**Pull request merged**
