### PR TITLE
PDL: Add support for default arguments in typedefs

### LINKED ISSUE #46: Support default arguments in PDL typedefs
Add support for specifying default values for the parameters specified in PDL typedefs. A rough list of what this would probably entail:
* coming up with an unambiguous syntax to specify a default argument in PDL. Could be modeled off existing syntax, for example what Python does (`parameter=default_value` in the definition)
* storing default arguments in `Files` and `Packages`
* logic in `File` component validation to only throw an error if a parameter isn't present **and** it doesn't have a default value specified
* logic to use user-provided values if they're present, default values if not in the typedef-replacement stage of `Package` validation

### PR DESCRIPTION
**Pull request by abutchart**
Uses Python default argument syntax (e.g. `params: [edge1, open_teq, closed_teq=closed]`)

Added error handling for when a parameter is absent and no default argument is specified, as well as when the default argument is blank (e.g. `params: [edge1, open_teq, closed_teq=]`)

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/94)

### CODE REVIEW

**Review by wendi-yu — COMMENTED** [review]
This looks _really_ great, thanks so much for doing this! I really like the way you've implemented the default arguments, I'm impressed that you deciphered so much PDL code lol I wrote this and it still confuses me sometimes. I left a few comments throughout, mostly just to clean up the code a little bit. Otherwise it looks really good!

As a general comment, it might also be good to add a few extra unit tests that cover default argument functionality specifically. We are already testing it in the giant `example.pdl` test, but that's almost more an integration test. If it ever fails, we probably want to provide more granularity as to what exactly went wrong with unit tests for specific default argument functionality. Maybe things like just a standard default argument working, taking a specified value over a default value, errors on illegal default value, etc. 

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/94#-:-MKDfqaw1Ox-gCS_m5K2:b-1d1bui)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @brianbutchart and @wendi-yu)

___
*[topside/pdl/example.yaml, line 54 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/94#-MKDUK0BCL4PTmn8J7Xm:-MKDSAAX1M9j8fnxgD7c:bue47j4) ([raw file](https://github.com/waterloo-rocketry/topside/blob/707dc2c3d8da10d48f69c016175f37bc28db8a93/topside/pdl/example.yaml#L54)):*
> ```YAML
>       edge_name: fav_edge
>       open_teq: 5
>       closed_teq: closed
> ```

Let's leave one of them as specifying a value for `closed_teq`, just to make sure that specifying an argument for a parameter that takes a default value still works. We probably want to specify something other than the default value of `closed` then, maybe just a very large `teq` like 100 or something.
___
*[topside/pdl/file.py, line 139 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/94#-MKDT_dK4VqXELkmKadr:-MKDSm7G4Pg0M03Pl3IJ:b-63r5jk) ([raw file](https://github.com/waterloo-rocketry/topside/blob/707dc2c3d8da10d48f69c016175f37bc28db8a93/topside/pdl/file.py#L139)):*
> ```Python
>         # TODO(wendi): support default arguments
>         params = self.typedefs[def_type]['params']
>         if len(params) != len(entry['params']):
> ```

Maybe we shouldn't remove this error check entirely - we could check that `len(entry['params']) <= len(params)`?
___
*[topside/pdl/file.py, line 147 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/94#-MKDT54T27LUeD0Dhkbp:-MKDT54T27LUeD0Dhkbq:bo7vh7d) ([raw file](https://github.com/waterloo-rocketry/topside/blob/77e5c311634740d3e32eda85268b134b452e53ef/topside/pdl/file.py#L147)):*
> ```Python
>                     raise exceptions.BadInputError("default argument operator ('=') used for "
>                                                     f"param {param} but no argument found")
>                 
> ```

Some extra whitespace floating around here - we have an autoformatting script that cleans this stuff up throughout the code. You can run it with `./tools/format.sh` from the root of the repo :)
___
*[topside/pdl/file.py, line 149 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/94#-MKDbSkZERNGJ647SN3C:-MKDbSkZERNGJ647SN3D:bsl3pzd) ([raw file](https://github.com/waterloo-rocketry/topside/blob/77e5c311634740d3e32eda85268b134b452e53ef/topside/pdl/file.py#L149)):*
> ```Python
>                 
>                 if param not in entry['params']:
>                     entry['params'][default_param[0]] = default_param[1]
> ```

I'm not sure if the assigning here is necessary - I think we generally just try to validate in the `File` part of the whole PDL process without making any changes, which should probably be documented somewhere (my bad lol). We're already doing the actual assigning in the `Package` code, so I think for the sake of separating concerns we shouldn't do it again here to make the code cleaner. 

Since we're doing the process of splitting and checking the two values again later on, it might be helpful to pull that out into a small helper function to avoid repeating code, and so that it's easier to change later on if we ever make adjustments in how we implement default parameters. 
___
*[topside/pdl/package.py, line 158 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/94#-MKDf02V9JAmreBT54Ua:-MKDf02V9JAmreBT54Ub:b-yledem) ([raw file](https://github.com/waterloo-rocketry/topside/blob/77e5c311634740d3e32eda85268b134b452e53ef/topside/pdl/package.py#L158)):*
> ```Python
>             if '=' in param:
>                 default_param = param.split('=')
>                 if not default_param[1]:
> ```

In a similar vein, since we already checked for default parameter validity before, we probably don't need to check again here. By the time we get to the Package code we should be able to just assume that everything's valid PDL, and do the actual assignment here. 
___
*[topside/pdl/package.py, line 165 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/94#-MKDffja1HhBLtc27zgu:-MKDffja1HhBLtc27zgv:b-6btfyh) ([raw file](https://github.com/waterloo-rocketry/topside/blob/77e5c311634740d3e32eda85268b134b452e53ef/topside/pdl/package.py#L165)):*
> ```Python
>                     component['params'][default_param[0]] = default_param[1]
> 
>             elif param not in component['params']:
> ```

Same with the error check here - mostly to avoid repeating code.

**Review by abutchart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/94)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @wendi-yu)

___
*[topside/pdl/example.yaml, line 54 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/94#-MKDUK0BCL4PTmn8J7Xm:-MKgMtbnBieRBk7aGvJO:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/707dc2c3d8da10d48f69c016175f37bc28db8a93/topside/pdl/example.yaml#L54)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Let's leave one of them as specifying a value for `closed_teq`, just to make sure that specifying an argument for a parameter that takes a default value still works. We probably want to specify something other than the default value of `closed` then, maybe just a very large `teq` like 100 or something.
</blockquote></details>

Done.
___
*[topside/pdl/file.py, line 139 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/94#-MKDT_dK4VqXELkmKadr:-MKgNLhN4DlNNg3VnojP:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/707dc2c3d8da10d48f69c016175f37bc28db8a93/topside/pdl/file.py#L139)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Maybe we shouldn't remove this error check entirely - we could check that `len(entry['params']) <= len(params)`?
</blockquote></details>

Done.
___
*[topside/pdl/file.py, line 147 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/94#-MKDT54T27LUeD0Dhkbp:-MKgNFjb5IzwDbMIZU_9:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/77e5c311634740d3e32eda85268b134b452e53ef/topside/pdl/file.py#L147)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Some extra whitespace floating around here - we have an autoformatting script that cleans this stuff up throughout the code. You can run it with `./tools/format.sh` from the root of the repo :)
</blockquote></details>

Done.
___
*[topside/pdl/file.py, line 149 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/94#-MKDbSkZERNGJ647SN3C:-MKgNWIW7ScGs4m2cC8R:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/77e5c311634740d3e32eda85268b134b452e53ef/topside/pdl/file.py#L149)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

I'm not sure if the assigning here is necessary - I think we generally just try to validate in the `File` part of the whole PDL process without making any changes, which should probably be documented somewhere (my bad lol). We're already doing the actual assigning in the `Package` code, so I think for the sake of separating concerns we shouldn't do it again here to make the code cleaner. 

Since we're doing the process of splitting and checking the two values again later on, it might be helpful to pull that out into a small helper function to avoid repeating code, and so that it's easier to change later on if we ever make adjustments in how we implement default parameters. 
</blockquote></details>

Done.
___
*[topside/pdl/package.py, line 158 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/94#-MKDf02V9JAmreBT54Ua:-MKgNYdY4AW6gWu--PK6:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/77e5c311634740d3e32eda85268b134b452e53ef/topside/pdl/package.py#L158)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

In a similar vein, since we already checked for default parameter validity before, we probably don't need to check again here. By the time we get to the Package code we should be able to just assume that everything's valid PDL, and do the actual assignment here. 
</blockquote></details>

Done.
___
*[topside/pdl/package.py, line 165 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/94#-MKDffja1HhBLtc27zgu:-MKgNZqq2UyBdB0TlK--:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/77e5c311634740d3e32eda85268b134b452e53ef/topside/pdl/package.py#L165)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Same with the error check here - mostly to avoid repeating code. 
</blockquote></details>

Done.

**Review by wendi-yu — COMMENTED** [review]
Looks really good! Some tiny nits, and after that we should be good to go :)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/94#-:-MKgVKZwDFrdtLp7bpTu:b-4ml34j)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @brianbutchart and @wendi-yu)

___
*[topside/pdl/file.py, line 140 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/94#-MKgUq059Gyzha4ulZHd:-MKgUq059Gyzha4ulZHe:b-ddb1w5) ([raw file](https://github.com/waterloo-rocketry/topside/blob/d3077585231b7d741d9ac1b3763e7ac4d0750c0a/topside/pdl/file.py#L140)):*
> ```Python
>         params = self.typedefs[def_type]['params']
>         if len(params) < len(entry['params']):
>             raise exceptions.BadInputError(f"params ({entry['params']}) present in component "
> ```

This error specifically isn't covered by the unit tests - would you mind restoring the unit test you took out? That should bring the code coverage of this diff to 100% and inch us that much closer to having a green codecov badge lol :)
___
*[topside/pdl/file.py, line 141 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/94#-MKgUl_l05bX3mqrNMLo:-MKgUl_m6DbNTeCZC36W:b-yxggli) ([raw file](https://github.com/waterloo-rocketry/topside/blob/d3077585231b7d741d9ac1b3763e7ac4d0750c0a/topside/pdl/file.py#L141)):*
> ```Python
>         if len(params) < len(entry['params']):
>             raise exceptions.BadInputError(f"params ({entry['params']}) present in component "
>                                            "declaration not found in typedef decleration")
> ```

`decleration` -> `declaration`

**Review by abutchart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/94)* status: 0 of 6 files reviewed, all discussions resolved

___
*[topside/pdl/file.py, line 140 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/94#-MKgUq059Gyzha4ulZHd:-MKuHO9s-qKMnjUKi5Co:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/d3077585231b7d741d9ac1b3763e7ac4d0750c0a/topside/pdl/file.py#L140)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

This error specifically isn't covered by the unit tests - would you mind restoring the unit test you took out? That should bring the code coverage of this diff to 100% and inch us that much closer to having a green codecov badge lol :)
</blockquote></details>

Done.
___
*[topside/pdl/file.py, line 141 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/94#-MKgUl_l05bX3mqrNMLo:-MKuHQSw71zDSyS-NtjA:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/d3077585231b7d741d9ac1b3763e7ac4d0750c0a/topside/pdl/file.py#L141)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

`decleration` -> `declaration`
</blockquote></details>

Done.

**Review by wendi-yu — APPROVED** [review]
:lgtm: don't forget to follow the stuff in CONTRIBUTING.md when you merge, otherwise we're good :)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/94#-:-MKv1TdZASIFYALqB4Mz:b-iatmey)* status: 0 of 6 files reviewed, all discussions resolved

**Pull request merged**
