### PR TITLE
Add better error catching for components

### PR DESCRIPTION
**Pull request by wendi-yu**
Added more error catches for components, and added a check in the Plumbing Engine to prevent loading in invalid components. 
Also applied the PlumbingEngine code fixes we've made in the past while to PlumbingComponent, like changing `is_valid()` and querying functions.
While I was at it I also added some super basic querying functions and updated the unit tests to use those rather than Networkx functions.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/15)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/15)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[topside/plumbing/plumbing_component.py, line 26 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/15#-M5TfT3c6WD9bWC5Rlq0:-M5TfT3dDS3vJlqUhctX:b4feula) ([raw file](https://github.com/waterloo-rocketry/topside/blob/87fdefc9349952d8f8a29980454c1b92e0e716f1/topside/plumbing/plumbing_component.py#L26)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>             last_len = len(edge_set)
>             edge_set.add(edge)
>             if len(edge_set) == last_len:
>                 error = invalid.InvalidComponentEdge(
>                     f"Duplicate edges '{edge}' found in edge list.", edge)
>                 invalid.add_error(error, self.error_set)
> ```
</details>


This is one way to do it, but I wonder if it's the most intuitive. I think checking `edge in edge_set` _before_ adding rather than checking if the length changes _after_ adding might be a bit more clear at first glance - will that work, or am I overlooking something?
___
*[topside/plumbing/plumbing_engine.py, line 393 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/15#-M5TgM8H9-77581ntuNU:-M5TgM8H9-77581ntuNV:bfbgkxj) ([raw file](https://github.com/waterloo-rocketry/topside/blob/87fdefc9349952d8f8a29980454c1b92e0e716f1/topside/plumbing/plumbing_engine.py#L393)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     def list_errors(self):
>         return self.error_set
> 
>     def list_nodes(self, data=True):
>         return list(self.plumbing_graph.nodes(data=data))
> 
>     def list_edges(self, data=True):
>         return list(self.plumbing_graph.edges(keys=True, data=data))
> ```
</details>


I think these can just be named `errors()`, `nodes()`, and `edges()` to be concise

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/15)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @jacobdeery)

___
*[topside/plumbing/plumbing_component.py, line 26 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/15#-M5TfT3c6WD9bWC5Rlq0:-M5Tm8NxD6XsL3w8NfXv:bxm505z) ([raw file](https://github.com/waterloo-rocketry/topside/blob/87fdefc9349952d8f8a29980454c1b92e0e716f1/topside/plumbing/plumbing_component.py#L26)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>             last_len = len(edge_set)
>             edge_set.add(edge)
>             if len(edge_set) == last_len:
>                 error = invalid.InvalidComponentEdge(
>                     f"Duplicate edges '{edge}' found in edge list.", edge)
>                 invalid.add_error(error, self.error_set)
> ```

This is one way to do it, but I wonder if it's the most intuitive. I think checking `edge in edge_set` _before_ adding rather than checking if the length changes _after_ adding might be a bit more clear at first glance - will that work, or am I overlooking something?
</blockquote></details>

Yeah you're right, that's definitely more intuitive. 
___
*[topside/plumbing/plumbing_engine.py, line 393 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/15#-M5TgM8H9-77581ntuNU:-M5Tlt3X1Vfubeoac1rZ:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/87fdefc9349952d8f8a29980454c1b92e0e716f1/topside/plumbing/plumbing_engine.py#L393)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>     def list_errors(self):
>         return self.error_set
> 
>     def list_nodes(self, data=True):
>         return list(self.plumbing_graph.nodes(data=data))
> 
>     def list_edges(self, data=True):
>         return list(self.plumbing_graph.edges(keys=True, data=data))
> ```

I think these can just be named `errors()`, `nodes()`, and `edges()` to be concise
</blockquote></details>

Done.

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/15)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @wendi-yu)

___
*[topside/plumbing/plumbing_component.py, line 59 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/15#-M5To2kB9Rbi73qUUZJP:-M5To2kB9Rbi73qUUZJQ:bm89ifl) ([raw file](https://github.com/waterloo-rocketry/topside/blob/0ba6e74ff814768c633040bf44119d8ca173c6f1/topside/plumbing/plumbing_component.py#L59)):*
> ```Python
>         return len(self.error_set) == 0
> 
>     def list_errors(self):
> ```

Just `errors` to line up with PlumbingEngine?

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/15)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @jacobdeery)

___
*[topside/plumbing/plumbing_component.py, line 59 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/15#-M5To2kB9Rbi73qUUZJP:-M5Tr1UjEQ_I7oCnJRG_:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/0ba6e74ff814768c633040bf44119d8ca173c6f1/topside/plumbing/plumbing_component.py#L59)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Just `errors` to line up with PlumbingEngine?
</blockquote></details>

Done.

**Review by jacobdeery — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/15#-:-M5U1jhX7asWnpcGZH33:bnfp4nl)* status: 1 of 7 files reviewed, all discussions resolved

**Pull request merged**
