### PR TITLE
app/proc: Load real procedures and upgrade viz

### PR DESCRIPTION
**Pull request by jacobdeery**
- Add a menu for opening a ProcLang file in the application (available
with Ctrl-O)
- Add utility functions to the ProceduresEngine for loading a new suite
and resetting
- Add visualization of ProcedureStep conditions/transitions
- Add a bunch of TODOs

The procedures pane will look like this for now:
image

We haven't merged #54 yet, so there's no pretty string representation, but once we get those in it will look a bit more concise.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/58)

### CODE REVIEW

**Review by wendi-yu — DISMISSED** [review]
Yeah looks good! I tried out loading the example proclang doc from the menu and moving through the steps, everything seems to work well (including the highlighting we talked about :0) Admittedly I don't have a ton of insight to offer on the Qt stuff though :)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/58#-:-MHKDrIAB5jhZPmJhKkY:b-cfzkx8)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @Code-Titan, @jacobdeery, and @wendi-yu)

___
*[application/procedures_bridge.py, line 156 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/58#-MHK8K4U-WiY3j_G6xh6:-MHK8K4U-WiY3j_G6xh7:b-1aqg4d) ([raw file](https://github.com/waterloo-rocketry/topside/blob/a9508e701ab369a6830ef2df21c3037cbf8ffb00/application/procedures_bridge.py#L156)):*
> ```Python
>     @Slot()
>     def stop(self):
>         # TODO(jacob): Should this reset the plumbing engine as well?
> ```

I think it makes sense for it to reset the plumbing engine - if we didn't, we'd end up with the procedures reset and ready to work on a plumbing engine in a modified state. If we just wanted to do something custom to the current plumbing engine state I think it makes more sense to pause than to stop?
___
*[application/resources/ProceduresPane.qml, line 73 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/58#-MHK9NoxE17mKmS5BO4B:-MHK9NoxE17mKmS5BO4C:bkb4aoh) ([raw file](https://github.com/waterloo-rocketry/topside/blob/a9508e701ab369a6830ef2df21c3037cbf8ffb00/application/resources/ProceduresPane.qml#L73)):*
> ```QML
>             width: proceduresList.width
>             height: procedureColumn.height + 10
>             color: ListView.isCurrentItem ? "#d8fff7" : (index % 2 == 0 ? "#f2f2f2" : "#f9f9f9")
> ```

Is there any way to name the colours more friendly-ily? It's a minor inconvenience since I'm pretty sure most editors give a sample colour anyways but just asking - maybe worth looking into if there's a way to globally assign names to theme colours or something, once UI becomes a thing that we care about more.

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/58)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @Code-Titan and @wendi-yu)

___
*[application/procedures_bridge.py, line 156 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/58#-MHK8K4U-WiY3j_G6xh6:-MHYcPNY7Y8dvhB2ootK:b-c6witt) ([raw file](https://github.com/waterloo-rocketry/topside/blob/a9508e701ab369a6830ef2df21c3037cbf8ffb00/application/procedures_bridge.py#L156)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

I think it makes sense for it to reset the plumbing engine - if we didn't, we'd end up with the procedures reset and ready to work on a plumbing engine in a modified state. If we just wanted to do something custom to the current plumbing engine state I think it makes more sense to pause than to stop?
</blockquote></details>

Yeah, I would tend to agree with that. I'll leave that for a future PR because right now there isn't a plumbing engine `reset()` method.
___
*[application/resources/ProceduresPane.qml, line 73 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/58#-MHK9NoxE17mKmS5BO4B:-MHYg8QoBiQzK0Yrz8H6:b-ez000h) ([raw file](https://github.com/waterloo-rocketry/topside/blob/a9508e701ab369a6830ef2df21c3037cbf8ffb00/application/resources/ProceduresPane.qml#L73)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Is there any way to name the colours more friendly-ily? It's a minor inconvenience since I'm pretty sure most editors give a sample colour anyways but just asking - maybe worth looking into if there's a way to globally assign names to theme colours or something, once UI becomes a thing that we care about more.
</blockquote></details>

I've turned these into properties instead of hardcoded inline strings. Pulling them out into a global theme will probably require a bit more work; I'll open an issue and leave that for a future PR.

**Review by wendi-yu — DISMISSED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/58#-:-MI1NVQO6A_FUihQLfmQ:bb6ywmx)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @Code-Titan and @wendi-yu)

___
*[application/procedures_bridge.py, line 156 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/58#-MHK8K4U-WiY3j_G6xh6:-MI1M3cF-cFgC_YO2H83:b-749ja6) ([raw file](https://github.com/waterloo-rocketry/topside/blob/a9508e701ab369a6830ef2df21c3037cbf8ffb00/application/procedures_bridge.py#L156)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Yeah, I would tend to agree with that. I'll leave that for a future PR because right now there isn't a plumbing engine `reset()` method.
</blockquote></details>

Huh, I guess there isn't. Sounds like it could be a good first issue :0 
___
*[application/resources/ProceduresPane.qml, line 73 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/58#-MHK9NoxE17mKmS5BO4B:-MI1MlhHDk6fWnO90Eai:b6jr532) ([raw file](https://github.com/waterloo-rocketry/topside/blob/a9508e701ab369a6830ef2df21c3037cbf8ffb00/application/resources/ProceduresPane.qml#L73)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

I've turned these into properties instead of hardcoded inline strings. Pulling them out into a global theme will probably require a bit more work; I'll open an issue and leave that for a future PR.
</blockquote></details>

Cool cool, I was just thinking about how tailwind does it (global JSON config file, iirc). Could be a cool new thing to implement later on, imo it definitely makes UI stuff cleaner and nicer to work with - but it'll definitely be more helpful if/when we have a decided UI with actual theme colours to implement and stuff :)

**Comment by jacobdeery** [comment]
Ready to go now that all of the other prerequisite PRs are in!

**Review by wendi-yu — APPROVED** [review]
Ah very cool I like it! I assume the newly rebased stuff was code reviewed. I can't step through the procedure loaded from `example.proc` when I run the application, not sure if that's expected? Looks good otherwise. It'll be really exciting once we connect this to loading in a plumbing engine system from PDL as well. 

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/58#-:-MIzzigs3ScxOHBUzulN:b-affs94)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @Code-Titan, @jacobdeery, and @wendi-yu)

___
*[application/procedures_bridge.py, line 136 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/58#-MIzyBXT47dnwzt2IuPK:-MIzyBXT47dnwzt2IuPL:b-5p4b2k) ([raw file](https://github.com/waterloo-rocketry/topside/blob/da73d0bc21ee0b046ec03d034eb84a62b4d5d0af/application/procedures_bridge.py#L136)):*
> ```Python
>     @Slot()
>     def loadProcedureSuite(self):
>         # TODO(jacob): Make this menu remember the last file opened
> ```

Good first issue?

**Review by jacobdeery — COMMENTED** [review]
> I can't step through the procedure loaded from example.proc when I run the application, not sure if that's expected?

Discussed offline, expected behaviour for the procedure in question

> It'll be really exciting once we connect this to loading in a plumbing engine system from PDL as well.

Stay tuned for #79!

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/58#-:-MJ-1cxIDERNzU9HR1lh:b-9zgh3c)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @Code-Titan and @wendi-yu)

___
*[application/procedures_bridge.py, line 136 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/58#-MIzyBXT47dnwzt2IuPK:-MJ-2BhhEp0plhg-vVko:b-7yu7nj) ([raw file](https://github.com/waterloo-rocketry/topside/blob/da73d0bc21ee0b046ec03d034eb84a62b4d5d0af/application/procedures_bridge.py#L136)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Good first issue?
</blockquote></details>

Wilco

**Pull request merged**
