### PR TITLE
Add reset function and test reset function for plumbing engine

### LINKED ISSUE #69: Add `reset()` function to plumbing engine
We don't currently have a way of resetting a plumbing engine to its initial state, which would be useful when navigating through operations procedures (in order to be able to sync procedure resets with plumbing engine resets).

The actual code to reset shouldn't be difficult - likely just resetting some counters and reloading initial states and pressures, which is already done on initialization. It's a good chance to get familiar with the pieces of the plumbing engine though (since you'd need to figure out what exactly needs resetting), and this function is pretty conducive to writing unit tests if anyone wants to take a first crack at that.

### PR DESCRIPTION
**Pull request by TieuKhang**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/97)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
This looks mostly good to me; I'll let Wendi give the more comprehensive review, just wanted to leave the one comment.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/97#-:-MKSCxC6AyErdR-6w-G-:b-c5v2ag)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @TieuKhang and @wendi-yu)

___
*[topside/plumbing/plumbing_engine.py, line 64 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/97#-MKSCui4DxODanmn3fiG:-MKSCui4DxODanmn3fiH:boqpn99) ([raw file](https://github.com/waterloo-rocketry/topside/blob/1fb10246386cc29d5b2529b913e5fd60d8a16115/topside/plumbing/plumbing_engine.py#L64)):*
> ```Python
>         self.load_graph(components, mapping, initial_pressures, initial_states)
> 
>     def reset(self):
> ```

I think we should also reset `time` to 0 here

**Review by wendi-yu — COMMENTED** [review]
This looks really good overall, I especially appreciate the unit test coverage! The comments I've left are mostly add-ons to tidy up the code for merging. Looks great!

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/97#-:-MKT2xyo2Fg0A-00SnVL:b-mms7ij)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @jacobdeery, @TieuKhang, and @wendi-yu)

___
*[topside/plumbing/plumbing_engine.py, line 64 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/97#-MKSCui4DxODanmn3fiG:-MKT3XWS1BYuI0YnaDbL:by3wdbf) ([raw file](https://github.com/waterloo-rocketry/topside/blob/1fb10246386cc29d5b2529b913e5fd60d8a16115/topside/plumbing/plumbing_engine.py#L64)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

I think we should also reset `time` to 0 here
</blockquote></details>

yep, agreed
___
*[topside/plumbing/plumbing_engine.py, line 71 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/97#-MKT8c1b20ny1gsmUN0b:-MKT8c1cCtaB3O_peirt:b-c5fhux) ([raw file](https://github.com/waterloo-rocketry/topside/blob/1fb10246386cc29d5b2529b913e5fd60d8a16115/topside/plumbing/plumbing_engine.py#L71)):*
> ```Python
>         """
> 
>         for name in self.initial_state:
> ```

This is my bad for not mentioning earlier, but we might not actually want to reset any components that have been added/removed. I think we should make this optional and controlled with a `kwarg` flag. The function definition would then become `def reset(self, reset_components=False)`, and we could wrap the component resetting portions of the function in an `if reset_components:` block. We'd definitely want to add a unit test for this flag, then :)
___
*[topside/plumbing/tests/test_plumbing_engine_editing.py, line 67 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/97#-MKT3Zkp55-VDb3fWxrS:-MKT3Zkp55-VDb3fWxrT:brbi4mh) ([raw file](https://github.com/waterloo-rocketry/topside/blob/1fb10246386cc29d5b2529b913e5fd60d8a16115/topside/plumbing/tests/test_plumbing_engine_editing.py#L67)):*
> ```Python
> 
> 
> def test_reset():
> ```

I really like the unit test coverage you've got :) this one test does cover a lot of the functionality of the `reset()` function though. It would probably be better to split it up into several additional different, small tests. Maybe one each for things like making sure a newly added component is removed, removed components are re-added, pressures are restored properly, etc. I think we definitely should keep this one around as an integration test, but in case something breaks we probably also want more granularity on what exactly went wrong. 

Something else to test (that's likely going to be a major use case of this function) is that it also works after calling `step()` and `solve()` on the plumbing engine, which are the functions that step the engine through time.
___
*[topside/plumbing/tests/test_plumbing_engine_editing.py, line 85 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/97#-MKT7jNgCPuGxnlGkF4X:-MKT7jNgCPuGxnlGkF4Y:bi2gez2) ([raw file](https://github.com/waterloo-rocketry/topside/blob/1fb10246386cc29d5b2529b913e5fd60d8a16115/topside/plumbing/tests/test_plumbing_engine_editing.py#L85)):*
> ```Python
>     assert plumb.is_valid()
>     assert plumb.time_res == int(utils.s_to_micros(0.2) / utils.DEFAULT_RESOLUTION_SCALE)
>     assert plumb.edges() == [
> ```

Instead of manually testing against these hardcoded values here, it might be easier to create another `two_valve_setup()` engine (`plumb_initial` or something) with the same arguments. It should be identical to the initial state of the first, so then you can just compare `plumb.edges() == plumb_initial.edges()`. Same for `nodes()` and basically all the other attributes you're checking here.

**Review by wendi-yu — COMMENTED** [review]
Yep looks really good to me! Just one/two more unit tests and we'll be good to go :) Once you do those, do you mind going through and marking all the comments as resolved? Makes reviewing easier, ty :0 

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/97#-:-MLQY6hT0SxyNf9qRf1u:b-q4dzar)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @jacobdeery, @TieuKhang, and @wendi-yu)

___
*[topside/plumbing/tests/test_plumbing_engine_editing.py, line 176 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/97#-MLQXK_m3G77G9EMwJg5:-MLQXK_m3G77G9EMwJg6:bwvafcf) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3ab2883f25d8e855a0c86317980eb127fc9960ea/topside/plumbing/tests/test_plumbing_engine_editing.py#L176)):*
> ```Python
> 
>     plumb.set_pressure(2, 150)
>     plumb.reset(True)
> ```

Just two more quick unit test ideas - a test that makes sure that `plumb.reset()` doesn't change components, and another one that makes sure that `plumb.reset()` still resets states/pressures/times.

**Review by TieuKhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/97)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @jacobdeery and @TieuKhang)

___
*[topside/plumbing/plumbing_engine.py, line 64 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/97#-MKSCui4DxODanmn3fiG:-MMC_dvs7mZgqcdn8Gvl:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/1fb10246386cc29d5b2529b913e5fd60d8a16115/topside/plumbing/plumbing_engine.py#L64)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

yep, agreed
</blockquote></details>

Done.

**Review by wendi-yu — APPROVED** [review]
Cool, :lgtm_strong:! Thanks for doing this :) Just before you merge, please check over `CONTRIBUTING.md` for the message format - you're generally pretty good on that front, just don't forget to add `pdl:` to the beginning of the message and to remove the autofilled merge commit message. Pull request number (the `(#97)` can also stay in :)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/97#-:-MMDDdGKEJVYkfIfjZ97:b3i0fd4)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @jacobdeery and @TieuKhang)

**Pull request merged**
