### PR TITLE
app: Move time controls to PlumbingBridge

### PR DESCRIPTION
**Pull request by jacobdeery**
Removes some weird coupling where the ProceduresBridge would reach into
the internals of the PlumbingBridge and step time on the plumbing engine
directly. We now have the PlumbingBridge explicitly handle all time
controls, which is better for modularity.

Test coverage takes a bit of a hit here since the signalling code is now in QML.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/105)

### CODE REVIEW

**Review by chrissank — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/105)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wendi-yu)

**Comment by chrissank** [comment]
*[a discussion](https://reviewable.io/reviews/waterloo-rocketry/topside/105#-MMhxQac4QJ4fOW5Vtt2:-MMhxQac4QJ4fOW5Vtt3:b6mqtfi) (no related file):*
Only comment (unrelated to this PR, but moreso about the application) : It's my understanding that `self.engine.reset()` resets the engine to it's original state (i.e. resetting the entire simulation). 

In that case, having the stop button (which is essentially a reset button) in the middle of the display seems a bit too easy to click. IMO it should be separate & have a reset confirmation on it. 

---

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/105)* status: all files reviewed, 1 unresolved discussion (waiting on @chrissank and @wendi-yu)

*[a discussion](https://reviewable.io/reviews/waterloo-rocketry/topside/105#-MMhxQac4QJ4fOW5Vtt2:-MMiBPUC2uEGM1eHR3aD:bq6rp1l) (no related file):*
<details><summary><i>Previously, chrissank (Chris Sankey) wrote…</i></summary><blockquote>

Only comment (unrelated to this PR, but moreso about the application) : It's my understanding that `self.engine.reset()` resets the engine to it's original state (i.e. resetting the entire simulation). 

In that case, having the stop button (which is essentially a reset button) in the middle of the display seems a bit too easy to click. IMO it should be separate & have a reset confirmation on it. 
</blockquote></details>

I don't think confirmation is necessary, but I could agree with moving it off to the side. I'll leave that for a future PR.

---

**Review by wendi-yu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/105)* status: all files reviewed, 1 unresolved discussion (waiting on @chrissank)

*[a discussion](https://reviewable.io/reviews/waterloo-rocketry/topside/105#-MMhxQac4QJ4fOW5Vtt2:-MMrwEj4D_dhbQynvfLc:b-l8gix2) (no related file):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

I don't think confirmation is necessary, but I could agree with moving it off to the side. I'll leave that for a future PR.
</blockquote></details>

Yeah, LGTM as well - not much to say since we're just moving functions over :0

---

**Pull request merged**
