### PR TITLE
Add support for error logging

### PR DESCRIPTION
**Pull request by wendi-yu**
Rather than halting the entire initialization process on each error, the
plumbing engine now logs any errors it encounters in an `error_list`
attribute and proceeds, loading in as much as it can. Whether or not
a given engine has errors is indicated by the `valid` attribute.

The same functionality was extended to plumbing components; however
certain plumbing engine functions still throw custom errors. These
aren't designed to be called within lengthy processes that need to
avoid interruption.

Also moved the plumbing component class into its own file to better
organize the codebase.

Also fixed possible bugs caused by the input dicts being passed by 
reference - to protect against out-of-scope changes, all dicts are deep
copied then assigned in the constructors. Unit tests were updated accordingly.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[operations_simulator/plumbing/exceptions.py, line 2 at r1](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8#-M4fsrw8E_wTsMlP4Gf1:-M4fsrw8E_wTsMlP4Gf2:bqyozgg) ([raw file](https://github.com/waterloo-rocketry/operations-simulator/blob/dbcbdc55f88c8c6e6e376fe93d6aff62075205bb/operations_simulator/plumbing/exceptions.py#L2)):*
> ```Python
> class MissingInputError(Exception):
>     pass
> ```

Nit: Please restore this newline
___
*[operations_simulator/plumbing/plumbing_component.py, line 28 at r1](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8#-M4ftIyE6xejjA2R2YFH:-M4ftIyF-eWS2ufKAY8A:b9t3p40) ([raw file](https://github.com/waterloo-rocketry/operations-simulator/blob/dbcbdc55f88c8c6e6e376fe93d6aff62075205bb/operations_simulator/plumbing/plumbing_component.py#L28)):*
> ```
>                             f"Invalid provided teq value ('{state[edge]}'), accepted keyword is: '{utils.CLOSED_KEYWORD}'", self.name, state_id, edge, og_teq)
> ```

Nit: This line is definitely too long; can you please break it up so that it's 100 characters max?
___
*[operations_simulator/plumbing/plumbing_component.py, line 46 at r1](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8#-M4ftUsnApLZOf3cWfgn:-M4ftUsnApLZOf3cWfgo:b-et2ubh) ([raw file](https://github.com/waterloo-rocketry/operations-simulator/blob/dbcbdc55f88c8c6e6e376fe93d6aff62075205bb/operations_simulator/plumbing/plumbing_component.py#L46)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         if not self.error_list:
>             self.valid = True
>         else:
>             self.valid = False
> ```
</details>


this can be `self.valid = len(self.error_list) == 0`
___
*[operations_simulator/plumbing/plumbing_engine.py, line 59 at r1](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8#-M4fuTy01ti85jUqnqoK:-M4fuTy01ti85jUqnqoL:b-532vtc) ([raw file](https://github.com/waterloo-rocketry/operations-simulator/blob/dbcbdc55f88c8c6e6e376fe93d6aff62075205bb/operations_simulator/plumbing/plumbing_engine.py#L59)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
>                 if nodes_map.get(start_node) is None:
>                     error = invalid.InvalidComponentNode(
>                         f"Component '{name}', node {start_node} not found in mapping dict.",
>                         name, start_node)
>                     self.error_list.append(error)
>                     continue
>                 if nodes_map.get(end_node) is None:
>                     error = invalid.InvalidComponentNode(
>                         f"Component '{name}', node {end_node} not found in mapping dict.",
>                         name, end_node)
>                     self.error_list.append(error)
>                     continue
> ```
</details>


Ideally we would be able to log both of these errors in a single pass. We could accomplish that if we did something like this:

```
both_nodes_valid = True

if nodes_map.get(start_node) is None:
    error = invalid.InvalidComponentNode(
        f"Component '{name}', node {start_node} not found in mapping dict.",
        name, start_node)
    self.error_list.append(error)
    both_nodes_valid = False
if nodes_map.get(end_node) is None:
    error = invalid.InvalidComponentNode(
        f"Component '{name}', node {end_node} not found in mapping dict.",
        name, end_node)
    self.error_list.append(error)
    both_nodes_valid = False

if both_nodes_valid:
    self.plumbing_graph.add_edge(nodes_map[start_node], nodes_map[end_node], edge_key)
```
___
*[operations_simulator/plumbing/plumbing_engine.py, line 126 at r1](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8#-M4fvPSD8T0dww827xi9:-M4fvPSD8T0dww827xiA:b9bz51k) ([raw file](https://github.com/waterloo-rocketry/operations-simulator/blob/dbcbdc55f88c8c6e6e376fe93d6aff62075205bb/operations_simulator/plumbing/plumbing_engine.py#L126)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
>             if component_map.get(cstart_node) is None:
>                 error = invalid.InvalidComponentNode(
>                     f"Component '{component.name}', node {cstart_node} not found in mapping dict.",
>                     component.name, cstart_node)
>                 self.error_list.append(error)
>                 continue
>             if component_map.get(cend_node) is None:
>                 error = invalid.InvalidComponentNode(
>                     f"Component '{component.name}', node {cend_node} not found in mapping dict.",
>                     component.name, cend_node)
>                 self.error_list.append(error)
>                 continue
> ```
</details>


Same comment as above
___
*[operations_simulator/plumbing/tests/test_plumbing_engine.py, line 218 at r1](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8#-M4fvk0M-P0A3RIvqFxx:-M4fvk0M-P0A3RIvqFxy:bx45pva) ([raw file](https://github.com/waterloo-rocketry/operations-simulator/blob/dbcbdc55f88c8c6e6e376fe93d6aff62075205bb/operations_simulator/plumbing/tests/test_plumbing_engine.py#L218)):*
> ```
> assert len(plumb.error_list) == total_call_num
> ```

I think an explanatory comment here as to why we expect 4 identical errors would be very helpful.

Also, no action required immediately, but another thought: it would be nice to _someday_ have the error list keep track of this and not create duplicate instances of the same error. We could do this by making the invalid reason classes hashable and putting them in a set instead of a list...but that's not a priority right now.
___
*[operations_simulator/plumbing/tests/test_plumbing_engine.py, line 315 at r1](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8#-M4fwqT18Q99zzgQq_Ht:-M4fwqT18Q99zzgQq_Hu:b-huestq) ([raw file](https://github.com/waterloo-rocketry/operations-simulator/blob/dbcbdc55f88c8c6e6e376fe93d6aff62075205bb/operations_simulator/plumbing/tests/test_plumbing_engine.py#L315)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
>     pc1 = ops.PlumbingEngine()
>     pc2 = ops.PlumbingEngine()
>     pc3 = ops.PlumbingEngine()
> 
>     key = 'f'
>     value = 1
>     pc1.mapping[key] = value
> 
>     assert pc1.mapping == {key: value}
>     assert pc2.mapping == {}
>     assert pc3.mapping == {}
> ```
</details>


Nit: you use `pc`, but these are engines, not components.

The idea behind having 3 of them was that `pc2` would get constructed _before_ modifying `pc1`, and `pc3` would get constructed _after_, just in case that made a difference; see the original test I sent for reference. If you declare all of them at the same time, you probably only need 2.

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @jacobdeery)

___
*[operations_simulator/plumbing/plumbing_component.py, line 46 at r1](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8#-M4ftUsnApLZOf3cWfgn:-M4fzqSM-1JyZQ-844WH:b-896fix) ([raw file](https://github.com/waterloo-rocketry/operations-simulator/blob/dbcbdc55f88c8c6e6e376fe93d6aff62075205bb/operations_simulator/plumbing/plumbing_component.py#L46)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>         if not self.error_list:
>             self.valid = True
>         else:
>             self.valid = False
> ```

this can be `self.valid = len(self.error_list) == 0`
</blockquote></details>

Done.
___
*[operations_simulator/plumbing/plumbing_engine.py, line 59 at r1](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8#-M4fuTy01ti85jUqnqoK:-M4g1bMW3DucVa1z7DIj:b-896fix) ([raw file](https://github.com/waterloo-rocketry/operations-simulator/blob/dbcbdc55f88c8c6e6e376fe93d6aff62075205bb/operations_simulator/plumbing/plumbing_engine.py#L59)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>                 if nodes_map.get(start_node) is None:
>                     error = invalid.InvalidComponentNode(
>                         f"Component '{name}', node {start_node} not found in mapping dict.",
>                         name, start_node)
>                     self.error_list.append(error)
>                     continue
>                 if nodes_map.get(end_node) is None:
>                     error = invalid.InvalidComponentNode(
>                         f"Component '{name}', node {end_node} not found in mapping dict.",
>                         name, end_node)
>                     self.error_list.append(error)
>                     continue
> ```

Ideally we would be able to log both of these errors in a single pass. We could accomplish that if we did something like this:

```
both_nodes_valid = True

if nodes_map.get(start_node) is None:
    error = invalid.InvalidComponentNode(
        f"Component '{name}', node {start_node} not found in mapping dict.",
        name, start_node)
    self.error_list.append(error)
    both_nodes_valid = False
if nodes_map.get(end_node) is None:
    error = invalid.InvalidComponentNode(
        f"Component '{name}', node {end_node} not found in mapping dict.",
        name, end_node)
    self.error_list.append(error)
    both_nodes_valid = False

if both_nodes_valid:
    self.plumbing_graph.add_edge(nodes_map[start_node], nodes_map[end_node], edge_key)
```
</blockquote></details>

Done.
___
*[operations_simulator/plumbing/plumbing_engine.py, line 126 at r1](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8#-M4fvPSD8T0dww827xi9:-M4g1c9lB8ArGr7G2mOl:b-896fix) ([raw file](https://github.com/waterloo-rocketry/operations-simulator/blob/dbcbdc55f88c8c6e6e376fe93d6aff62075205bb/operations_simulator/plumbing/plumbing_engine.py#L126)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>             if component_map.get(cstart_node) is None:
>                 error = invalid.InvalidComponentNode(
>                     f"Component '{component.name}', node {cstart_node} not found in mapping dict.",
>                     component.name, cstart_node)
>                 self.error_list.append(error)
>                 continue
>             if component_map.get(cend_node) is None:
>                 error = invalid.InvalidComponentNode(
>                     f"Component '{component.name}', node {cend_node} not found in mapping dict.",
>                     component.name, cend_node)
>                 self.error_list.append(error)
>                 continue
> ```

Same comment as above
</blockquote></details>

Done.
___
*[operations_simulator/plumbing/tests/test_plumbing_engine.py, line 218 at r1](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8#-M4fvk0M-P0A3RIvqFxx:-M4g1hfJCXXNMTCC9vC0:b-kq4cal) ([raw file](https://github.com/waterloo-rocketry/operations-simulator/blob/dbcbdc55f88c8c6e6e376fe93d6aff62075205bb/operations_simulator/plumbing/tests/test_plumbing_engine.py#L218)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> assert len(plumb.error_list) == total_call_num
> ```

I think an explanatory comment here as to why we expect 4 identical errors would be very helpful.

Also, no action required immediately, but another thought: it would be nice to _someday_ have the error list keep track of this and not create duplicate instances of the same error. We could do this by making the invalid reason classes hashable and putting them in a set instead of a list...but that's not a priority right now.
</blockquote></details>

Right now having lots of duplicate instances of the same error almost acts like a clue that the node name in the original mapping dict provided was wrong, rather than a node name fed in through an initial states dict or something - but I agree that we could implement that more cleanly than throwing four of the same error at them.

The `dataclass` decorator we're using for our `InvalidReasons` actually does have an custom `.__eq__` operator that checks equality of the values of each field as if it were a tuple, so we might not even need to hash our errors ourselves. Seems doable :)

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8)* status: 0 of 6 files reviewed, all discussions resolved

___
*[operations_simulator/plumbing/tests/test_plumbing_engine.py, line 218 at r1](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8#-M4fvk0M-P0A3RIvqFxx:-M4g9Lua5zSQB6Hy1e6M:bkarhgz) ([raw file](https://github.com/waterloo-rocketry/operations-simulator/blob/dbcbdc55f88c8c6e6e376fe93d6aff62075205bb/operations_simulator/plumbing/tests/test_plumbing_engine.py#L218)):*
<details><summary><i>Previously, wendi-yu wrote…</i></summary><blockquote>

Right now having lots of duplicate instances of the same error almost acts like a clue that the node name in the original mapping dict provided was wrong, rather than a node name fed in through an initial states dict or something - but I agree that we could implement that more cleanly than throwing four of the same error at them.

The `dataclass` decorator we're using for our `InvalidReasons` actually does have an custom `.__eq__` operator that checks equality of the values of each field as if it were a tuple, so we might not even need to hash our errors ourselves. Seems doable :)
</blockquote></details>

Ok, sounds good. I would still like to see a comment left here so that people reading the code in the future don't need to figure out "wait, why are there 4 errors"?

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8)* status: 0 of 6 files reviewed, all discussions resolved

___
*[operations_simulator/plumbing/tests/test_plumbing_engine.py, line 218 at r1](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8#-M4fvk0M-P0A3RIvqFxx:-M4gAa5SBQqfxdeBBVBk:b6drgc8) ([raw file](https://github.com/waterloo-rocketry/operations-simulator/blob/dbcbdc55f88c8c6e6e376fe93d6aff62075205bb/operations_simulator/plumbing/tests/test_plumbing_engine.py#L218)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Ok, sounds good. I would still like to see a comment left here so that people reading the code in the future don't need to figure out "wait, why are there 4 errors"?
</blockquote></details>

Yep, the comment is there - it's above where `total_call_num` is assigned instead of at the assert (sorry should've mentioned)

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8)* status: 0 of 6 files reviewed, all discussions resolved

___
*[operations_simulator/plumbing/tests/test_plumbing_engine.py, line 218 at r1](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8#-M4fvk0M-P0A3RIvqFxx:-M4gAzwv3AQMH1SFNA2a:bmubaz) ([raw file](https://github.com/waterloo-rocketry/operations-simulator/blob/dbcbdc55f88c8c6e6e376fe93d6aff62075205bb/operations_simulator/plumbing/tests/test_plumbing_engine.py#L218)):*
<details><summary><i>Previously, wendi-yu wrote…</i></summary><blockquote>

Yep, the comment is there - it's above where `total_call_num` is assigned instead of at the assert (sorry should've mentioned)
</blockquote></details>

Gotcha, my mistake.

**Review by jacobdeery — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/operations-simulator/8#-:-M4gB25u0G2COlyzAxvE:b-uwkowd)* status: 0 of 6 files reviewed, all discussions resolved

**Review by jacobdeery — APPROVED** [review]

**Pull request merged**
