### PR TITLE
proc: Add ProcedureSuite class

### PR DESCRIPTION
**Pull request by jacobdeery**
New class that provides a convenient way for grouping a set of related
procedures and associated metadata. Currently the only metadata is the
entry point into the suite (the first procedure that should be
executed), but we also add checks for duplicate procedure IDs, fixing a
potential bug.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/56)

### CODE REVIEW

**Comment by jacobdeery** [comment]
Stacking on top of #55 until that one gets merged.

**Review by wendi-yu — COMMENTED** [review]
LGTM overall! I agree that it does feel a lot cleaner to have the metadata  pulled out of the engine and into a self-contained suite. 

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/56#-:-MGp_eUxCEXCv_aQNAN1:byq8h52)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @jacobdeery and @wendi-yu)

___
*[topside/procedures/procedures_engine.py, line 35 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/56#-MGpXWAwBvLqYdJ64IPn:-MGpXWAwBvLqYdJ64IPo:b-1bc5qn) ([raw file](https://github.com/waterloo-rocketry/topside/blob/041d6f4b4fba58e5697e6165c28527d0d0e2e496/topside/procedures/procedures_engine.py#L35)):*
> ```Python
>         if suite is not None:
>             self.current_procedure_id = self._suite.starting_procedure_id
>             self.current_step = self._suite[self.current_procedure_id].step_list[0]
> ```

Will this combust if we give the procedures engine an empty ProcedureSuite? The `starting_procedure_id` defaults to 'main', right, so trying to access `suite['main']` when the suite's dict of procedures is empty throws a key error? If not allowing and empty suite is intentional maybe it's worth catching and erroring explicitly?

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/56)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @wendi-yu)

___
*[topside/procedures/procedures_engine.py, line 35 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/56#-MGpXWAwBvLqYdJ64IPn:-MGqCG3X1ZtqmEU0gF0g:b1rwutg) ([raw file](https://github.com/waterloo-rocketry/topside/blob/041d6f4b4fba58e5697e6165c28527d0d0e2e496/topside/procedures/procedures_engine.py#L35)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Will this combust if we give the procedures engine an empty ProcedureSuite? The `starting_procedure_id` defaults to 'main', right, so trying to access `suite['main']` when the suite's dict of procedures is empty throws a key error? If not allowing and empty suite is intentional maybe it's worth catching and erroring explicitly?
</blockquote></details>

Good catch. I've added a check to `ProcedureSuite` that ensures the suite contains a procedure corresponding to the starting procedure ID, which makes it an error to construct an empty suite.

**Review by wendi-yu — APPROVED** [review]
Cool cool, LGTM! 

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/56#-:-MH88ToZ9ZAXUIaVT0b8:b-fjgbni)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @wendi-yu)

**Pull request merged**
