### PR TITLE
proc: Change WaitUntil condition to WaitFor

### PR DESCRIPTION
**Pull request by jacobdeery**
Instead of checking if a certain amount of time has elapsed since the
start of the procedure, WaitFor now checks if a certain amount of time
has elapsed since the most recent step was executed, which more
accurately represents the conditions we include in our procedures.

This is technically on the roadmap for W21, but I wanted to just get it out of the way so we can focus on the bigger things.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/114)

### CODE REVIEW

**Review by wendi-yu — COMMENTED** [review]
Looks good :0

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/114#-:-MQtpSrlBCluE0I5mirZ:b3kmvpk)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @brianbutchart, @chrissank, @jacobdeery, @James020118, and @wendi-yu)

___
*[topside/procedures/conditions.py, line 8 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/114#-MQtlGQsD1_zRh1vdrV4:-MQtlGQsD1_zRh1vdrV5:b-yqw0i1) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fc683b6315dc8bfe98d2b2b56fc59c1fcf6a8c6d/topside/procedures/conditions.py#L8)):*
> ```Python
>     Base class for all procedure conditions.
> 
>     This class should never be used directly.
> ```

Could be interesting to use an [abstract base class](https://docs.python.org/3/library/abc.html) here, it raises all those "not allowed to use" errors for you. Not a huge difference but could be fun for first years to see.
___
*[topside/procedures/conditions.py, line 213 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/114#-MQtmX1U14lUrLfuiGQy:-MQtmX1U14lUrLfuiGQz:bxkccj8) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fc683b6315dc8bfe98d2b2b56fc59c1fcf6a8c6d/topside/procedures/conditions.py#L213)):*
> ```Python
>         wait_t: int
>             The wait time interval for this condition. This condition
>             will become satisfied `wait_t` after it first becomes active
> ```

Mention that it's in  microseconds?
___
*[topside/procedures/conditions.py, line 238 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/114#-MQtn6-S1fcxc_fk3tX-:-MQtn6-S1fcxc_fk3tX0:b-m89oz8) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fc683b6315dc8bfe98d2b2b56fc59c1fcf6a8c6d/topside/procedures/conditions.py#L238)):*
> ```Python
>             engine.
>         """
>         self.current_t = state['time']
> ```

Do we want to have a nicer error if `time` isn't provided? I guess it throws a `KeyError` either way so nbd
___
*[topside/procedures/procedures_engine.py, line 108 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/114#-MQtolQ-8TSzuypfPbKU:-MQtolQ08dVfrDU8GqpF:bfgzn2v) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fc683b6315dc8bfe98d2b2b56fc59c1fcf6a8c6d/topside/procedures/procedures_engine.py#L108)):*
> ```Python
>         self.execute(self.current_step.action)
>         self.step_position = StepPosition.After
>         self.reinitialize_conditions()
> ```

This could be a lot of querying on every `execute_current`. I don't think any of our plumbing is big enough for this to be a problem now, I'm fine with it, but I wonder if we can make it smarter later on and only update stuff that's changed.

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/114)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @brianbutchart, @chrissank, @James020118, and @wendi-yu)

___
*[topside/procedures/conditions.py, line 8 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/114#-MQtlGQsD1_zRh1vdrV4:-MQu1mKM9QAl9vO8WY_g:b-fznogt) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fc683b6315dc8bfe98d2b2b56fc59c1fcf6a8c6d/topside/procedures/conditions.py#L8)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Could be interesting to use an [abstract base class](https://docs.python.org/3/library/abc.html) here, it raises all those "not allowed to use" errors for you. Not a huge difference but could be fun for first years to see.
</blockquote></details>

Good idea, done.
___
*[topside/procedures/conditions.py, line 213 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/114#-MQtmX1U14lUrLfuiGQy:-MQu3jEX0yUSl-rQmnXr:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fc683b6315dc8bfe98d2b2b56fc59c1fcf6a8c6d/topside/procedures/conditions.py#L213)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Mention that it's in  microseconds?
</blockquote></details>

Done.
___
*[topside/procedures/conditions.py, line 238 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/114#-MQtn6-S1fcxc_fk3tX-:-MQu3k4x-LQJF0N03CY1:bqeu4uh) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fc683b6315dc8bfe98d2b2b56fc59c1fcf6a8c6d/topside/procedures/conditions.py#L238)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Do we want to have a nicer error if `time` isn't provided? I guess it throws a `KeyError` either way so nbd
</blockquote></details>

I think the `KeyError` is pretty clear
___
*[topside/procedures/procedures_engine.py, line 108 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/114#-MQtolQ-8TSzuypfPbKU:-MQu4-SfC-WmAriTG0cl:bgn6f9q) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fc683b6315dc8bfe98d2b2b56fc59c1fcf6a8c6d/topside/procedures/procedures_engine.py#L108)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

This could be a lot of querying on every `execute_current`. I don't think any of our plumbing is big enough for this to be a problem now, I'm fine with it, but I wonder if we can make it smarter later on and only update stuff that's changed.
</blockquote></details>

What do you see being the computational bottleneck here? `reinitialize_conditions` only queries the state once and then passes it to each condition on the current step, which will only be 1 or 2 in the vast majority of cases.

**Review by wendi-yu — APPROVED** [review]
LGTM :^)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/114#-:-MRghwULEyM-8Rwb6ldK:b-sn004i)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @brianbutchart, @chrissank, and @James020118)

___
*[topside/procedures/conditions.py, line 238 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/114#-MQtn6-S1fcxc_fk3tX-:-MRghNOn1wMrOC1NjRlG:b-m9rcvw) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fc683b6315dc8bfe98d2b2b56fc59c1fcf6a8c6d/topside/procedures/conditions.py#L238)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

I think the `KeyError` is pretty clear
</blockquote></details>

Yeah, that's fair. sgtm
___
*[topside/procedures/procedures_engine.py, line 108 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/114#-MQtolQ-8TSzuypfPbKU:-MRghYQxEm5nwT4AIMY4:big9op4) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fc683b6315dc8bfe98d2b2b56fc59c1fcf6a8c6d/topside/procedures/procedures_engine.py#L108)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

What do you see being the computational bottleneck here? `reinitialize_conditions` only queries the state once and then passes it to each condition on the current step, which will only be 1 or 2 in the vast majority of cases.
</blockquote></details>

Oh I think I meant more the call to `current_pressures()` every time - idk how it's implemented under the hood in networkx, maybe it's not very computationally expensive. I agree that it's probably fine though.

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/114)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @brianbutchart, @chrissank, and @James020118)

___
*[topside/procedures/procedures_engine.py, line 108 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/114#-MQtolQ-8TSzuypfPbKU:-MRlAwQ41D_8DrcKNcUy:bollvpz) ([raw file](https://github.com/waterloo-rocketry/topside/blob/fc683b6315dc8bfe98d2b2b56fc59c1fcf6a8c6d/topside/procedures/procedures_engine.py#L108)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Oh I think I meant more the call to `current_pressures()` every time - idk how it's implemented under the hood in networkx, maybe it's not very computationally expensive. I agree that it's probably fine though.
</blockquote></details>

I did a quick profiling run and this is roughly what `current_pressures` looks like:

```
mean: 5.85957699999999981344 us
min: 5.65710000000000068354 us
max: 6.04218000000000010630 us
```

I would consider that relatively speedy.

**Pull request merged**
