### PR TITLE
Update package.py to allow for imports to be read from the imports folder, rather than it being a hardcoded dictionary

### LINKED ISSUE #45: Allow user-specified imports
Right now, our list of acceptable imports is hard coded in as a "standard library" of sorts. Importable PDL files live in the `topside/pdl/imports` folder, and the software keeps its record of what imports are allowed in a hard coded dict . This isn't a very flexible implementation and doesn't allow users to load in files that they'd like to import later on, which is functionality that we should support.

A basic version of this shouldn't be difficult to implement (at the package level anyways, actually adding the files is a different matter and might require some restructuring as to where things are stored). An initial idea could be to store a JSON object of `{import name: import file path}` in a file somewhere, and read it out as part of instantiation for `Package` (there's room for more sophisticated hashing and caching or whatever to improve efficiency here). We then update the contents of the file every time the list of imports is changed. The actual machinery for adding new imports doesn't necessarily have to be there yet, but it would be good to have import handling that's conducive to adding that feature when the time comes.

The code relevant to this issue lives in `topside/pdl/package.py` right now. In the same vein, it would be nice to add unused import detection as well (since these are both issues impacting the same code). Definitely more a QoL than a hard usability feature (so not super high priority), but again it would be nice to have.

### PR DESCRIPTION
**Pull request by KavinSatheeskumar**
Change added to package.py to allow users to create imports simply by adding them to the imports folder

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/72)

### CODE REVIEW

**Review by wendi-yu — CHANGES_REQUESTED** [review]
Looks good overall! Looks like the code should work, just few small things to address. This is harder to test since the imports folder isn't exactly hermetic, but maybe pop in a quick check that `len(IMPORTS) != 0` in the test files (definitely feel free to ask if you'd like more guidance on how to use the unit tests). It'll be pretty obvious from the rest of the unit tests if the imports are completely broken, but it'll be nice to have a specific test that points to import reading too.

There's room for a bit of optimization here, if you'd be at all interested in taking that on - definitely no pressure to do so though, and not necessary to merge this PR. Not to beat the JSON horse dead, but instead of reading in the contents of every single import file on every package initialization, we could keep our `IMPORTS` dict in a JSON file. We then only read that one file and compare hashes of our record of paths and the actual paths we've read to see if we actually need to construct a new `IMPORTS` dict. If not, we use what we already have.

Again this definitely doesn't need to be done in this PR. I'll open another issue with the optimization - if you want to work on it let me or Jacob know and we'll assign you.

Looks mostly good overall though! Thanks for doing this :)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-:-MIR7Uz67IUF0DMgAAtD:b-o2wbjf)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jacobdeery, @KavinSatheeskumar, and @wendi-yu)

___
*[topside/pdl/package.py, line 38 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MIR6iftBUVdMFOIaVdX:-MIR6ifu6ejbamrkh3ju:b-2rt0nr) ([raw file](https://github.com/waterloo-rocketry/topside/blob/58474f7d77face627b44497b1c360e2743c9e854/topside/pdl/package.py#L38)):*
> ```Python
>         imports = os.listdir(utils.imports_path)
> 
>         for x in imports:
> ```

You might want to name `x` more descriptively, just as a matter of good practice. Something like `import_file` could work, to distinguish from `name` :)
___
*[topside/pdl/package.py, line 41 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MIRDaw396Zh6luhjLbM:-MIRDaw396Zh6luhjLbN:b-f1uc5n) ([raw file](https://github.com/waterloo-rocketry/topside/blob/58474f7d77face627b44497b1c360e2743c9e854/topside/pdl/package.py#L41)):*
> ```Python
> 
>             path = os.path.join(utils.imports_path, x)
>             name = yaml.safe_load(open(path,"r"))["name"]
> ```

The style we try to stick with is single quotes (`'` rather than `"`) for shorter strings, so like for `"r"` or `"name"` here.

**Review by jacobdeery — COMMENTED** [review]
After reading through this PR I have a few thoughts about the way the current import mechanism works, which I've left as comments below. @wendi-yu please do weigh in!

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-:-MIRY16L9QfUfdztMBKC:bjhm7k)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @jacobdeery and @KavinSatheeskumar)

___
*[topside/pdl/package.py, line 14 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MIRKS1P-7OH-JAA8cPj:-MIRKS1P-7OH-JAA8cPk:b4rd4yk) ([raw file](https://github.com/waterloo-rocketry/topside/blob/58474f7d77face627b44497b1c360e2743c9e854/topside/pdl/package.py#L14)):*
> ```
> # TODO(wendi): make imports more dynamic, so that users can add importable files
> # outside a predefined library. Likely involves a function that traipses through the
> # imports folder for new files and stores them in this dict whenever new Packages are instantiated.
> ```
This PR will address this TODO, correct? If so, you can remove the comment.
___
*[topside/pdl/package.py, line 41 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MIRKf7gAOHU_JZxx_e3:-MIRKf7gAOHU_JZxx_e4:b-5u8uiw) ([raw file](https://github.com/waterloo-rocketry/topside/blob/58474f7d77face627b44497b1c360e2743c9e854/topside/pdl/package.py#L41)):*
> ```
> path,"r"
> ```
Nit: There should be a space after the comma here. In future you can automatically fix these by running the `tools/format.sh` script
___
*[topside/pdl/package.py, line 41 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MIRR9g95C1LUX6umt4R:-MIRR9g95C1LUX6umt4S:b-elcxqh) ([raw file](https://github.com/waterloo-rocketry/topside/blob/58474f7d77face627b44497b1c360e2743c9e854/topside/pdl/package.py#L41)):*
> ```
> name = yaml.safe_load(open(path,"r"))["name"]
> ```
I have a few reservations about this approach.

First, as-is, if I add a single non-PDL file to the import directory, all of the unit tests will fail. This means that instantiating a `Package` implicitly requires the import directory to contain only valid PDL files - because everything there is going to be parsed, whether you ask for it or not. I think that we either need to eliminate this requirement or make it explicit. Either way, we should wrap this line in a `try`-`except` block. If we want to eliminate the requirement, our `except` does nothing and just moves to the next file. If we want to make it explicit, we should hard fail.

I'm also a bit concerned with the requirement that we parse every potential file to build the import dict, but I guess this is a necessary side effect of handling imports by PDL name rather than filename. Something to think about.
___
*[topside/pdl/package.py, line 42 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MIRX8KqDT8oBS8H4FKC:-MIRX8KqDT8oBS8H4FKD:bg8qhrf) ([raw file](https://github.com/waterloo-rocketry/topside/blob/58474f7d77face627b44497b1c360e2743c9e854/topside/pdl/package.py#L42)):*
> ```
> IMPORTS[name] = path
> ```
Hmm, if I have two files (`stdlib1.pdl` and `stdlib2.pdl`) that both declare the `stdlib` namespace, we'll overwrite the second one here. I'm not sure that this is desired - maybe it should be an error (or at least a warning) if we encounter a duplicate namespace?

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/72)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @jacobdeery and @KavinSatheeskumar)

___
*[topside/pdl/package.py, line 41 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MIRR9g95C1LUX6umt4R:-MIZzcV_1RTe25jFUmJW:brudgll) ([raw file](https://github.com/waterloo-rocketry/topside/blob/58474f7d77face627b44497b1c360e2743c9e854/topside/pdl/package.py#L41)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> name = yaml.safe_load(open(path,"r"))["name"]
> ```
I have a few reservations about this approach.

First, as-is, if I add a single non-PDL file to the import directory, all of the unit tests will fail. This means that instantiating a `Package` implicitly requires the import directory to contain only valid PDL files - because everything there is going to be parsed, whether you ask for it or not. I think that we either need to eliminate this requirement or make it explicit. Either way, we should wrap this line in a `try`-`except` block. If we want to eliminate the requirement, our `except` does nothing and just moves to the next file. If we want to make it explicit, we should hard fail.

I'm also a bit concerned with the requirement that we parse every potential file to build the import dict, but I guess this is a necessary side effect of handling imports by PDL name rather than filename. Something to think about.
</blockquote></details>

Yeah, I definitely agree on the `try-except` wrap, though I'm unsure if any other files will commonly be in the `imports` folder. We could also tell it to only try to parse files with the `pdl` extension. I think the impact of parsing every potential file will definitely be somewhat mitigated if we do caching, it's a lot of work on every instantiation right now but I'm not expecting the imports folder to change very often in the future. We can also only parse the files that have changed. 

I agree that it's a little clunkier to handle by name, but it does feel nicely parallel to how files are usually handled. The main benefit I can think of of using a `name` field instead of the file name is that separate files can contribute to the same namespace right now.
___
*[topside/pdl/package.py, line 42 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MIRX8KqDT8oBS8H4FKC:-MI_1jxXCZxRClgtbQZv:b-bt1cxz) ([raw file](https://github.com/waterloo-rocketry/topside/blob/58474f7d77face627b44497b1c360e2743c9e854/topside/pdl/package.py#L42)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> IMPORTS[name] = path
> ```
Hmm, if I have two files (`stdlib1.pdl` and `stdlib2.pdl`) that both declare the `stdlib` namespace, we'll overwrite the second one here. I'm not sure that this is desired - maybe it should be an error (or at least a warning) if we encounter a duplicate namespace?
</blockquote></details>

I think the default right now is that we act as if two files that declare the same namespace build on top of each other (so components in one file, actual graph in another for example). If we don't want to allow this for imports, we could first check that `name not in IMPORTS` and throw a warning if it is, otherwise we could also store a list of relevant files per namespace and load all of those files.

Good catch though, definitely something to consider :)

**Comment by KavinSatheeskumar** [comment]
Hey, I made those changed and it said that the tests failed. I think the issue is on line 46 where I raise the NameError, but I am not sure. I'll try replacing it with a warning and seeing what happens

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/72)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[topside/pdl/package.py, line 14 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MIRKS1P-7OH-JAA8cPj:-MI_9ETk9r1DR8g3EEye:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/58474f7d77face627b44497b1c360e2743c9e854/topside/pdl/package.py#L14)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> # TODO(wendi): make imports more dynamic, so that users can add importable files
> # outside a predefined library. Likely involves a function that traipses through the
> # imports folder for new files and stores them in this dict whenever new Packages are instantiated.
> ```
This PR will address this TODO, correct? If so, you can remove the comment.
</blockquote></details>

Done.
___
*[topside/pdl/package.py, line 38 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MIR6iftBUVdMFOIaVdX:-MI_9FrF1ItNLvSccWtd:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/58474f7d77face627b44497b1c360e2743c9e854/topside/pdl/package.py#L38)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

You might want to name `x` more descriptively, just as a matter of good practice. Something like `import_file` could work, to distinguish from `name` :)
</blockquote></details>

Done.
___
*[topside/pdl/package.py, line 41 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MIRDaw396Zh6luhjLbM:-MI_9GjRErUTwvvTglVe:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/58474f7d77face627b44497b1c360e2743c9e854/topside/pdl/package.py#L41)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

The style we try to stick with is single quotes (`'` rather than `"`) for shorter strings, so like for `"r"` or `"name"` here.
</blockquote></details>

Done.
___
*[topside/pdl/package.py, line 41 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MIRR9g95C1LUX6umt4R:-MI_9JnT89m66fv1xPT0:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/58474f7d77face627b44497b1c360e2743c9e854/topside/pdl/package.py#L41)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Yeah, I definitely agree on the `try-except` wrap, though I'm unsure if any other files will commonly be in the `imports` folder. We could also tell it to only try to parse files with the `pdl` extension. I think the impact of parsing every potential file will definitely be somewhat mitigated if we do caching, it's a lot of work on every instantiation right now but I'm not expecting the imports folder to change very often in the future. We can also only parse the files that have changed. 

I agree that it's a little clunkier to handle by name, but it does feel nicely parallel to how files are usually handled. The main benefit I can think of of using a `name` field instead of the file name is that separate files can contribute to the same namespace right now.
</blockquote></details>

Done.
___
*[topside/pdl/package.py, line 42 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MIRX8KqDT8oBS8H4FKC:-MI_9LBw5CVD3u8mtFIs:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/58474f7d77face627b44497b1c360e2743c9e854/topside/pdl/package.py#L42)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

I think the default right now is that we act as if two files that declare the same namespace build on top of each other (so components in one file, actual graph in another for example). If we don't want to allow this for imports, we could first check that `name not in IMPORTS` and throw a warning if it is, otherwise we could also store a list of relevant files per namespace and load all of those files.

Good catch though, definitely something to consider :)
</blockquote></details>

Done.

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/72)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @jacobdeery, @KavinSatheeskumar, and @wendi-yu)

___
*[topside/pdl/package.py, line 14 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MIRKS1P-7OH-JAA8cPj:-MI_HgcREMrMqTi1HvvN:b-2r7swd) ([raw file](https://github.com/waterloo-rocketry/topside/blob/58474f7d77face627b44497b1c360e2743c9e854/topside/pdl/package.py#L14)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You'll want to remove the whole comment, not just the first line
___
*[topside/pdl/package.py, line 49 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MI_Htu10w5LiwYBkrnI:-MI_Htu10w5LiwYBkrnJ:bi0bh26) ([raw file](https://github.com/waterloo-rocketry/topside/blob/994e6d9da577f3295c68a5c411c4bed0679cc4d9/topside/pdl/package.py#L49)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> if (name in IMPORTS):
>                 warnings.warn("There are multiple files in the imports folder with the name " + name)
>                 #Maybe we could make this into one of the custom exceptions that the Exceptions file is for
>             else:
>                 IMPORTS[name] = path
> ```
</details>

This `if`-`else` needs to be inside the `try`; otherwise, if we hit the `except`, we'll still try to execute this code and `name` won't be defined, so we'll error.

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/72)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @KavinSatheeskumar and @wendi-yu)

___
*[topside/pdl/package.py, line 16 at r4](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MIfLEVCCPou4sGATprt:-MIfLEVD8RYwWYm-VvgX:bfsgiw5) ([raw file](https://github.com/waterloo-rocketry/topside/blob/4cef32bf065c0ba5bc3e769a459406774355af0f/topside/pdl/package.py#L16)):*
> ```
> ;
> ```
Nit: should be `:`

**Review by wendi-yu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/72)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @KavinSatheeskumar)

___
*[topside/pdl/package.py, line 13 at r5](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MIfPmu533FBcHoZmeQh:-MIfPmu533FBcHoZmeQi:b-rhg59i) ([raw file](https://github.com/waterloo-rocketry/topside/blob/ab0cfc513f96baf39412edc438f75c54108a5199/topside/pdl/package.py#L13)):*
> ```Python
> # on requested import.
> 
> # TODO: make importing more efficent by having a YMAL file storing the self.importable_files dict and updating it
> ```

YMAL -> YAML

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/72)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[topside/pdl/package.py, line 49 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MI_Htu10w5LiwYBkrnI:-MJ-Di9mBg594MaZKU5j:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/994e6d9da577f3295c68a5c411c4bed0679cc4d9/topside/pdl/package.py#L49)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> if (name in IMPORTS):
>                 warnings.warn("There are multiple files in the imports folder with the name " + name)
>                 #Maybe we could make this into one of the custom exceptions that the Exceptions file is for
>             else:
>                 IMPORTS[name] = path
> ```
This `if`-`else` needs to be inside the `try`; otherwise, if we hit the `except`, we'll still try to execute this code and `name` won't be defined, so we'll error.
</blockquote></details>

Done.
___
*[topside/pdl/package.py, line 13 at r5](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MIfPmu533FBcHoZmeQh:-MJ-DgHaDP3h5vej4nLt:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/ab0cfc513f96baf39412edc438f75c54108a5199/topside/pdl/package.py#L13)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

YMAL -> YAML
</blockquote></details>

Done.

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/72)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[topside/pdl/package.py, line 49 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MI_Htu10w5LiwYBkrnI:-MJ-GBYn2E0rHHHbS9Hx:bnelezu) ([raw file](https://github.com/waterloo-rocketry/topside/blob/994e6d9da577f3295c68a5c411c4bed0679cc4d9/topside/pdl/package.py#L49)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is done since we removed that try catch.

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/72)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jacobdeery, @KavinSatheeskumar, and @wendi-yu)

___
*[topside/pdl/package.py, line 49 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MI_Htu10w5LiwYBkrnI:-MJ-KLzG8AI6hirg9tAq:b-t1tcjc) ([raw file](https://github.com/waterloo-rocketry/topside/blob/994e6d9da577f3295c68a5c411c4bed0679cc4d9/topside/pdl/package.py#L49)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

This is done since we removed that try catch.
</blockquote></details>

The try-catch is still here (the one with `name = yaml.safe_load`)

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/72)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[topside/pdl/package.py, line 49 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-MI_Htu10w5LiwYBkrnI:-MJ-M5H6EkBdSVwG9wlW:b-29xqfv) ([raw file](https://github.com/waterloo-rocketry/topside/blob/994e6d9da577f3295c68a5c411c4bed0679cc4d9/topside/pdl/package.py#L49)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

The try-catch is still here (the one with `name = yaml.safe_load`)
</blockquote></details>

Ah, my bad, I'll fix that now

**Review by wendi-yu — APPROVED** [review]
Looks good! Thanks for putting this together :)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/72#-:-MJ-RynN0QvZGhT1EfpR:b-i5dfmx)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @wendi-yu)

**Pull request merged**
