### PR TITLE
pdl: Add basic PDL parsing structure

### PR DESCRIPTION
**Pull request by wendi-yu**
This introduces the PDL parser module. It includes its two basic underlying classes, the `File` and the `Package`. The gist of the two is that `Files` represent individual units of PDL, entered by a user, while a `Package` is a collection of `Files` that can be assembled into a coherent plumbing engine. This PR doesn't include the actual "convert to plumbing engine input" parts of the parser, it's mostly just validating and properly assembling data.

This isn't a complete implementation yet - there are definitely parts that could be fleshed out, maybe even as a good first issue :) they're marked with `TODOs`. I think the major functionality we want is there though. I also started the structure of a standard PDL library, which can also be improved and expanded upon later (tbh the existing `stdlib` typedef is almost complete nonsense I just needed something for my tests).

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/44)

### CODE REVIEW

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/44)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @dwkletke and @jacobdeery)

___
*[topside/pdl/exceptions.py, line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6x-cE3y_2aEGsIiF4:-MB6x-cE3y_2aEGsIiF5:brkbyr) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/exceptions.py#L1)):*
> ```Python
> class BadInputError(Exception):
> ```

I was considering having an `exceptions.py` file in the topside directory rather than different exceptions for every module, especially since we have a `BadInputError` already in the plumbing engine, thoughts?

**Review by jacobdeery — COMMENTED** [review]
> Reviewed 11 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/44)* status: 6 of 14 files reviewed, 17 unresolved discussions (waiting on @dwkletke, @jacobdeery, and @wendi-yu)

___
*[topside/pdl/example.yaml, line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6qewi9ULAJm3JxEl_:-MB6qewj75VM3ZYbUH1h:b-q6l6oq) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/example.yaml#L1)):*
> ```
> potato
> ```
Please name this something else
___
*[topside/pdl/example.yaml, line 4 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6qh0H8bB1i8KRBHSc:-MB6qh0H8bB1i8KRBHSd:b-v68az) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/example.yaml#L4)):*
> ```YAML
> 
> import: [stdlib]
>   
> ```

Extraneous whitespace throughout this file
___
*[topside/pdl/example.yaml, line 28 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6qmFqDXxqQOd-DlaK:-MB6qmFqDXxqQOd-DlaL:b5tn1ct) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/example.yaml#L28)):*
> ```YAML
>       closed:
>         edge1: closed
> ```

Standardize on one newline vs two?
___
*[topside/pdl/exceptions.py, line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6x-cE3y_2aEGsIiF4:-MB7-FDe2hWoEZDlQGo5:b-vmeu78) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/exceptions.py#L1)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

I was considering having an `exceptions.py` file in the topside directory rather than different exceptions for every module, especially since we have a `BadInputError` already in the plumbing engine, thought?
</blockquote></details>

Honestly, I'm not sure if we actually need these user-defined exceptions - we might be fine just using `RuntimeError` or `ValueError` in most cases.
___
*[topside/pdl/file.py, line 6 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6so-i5Fh3w94wW61d:-MB6so-i5Fh3w94wW61e:bwxh1cv) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/file.py#L6)):*
> ```
> fields, entry
> ```
Nit: I think switching the order of these parameters might be a bit more intuitive
___
*[topside/pdl/file.py, line 7 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6r2k2ERIi45wf-IDp:-MB6r2k2ERIi45wf-IDq:b-talt05) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/file.py#L7)):*
> ```Python
> 
> def check_fields(fields, entry):
>     """ Check that all provided fields are in entry, where entry is a PDL object."""
> ```

Extra space at start of docstring (throughout the file)
___
*[topside/pdl/file.py, line 14 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6sEM37sN8cVK6Wleo:-MB6sEM37sN8cVK6Wlep:b-d77mji) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/file.py#L14)):*
> ```
>         if entry[field] is None:
>             raise exceptions.BadInputError(f"field {field} required not to be empty")
> ```

The exception message communicates a different condition (field must be not empty) than what the if statement is checking (field is `None`). What is the actual requirement?
___
*[topside/pdl/file.py, line 20 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6rDAM0cG-9VEuJVe8:-MB6rDAM0cG-9VEuJVe9:bby5t2c) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/file.py#L20)):*
> ```
> "f"
> ```
Nit: single quotes?
___
*[topside/pdl/file.py, line 60 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6rQRs2fnFOG-DOb3T:-MB6rQRs2fnFOG-DOb3U:b7lucmi) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/file.py#L60)):*
> ```
> "f":
> ```
Single quotes throughout the file
___
*[topside/pdl/file.py, line 65 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6rSKP1Pd4_H7BKiDf:-MB6rSKP1Pd4_H7BKiDg:b-56k0dt) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/file.py#L65)):*
> ```
> "invalid input type {input_type}"
> ```
Right now I think all of our exceptions use double quotes; we should fix that
___
*[topside/pdl/file.py, line 130 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6sf8XERexsfYJBHP9:-MB6sf8XERexsfYJBHPA:b-kijbjk) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/file.py#L130)):*
> ```
> typedef {def_type} not found; hoisting not allowed
> ```
"hoisting not allowed" will not be an intuitive error message for most people reading it (I didn't know what hoisting was until reading your comment).
___
*[topside/pdl/file.py, line 135 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6x_xv9reSELbW9msF:-MB6x_xwCAcRJ5Jf9QQL:b-bzlngn) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3111dc6a43807c95b4469542cba2a43c36d88ad9/topside/pdl/file.py#L135)):*
> ```
>         if len(params) != len(entry):
>             raise exceptions.BadInputError(f"not all params ({params}) present in component "
>                                            "declaration")
> ```
Do we want to eventually support default values for params?
___
*[topside/pdl/package.py, line 19 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6uUQIALi67oowFSpL:-MB6uTXP2M7frFTITmgd:b-2sxjig) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/package.py#L19)):*
> ```
>  
> ```
Extra space at start of docstring
___
*[topside/pdl/package.py, line 92 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6tl9rDMkL2W7pxkS6:-MB6tl9s7yAK61H1PVjU:b6898rz) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/package.py#L92)):*
> ```Python
>         name = component["type"]
>         if "." in name:
>             # NOTE: we might eventually want to consider how well this will play with nested imports
> ```

Have we tried nested imports? Does it work? If not, maybe we should explicitly fail for multiple `.` in the name here with a `NotImplementedError` and make this `NOTE` into a `TODO`.
___
*[topside/pdl/imports/stdlib.yaml, line 2 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6ujtq1hGm__XPo8kk:-MB6ujtq1hGm__XPo8kl:b-sde940) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/imports/stdlib.yaml#L2)):*
> ```
> import: []
> ```
Should we add a `TODO` to support leaving this line out if the import list is empty?
___
*[topside/pdl/tests/test_file.py, line 41 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6wPgI-1Myury32YqM:-MB6wPgI-1Myury32YqN:bg2wpm0) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/tests/test_file.py#L41)):*
> ```Python
> 
> 
> def test_invalid_component():
> ```

Consider splitting this into three separate tests rather than testing three separate things in one test. Generally good TDD practice for a single test to test one thing.
___
*[topside/pdl/tests/test_file.py, line 165 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6w61cBw4f3XIaSl--:-MB6w61cBw4f3XIaSl-0:b7th6hl) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/tests/test_file.py#L165)):*
<details><summary><i alt="summary">Quoted 31 lines of code…</i></summary>

> ```
>         """
> name: potato
> import: [stdlib, other_lib]
> body:
> - graph:
>     name: main
>     nodes:
>       A:
>         fixed_pressure: 500
>         components:
>           - [fill_valve, 0]
>       B:
>         components:
>           - [fill_valve, 1]
>           - [vent_valve, 0]
>           - [check_valve, 0]
>       C:
>         initial_pressure: 10
>         components:
>           - [check_valve, 1]
>           - [three_way_valve, 0]
>       D:
>         components:
>           - [three_way_valve, 1]
>           - [vent_plug, 0]
>       atm:
>         components:
>           - [three_way_valve, 2]
>           - [vent_plug, 1]
>           - [vent_valve, 1]
> """
> ```
</details>


It's pretty hard to tell what's actually missing just from a quick readthrough here. Are all of these nodes strictly necessary? if so, a comment explaining what to look at would definitely be helpful

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/44)* status: 6 of 14 files reviewed, 14 unresolved discussions (waiting on @dwkletke and @jacobdeery)

___
*[topside/pdl/example.yaml, line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6qewi9ULAJm3JxEl_:-MB786Wo-H3QOnt0zOXf:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/example.yaml#L1)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> potato
> ```
Please name this something else
</blockquote></details>

Done.
___
*[topside/pdl/example.yaml, line 4 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6qh0H8bB1i8KRBHSc:-MB78xW6CZJ6qeEzk0fc:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/example.yaml#L4)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Extraneous whitespace throughout this file
</blockquote></details>

Done.
___
*[topside/pdl/example.yaml, line 28 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6qmFqDXxqQOd-DlaK:-MB78xx07ir1PjORHnD8:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/example.yaml#L28)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Standardize on one newline vs two?
</blockquote></details>

Done.
___
*[topside/pdl/exceptions.py, line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6x-cE3y_2aEGsIiF4:-MB78zpG1FxoPy5DwmrV:b65xirm) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/exceptions.py#L1)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Honestly, I'm not sure if we actually need these user-defined exceptions - we might be fine just using `RuntimeError` or `ValueError` in most cases.
</blockquote></details>

Yeah, they're a lot more descriptive in the plumbing engine than here. I'm ok with leaving it as is for now since having the slightly more descriptive error isn't causing any harm, but we can revisit later on?
___
*[topside/pdl/file.py, line 14 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6sEM37sN8cVK6Wleo:-MB79ZhO2RHmjWkL74Pm:b-tnasb9) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/file.py#L14)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>         if entry[field] is None:
>             raise exceptions.BadInputError(f"field {field} required not to be empty")
> ```

The exception message communicates a different condition (field must be not empty) than what the if statement is checking (field is `None`). What is the actual requirement?
</blockquote></details>

If the field is left empty in the PDL, the object produced by the yaml load will have  a `None` value. So if you had something like this:
```
namespace: example
imports: [stdlib]
body:
```
you'd end up with a dict like this:
```
{ 
'namespace': 'example',
'imports': ['stdlib'],
'body': None
}
```
So it is checking for an empty entry still - I added an explanatory comment.
___
*[topside/pdl/file.py, line 60 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6rQRs2fnFOG-DOb3T:-MB7AjNM92Ottb3tBp3d:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/file.py#L60)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> "f":
> ```
Single quotes throughout the file
</blockquote></details>

Done.
___
*[topside/pdl/file.py, line 65 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6rSKP1Pd4_H7BKiDf:-MB7Amdo8xfkxQhkLEC-:bbwu89t) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/file.py#L65)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> "invalid input type {input_type}"
> ```
Right now I think all of our exceptions use double quotes; we should fix that
</blockquote></details>

Is there anything wrong with having double quotes? I think for longer messages double quotes make sense (single ones always felt more char-like to me), but is there some stylistic preference I'm unaware of?
___
*[topside/pdl/file.py, line 130 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6sf8XERexsfYJBHP9:-MB7BQrV06GAkUKu7Biz:b-jq38c1) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/file.py#L130)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> typedef {def_type} not found; hoisting not allowed
> ```
"hoisting not allowed" will not be an intuitive error message for most people reading it (I didn't know what hoisting was until reading your comment).
</blockquote></details>

#justjavascriptthings
changed the error message lol
___
*[topside/pdl/file.py, line 135 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6x_xv9reSELbW9msF:-MB7COrIE0Er3lh05z1y:b-n5imhb) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3111dc6a43807c95b4469542cba2a43c36d88ad9/topside/pdl/file.py#L135)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>         if len(params) != len(entry):
>             raise exceptions.BadInputError(f"not all params ({params}) present in component "
>                                            "declaration")
> ```
Do we want to eventually support default values for params?
</blockquote></details>

Sure, I'll add it as a TODO
___
*[topside/pdl/package.py, line 19 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6uUQIALi67oowFSpL:-MB7CwbME9WVozmTSh4s:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/package.py#L19)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>  
> ```
Extra space at start of docstring
</blockquote></details>

Done.
___
*[topside/pdl/package.py, line 92 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6tl9rDMkL2W7pxkS6:-MB7HP1P16EeaR15dXJ3:bf42zxg) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/package.py#L92)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Have we tried nested imports? Does it work? If not, maybe we should explicitly fail for multiple `.` in the name here with a `NotImplementedError` and make this `NOTE` into a `TODO`.
</blockquote></details>

Eh, I think the problem is that I'm honestly not sure what a nested import would entail right now. I kind of doubt nested imports will be in the scope of things we're realistically going to do anytime soon, but yeah I'll add the explicit fail.
___
*[topside/pdl/imports/stdlib.yaml, line 2 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6ujtq1hGm__XPo8kk:-MB7EfzE1OuxKEe2jAdH:begt069) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/imports/stdlib.yaml#L2)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> import: []
> ```
Should we add a `TODO` to support leaving this line out if the import list is empty?
</blockquote></details>

I just made the change since it was pretty simple (and added a unit test for it)
___
*[topside/pdl/tests/test_file.py, line 41 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6wPgI-1Myury32YqM:-MB7FC2F1DvMtQcRnEha:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/tests/test_file.py#L41)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Consider splitting this into three separate tests rather than testing three separate things in one test. Generally good TDD practice for a single test to test one thing.
</blockquote></details>

Done.
___
*[topside/pdl/tests/test_file.py, line 165 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6w61cBw4f3XIaSl--:-MB7Fggr1n_uMLaayU7B:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/tests/test_file.py#L165)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>         """
> name: potato
> import: [stdlib, other_lib]
> body:
> - graph:
>     name: main
>     nodes:
>       A:
>         fixed_pressure: 500
>         components:
>           - [fill_valve, 0]
>       B:
>         components:
>           - [fill_valve, 1]
>           - [vent_valve, 0]
>           - [check_valve, 0]
>       C:
>         initial_pressure: 10
>         components:
>           - [check_valve, 1]
>           - [three_way_valve, 0]
>       D:
>         components:
>           - [three_way_valve, 1]
>           - [vent_plug, 0]
>       atm:
>         components:
>           - [three_way_valve, 2]
>           - [vent_plug, 1]
>           - [vent_valve, 1]
> """
> ```

It's pretty hard to tell what's actually missing just from a quick readthrough here. Are all of these nodes strictly necessary? if so, a comment explaining what to look at would definitely be helpful
</blockquote></details>

Done.

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/44)* status: 5 of 14 files reviewed, 6 unresolved discussions (waiting on @dwkletke, @jacobdeery, and @wendi-yu)

___
*[topside/pdl/exceptions.py, line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6x-cE3y_2aEGsIiF4:-MB7Nceh0xjgDzqvmHMT:bto2vo1) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/exceptions.py#L1)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Yeah, they're a lot more descriptive in the plumbing engine than here. I'm ok with leaving it as is for now since having the slightly more descriptive error isn't causing any harm, but we can revisit later on?
</blockquote></details>

Sounds good, maybe leave a TODO?
___
*[topside/pdl/file.py, line 60 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6rQRs2fnFOG-DOb3T:-MB7OESs3LqukjmuRW8F:b-xbcw96) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/file.py#L60)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done only here; there are a lot of these elsewhere still
___
*[topside/pdl/file.py, line 65 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6rSKP1Pd4_H7BKiDf:-MB7NyBz5m2MCQOtnZHX:b-o0iun3) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/file.py#L65)):*
PEP 8:

> In Python, single-quoted strings and double-quoted strings are the same. This PEP does not make a recommendation for this. Pick a rule and stick to it. When a string contains single or double quote characters, however, use the other one to avoid backslashes in the string. It improves readability.
>
> For triple-quoted strings, always use double quote characters to be consistent with the docstring convention in PEP 257.

I'm used to single quotes (not sure why), but I don't mind switching everything over to double quotes if you prefer that. We should just be consistent 
___
*[topside/pdl/file.py, line 137 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB7OreQ7qJASR-papv6:-MB7OreQ7qJASR-papv7:b-vz2qty) ([raw file](https://github.com/waterloo-rocketry/topside/blob/2b59c523a3e1ceae3933c58e009d5aec9fe51340/topside/pdl/file.py#L137)):*
> ```
> default params
> ```
"default values for params" or "default arguments". A parameter is a variable; the actual value is an argument.
___
*[topside/pdl/package.py, line 92 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6tl9rDMkL2W7pxkS6:-MB7P9bs24zWN1-GprMV:bv3go41) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/package.py#L92)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Eh, I think the problem is that I'm honestly not sure what a nested import would entail right now. I kind of doubt nested imports will be in the scope of things we're realistically going to do anytime soon, but yeah I'll add the explicit fail.
</blockquote></details>

Ah, fair enough. I think I was thinking about transitive includes in the C[++] sense (`localizer.h` includes `pose.h` which includes `geometry.h`), but I see now that that's not how our system is set up.
___
*[topside/pdl/package.py, line 51 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB7Oj_B5Vxo0NpejStD:-MB7Oj_B5Vxo0NpejStE:buj79cb) ([raw file](https://github.com/waterloo-rocketry/topside/blob/2b59c523a3e1ceae3933c58e009d5aec9fe51340/topside/pdl/package.py#L51)):*
> ```
> for imp in self.imports:
> ```
use `set(self.imports)` here for easy duplicate removal
___
*[topside/pdl/tests/test_file.py, line 183 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB7Pw7p5uGrCsPlEHEi:-MB7Pw7p5uGrCsPlEHEj:bakggms) ([raw file](https://github.com/waterloo-rocketry/topside/blob/2b59c523a3e1ceae3933c58e009d5aec9fe51340/topside/pdl/tests/test_file.py#L183)):*
> ```Python
> 
>     # A is missing its components
>     incomplete_nodes =\
> ```

I'd split this one off into a separate test as well

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/44)* status: 5 of 14 files reviewed, 5 unresolved discussions (waiting on @dwkletke and @jacobdeery)

___
*[topside/pdl/file.py, line 60 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6rQRs2fnFOG-DOb3T:-MB7V8iC1-HPTKGgq6KT:b-wq5x9m) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/file.py#L60)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Done only here; there are a lot of these elsewhere still
</blockquote></details>

Sorry, are there? I got them all in `file.py` and in the tests for files and packages I'm fairly sure? Did you mean the dict keys too?
___
*[topside/pdl/file.py, line 65 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6rSKP1Pd4_H7BKiDf:-MB7W8C79HJ83G9YYEcP:b-sw8k92) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/file.py#L65)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

PEP 8:

> In Python, single-quoted strings and double-quoted strings are the same. This PEP does not make a recommendation for this. Pick a rule and stick to it. When a string contains single or double quote characters, however, use the other one to avoid backslashes in the string. It improves readability.
>
> For triple-quoted strings, always use double quote characters to be consistent with the docstring convention in PEP 257.

I'm used to single quotes (not sure why), but I don't mind switching everything over to double quotes if you prefer that. We should just be consistent 
</blockquote></details>

Sure, I think all the error messages are consistently double quoted within the scope of this PR. I think the majority are double quoted now, we can change one way or the other in a different refactoring PR or something?
___
*[topside/pdl/file.py, line 137 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB7OreQ7qJASR-papv6:-MB7WfhB4Y1vo_kPyfYL:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/2b59c523a3e1ceae3933c58e009d5aec9fe51340/topside/pdl/file.py#L137)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> default params
> ```
"default values for params" or "default arguments". A parameter is a variable; the actual value is an argument.
</blockquote></details>

Done.
___
*[topside/pdl/package.py, line 51 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB7Oj_B5Vxo0NpejStD:-MB7WmEG41uMri6fPZhl:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/2b59c523a3e1ceae3933c58e009d5aec9fe51340/topside/pdl/package.py#L51)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> for imp in self.imports:
> ```
use `set(self.imports)` here for easy duplicate removal
</blockquote></details>

Done.
___
*[topside/pdl/tests/test_file.py, line 183 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB7Pw7p5uGrCsPlEHEi:-MB7Wwtx7pmWHILZ4o7S:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/2b59c523a3e1ceae3933c58e009d5aec9fe51340/topside/pdl/tests/test_file.py#L183)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

I'd split this one off into a separate test as well
</blockquote></details>

Done.

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/44)* status: 5 of 14 files reviewed, 1 unresolved discussion (waiting on @dwkletke, @jacobdeery, and @wendi-yu)

___
*[topside/pdl/file.py, line 60 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6rQRs2fnFOG-DOb3T:-MB7Xt_P4myxOvFljwir:b-f8gt55) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/file.py#L60)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Sorry, are there? I got them all in `file.py` and in the tests for files and packages I'm fairly sure? Did you mean the dict keys too?
</blockquote></details>

Yep, every string should be quoted the same way. We can keep error messages as the exception for now to maintain _some_ level of consistency, but everything else should be single quotes since that's the convention we have at the moment throughout the codebase.
___
*[topside/pdl/file.py, line 65 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6rSKP1Pd4_H7BKiDf:-MB7YAM47wQeMxn5qSO_:bjq15zj) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/file.py#L65)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Sure, I think all the error messages are consistently double quoted within the scope of this PR. I think the majority are double quoted now, we can change one way or the other in a different refactoring PR or something?
</blockquote></details>

Yep, I'm fine with that.

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/44)* status: 5 of 14 files reviewed, all discussions resolved (waiting on @dwkletke and @jacobdeery)

___
*[topside/pdl/file.py, line 60 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-MB6rQRs2fnFOG-DOb3T:-MB7_tWa6Bg5S0HwDgDT:b-lw1izi) ([raw file](https://github.com/waterloo-rocketry/topside/blob/3dd548199f81ecfa9813c27d92a290e798dc0d58/topside/pdl/file.py#L60)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Yep, every string should be quoted the same way. We can keep error messages as the exception for now to maintain _some_ level of consistency, but everything else should be single quotes since that's the convention we have at the moment throughout the codebase.
</blockquote></details>

_ah_ my bad I thought you meant the single characters only, done now

**Review by jacobdeery — APPROVED** [review]
Let's do it!

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/44#-:-MB7dtn_AhkluspEN-dt:b-mlyogx)* status: 5 of 14 files reviewed, all discussions resolved (waiting on @dwkletke and @jacobdeery)

**Pull request merged**
