### PR TITLE
Optimize the optimizer

### PR DESCRIPTION
**Pull request by jacobdeery**
Vectorize the graph layout optimization routine. Remove nested for loops and redundant calculations between cost terms and across iterations.

Speeds up `layout_plumbing_engine` by ~4.8x.

Current master:
```
mean time: 4.4294932126998905 seconds
max time: 4.631882905960083 seconds
min time: 4.306760311126709 seconds
```

This PR:
```
mean time: 0.9118092298507691 seconds
max time: 0.9235303401947021 seconds
min time: 0.8985953330993652 seconds
```

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/17)

### CODE REVIEW

**Review by wendi-yu — COMMENTED** [review]
Exploding build aside, :lgtm: overall :) If we do end up commenting the function parameters in layout, I'll do it for the plumbing engine as well.

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/17#-:-M7WHcK9DE_dmKlBFB_4:b-skm9xm)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @jacobdeery and @wendi-yu)

___
*[topside/visualization/optimization/cost_terms.py, line 5 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/17#-M7ViZDb9Z5RXKjixYz8:-M7ViZDcD3jZwkLTjbRx:boa43zc) ([raw file](https://github.com/waterloo-rocketry/topside/blob/6963cf1cb98f9ee5760a0e5016a494d8fcda2f25/topside/visualization/optimization/cost_terms.py#L5)):*
> ```Python
> 
> class NeighboringDistance():
>     def __init__(self, g, node_indices, node_component_neighbors, settings, internal):
> ```

Do you think it would be useful to have comments documenting what the parameters of meaty functions like this should be? Both layout and the plumbing engine have functions that take in reasonably complex data structures now. Especially since it's Python where types aren't declared, I think it would be nice to have a reference at hand of what data structure with what values each of the variables are. Plus in-code documentation is probably going to stay more up-to-date than any external stuff we make :0

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/17)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @wendi-yu)

___
*[topside/visualization/optimization/cost_terms.py, line 5 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/17#-M7ViZDb9Z5RXKjixYz8:-M7f-oGtD7i84DbO3S7G:bjh5ezw) ([raw file](https://github.com/waterloo-rocketry/topside/blob/6963cf1cb98f9ee5760a0e5016a494d8fcda2f25/topside/visualization/optimization/cost_terms.py#L5)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Do you think it would be useful to have comments documenting what the parameters of meaty functions like this should be? Both layout and the plumbing engine have functions that take in reasonably complex data structures now. Especially since it's Python where types aren't declared, I think it would be nice to have a reference at hand of what data structure with what values each of the variables are. Plus in-code documentation is probably going to stay more up-to-date than any external stuff we make :0 
</blockquote></details>

Done for cost terms and `layout_plumbing_engine`. I'll comment `terminal_graph` as well, probably tomorrow. Let me know if you want me to comment any of the other small functions - I think most of them should be pretty intuitive.

**Review by wendi-yu — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/17#-:-M7fHfnV1SGeBwakBD0E:bnfp4nl)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @wendi-yu)

**Comment by wendi-yu** [comment]
Yep everything makes sense, I'll do the plumbing engine comments in the same style then. Preemptive LGTM if it's just commenting `terminal_graph` from here :0

**Review by wendi-yu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/17)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[topside/visualization/layout.py, line 15 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/17#-M7jfnfd3SIXgPMLTO0M:-M7jfnfd3SIXgPMLTO0N:b-t9d203) ([raw file](https://github.com/waterloo-rocketry/topside/blob/a64176089825b86a0a7bbe37408198139093b249/topside/visualization/layout.py#L15)):*
> ```Python
>                 i. Create a node C_n in T, where the node name of C_n is
>                    <name of C>.<name of n>.
>                 ii. Create an edge in T from C_n to C.mapping[n].
> ```

It makes sense to me having worked on the plumbing engine, but I think it would be helpful to specify what exactly `mapping[n]` is. 
The components themselves _technically_ don't have mappings, but `C.mapping` is probably clearer than the strictly correct way :0

**Review by wendi-yu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/17#-:-M7k5-tF3YeCHHgCoY2q:bnfp4nl)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

**Pull request merged**
