### PR TITLE
app: Unit test VisualizationArea functions 

### PR DESCRIPTION
**Pull request by jacobdeery**
Add unit tests for the `paint` method in VisualizationArea (and for
`scale_and_center`, a new method I pulled out of `paint`). Still doesn't
test anything related to QML - this is internal logic only.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/93)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/93)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @Code-Titan and @wendi-yu)

___
*[.gitignore, line 27 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/93#-MK1GvA10cHQtY0o3tPR:-MK1GvA10cHQtY0o3tPS:b-e94zct) ([raw file](https://github.com/waterloo-rocketry/topside/blob/204c1ce24cb3c11ac5ecab93a78a0a92bbce150c/.gitignore#L27)):*
> ```ignore
> .coverage
> coverage.xml
> htmlcov
> ```

if you run `pytest --cov --cov-report=html` you get a folder (named `htmlcov` by default) that has a lot of the same info that codecov posts on GitHub. Useful for looking at coverage locally in more detail.

**Review by wendi-yu — COMMENTED** [review]
cool beans looks good :)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/93#-:-MK6qDOG7zp_0OQrMUXd:bs6x0k7)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Code-Titan, @jacobdeery, and @wendi-yu)

___
*[application/visualization_area.py, line 113 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/93#-MK6kZDr0TWwJXDDy7iR:-MK6kZDs5LERi4EEvmdX:b5kad5o) ([raw file](https://github.com/waterloo-rocketry/topside/blob/204c1ce24cb3c11ac5ecab93a78a0a92bbce150c/application/visualization_area.py#L113)):*
> ```Python
>         self.component_font = QFont('Arial', 8, QFont.Bold)
> 
>         if self.DEBUG_MODE:  # pragma: no cover
> ```

Looks like we can specify lines to always exclude from code coverage (so `if self.DEBUG_MODE`, assuming we never want coverage on debug lines) from the `.coveragerc` file, instead of manually popping in a `# pragma: no cover` every time - details are [here](https://coverage.readthedocs.io/en/coverage-4.3.3/excluding.html#advanced-exclusion).
___
*[application/tests/test_visualization_area.py, line 23 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/93#-MK6mJM16PiyfY2Q9twF:-MK6mJM28LGOuIEraHi5:b-w9dgs9) ([raw file](https://github.com/waterloo-rocketry/topside/blob/204c1ce24cb3c11ac5ecab93a78a0a92bbce150c/application/tests/test_visualization_area.py#L23)):*
> ```Python
> 
>     def __eq__(self, other):
>         return (self.p1 == other.p1 and self.p2 == other.p2) or \
> ```

Should we have a type check for the equality comparison?

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/93)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @Code-Titan)

___
*[application/visualization_area.py, line 113 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/93#-MK6kZDr0TWwJXDDy7iR:-MK7w0RWCtJRAjruxOqa:b-vyayl8) ([raw file](https://github.com/waterloo-rocketry/topside/blob/204c1ce24cb3c11ac5ecab93a78a0a92bbce150c/application/visualization_area.py#L113)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Looks like we can specify lines to always exclude from code coverage (so `if self.DEBUG_MODE`, assuming we never want coverage on debug lines) from the `.coveragerc` file, instead of manually popping in a `# pragma: no cover` every time - details are [here](https://coverage.readthedocs.io/en/coverage-4.3.3/excluding.html#advanced-exclusion).
</blockquote></details>

That's much cleaner - done.
___
*[application/tests/test_visualization_area.py, line 23 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/93#-MK6mJM16PiyfY2Q9twF:-MK7uC1v0mVO6o6NaEtg:b-slcius) ([raw file](https://github.com/waterloo-rocketry/topside/blob/204c1ce24cb3c11ac5ecab93a78a0a92bbce150c/application/tests/test_visualization_area.py#L23)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Should we have a type check for the equality comparison?
</blockquote></details>

Probably not necessary since we'll only ever be comparing MockLines to MockLines, but added one anyways just to guard against dumb mistakes.

**Review by wendi-yu — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/93#-:-MKDqtyR6k4aXdD1YAae:bg7igkv)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @Code-Titan and @wendi-yu)

**Pull request merged**
