### PR TITLE
Add in-app PDL editor

### PR DESCRIPTION
**Pull request by jacobdeery**
Very simple and barebones editor for now. Press Ctrl+Shift+E to open it, or use the Tools menu.

You should see a window like this one:
image

PDL code can be entered in the top text box. Pressing the `Compile` button should try to compile the PDL code, printing an error if it is invalid for some reason. If it is valid, the resulting plumbing engine should be visualized in the left pane.

image

The code can be changed and recompiled at any time.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/128)

### CODE REVIEW

**Review by wendi-yu — COMMENTED** [review]
Yeah looks good to me, I tested it locally and it all seems to behave as expected. It'll definitely be useful to be able to load/save files later on. 

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/128#-:-MazZTe99alm-wwz3rit:b-hdqbo2)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @dldyment, @jacobdeery, and @James020118)

___
*[application/application.py, line 98 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/128#-MazRX_NCqFlD69LHBoW:-MazRX_OD984STgCKJ5F:baoixm3) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9da7d53a0e0b657ba8345b4f0e3499eda1f1a5ef/application/application.py#L98)):*
> ```Python
>         tools_menu = QMenu('&Tools')
> 
>         pdl_editor_action = QAction('Launch PDL Editor', window)
> ```

This might be a nitpick but it seems more standard to just have the name of the tool ("PDL Editor") rather than the action of "Launch PDL editor", but up to you :0
___
*[application/pdl_editor.py, line 53 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/128#-MazZqZy8gsnHLdUjr4U:-MazZqZy8gsnHLdUjr4V:brsrafo) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9da7d53a0e0b657ba8345b4f0e3499eda1f1a5ef/application/pdl_editor.py#L53)):*
> ```Python
>             plumb = parser.make_engine()
>         except Exception as e:
>             self.messages.appendPlainText('Error encountered in PDL compilation:')
> ```

What do you think about adding error messages in red, just for visibility? Otherwise it doesn't seem like there's a huge visible response when you compile an invalid engine rn
___
*[application/plumbing_vis/visualization_area.py, line 86 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/128#-MazY4c0A5IQKOEHRiDe:-MazY4c0A5IQKOEHRiDf:b-t3ypz4) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9da7d53a0e0b657ba8345b4f0e3499eda1f1a5ef/application/plumbing_vis/visualization_area.py#L86)):*
> ```Python
> 
> 
> class PlumbingVisualizer(QObject):
> ```

ooh smort makes sense, I like this better than the multiple inheritance option too

**Review by dldyment — DISMISSED** [review]
Looks good! I like Wendi's idea about putting error messages in red.

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/128)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @James020118 and @wendi-yu)

___
*[application/application.py, line 98 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/128#-MazRX_NCqFlD69LHBoW:-McPyb6C6HOPgfUINV_5:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9da7d53a0e0b657ba8345b4f0e3499eda1f1a5ef/application/application.py#L98)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

This might be a nitpick but it seems more standard to just have the name of the tool ("PDL Editor") rather than the action of "Launch PDL editor", but up to you :0
</blockquote></details>

Done.
___
*[application/pdl_editor.py, line 53 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/128#-MazZqZy8gsnHLdUjr4U:-McPyde823tYNxO6m272:b72tle6) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9da7d53a0e0b657ba8345b4f0e3499eda1f1a5ef/application/pdl_editor.py#L53)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

What do you think about adding error messages in red, just for visibility? Otherwise it doesn't seem like there's a huge visible response when you compile an invalid engine rn
</blockquote></details>

Will leave for a Good First Issue

**Review by wendi-yu — APPROVED** [review]
Looks good!

**Pull request merged**
