### PR TITLE
plumbing: Introduce node class as attribute

### PR DESCRIPTION
**Pull request by wendi-yu**
This introduces `Node` classes, which we use to model the various types of nodes in a plumbing graph - eg atmosphere, tanks with capacity, etc. The main purpose is to encapsulate the relevant attributes of a node in one place and to allow different pressure calculations to be done, depending on node type.

I was originally going to implement this through making the networkx nodes themselves objects, but that made identifying nodes fairly difficult. I was also worried about pass by reference errors and equality comparisons. Instead, the object is stored under a `body` attribute for each networkx node, and the nodes are still identified by their original names. 

A few parts could still use a little polishing, but I wanted to get the basic implementation in to unblock other people. Namely,
* determining what node type to return could still use a little work. It'll require PDL changes into the future, but since Kavin is working on the first non-trivial node type I figured it would be best to figure it out with him when he wants to start working on it.
* the `fixed_pressures` dict on the plumbing engine might not be as necessary anymore since nodes keep track of their own fixedness. That's just a code cleanup though, and can proceed in parallel with other work.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/123)

### CODE REVIEW

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/123)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @jacobdeery and @KavinSatheeskumar)

___
*[topside/plumbing/node.py, line 29 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/123#-MRm2wj53EeSB2HUILDp:-MRm2wj63rBydmVs6Obz:bfj1jsq) ([raw file](https://github.com/waterloo-rocketry/topside/blob/21ec9166c1e8cbaafca42c61b2d10b377367639a/topside/plumbing/node.py#L29)):*
> ```Python
>     @abstractmethod
>     def get_pressure(self):
>         """Return pressure."""
> ```

The docstrings here aren't particularly useful but they shut codecov up, since it complains about `pass` not being tested even thought the abstract stuff can't be instantiated

**Review by KavinSatheeskumar — APPROVED** [review]
> Reviewed 5 of 8 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/123)* status: all files reviewed, 1 unresolved discussion (waiting on @jacobdeery)

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/123)* status: all files reviewed, 2 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[topside/plumbing/plumbing_engine.py, line 313 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/123#-MRp0ZGD896zqUQV5y-Q:-MRp070d3obscyrj-SqE:b2e7gr7) ([raw file](https://github.com/waterloo-rocketry/topside/blob/21ec9166c1e8cbaafca42c61b2d10b377367639a/topside/plumbing/plumbing_engine.py#L313)):*
> ```Python
>                     start_map_node, end_map_node, component.name + '.' + edge_key)
> 
>                 for node in [start_map_node, end_map_node]:
> ```

Just a dumb question, why are we for looping over two variables?

I also found the "continue" statement odd, can't we just use a "not" in the if condition and have that code inside the if statement

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/123)* status: all files reviewed, 2 unresolved discussions (waiting on @jacobdeery and @KavinSatheeskumar)

___
*[topside/plumbing/plumbing_engine.py, line 313 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/123#-MRp0ZGD896zqUQV5y-Q:-MRphADgBcMoLb9wKGhH:bm5d0t5) ([raw file](https://github.com/waterloo-rocketry/topside/blob/21ec9166c1e8cbaafca42c61b2d10b377367639a/topside/plumbing/plumbing_engine.py#L313)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Just a dumb question, why are we for looping over two variables?

I also found the "continue" statement odd, can't we just use a "not" in the if condition and have that code inside the if statement
</blockquote></details>

Oh yeah, the for loop isn’t super necessary - it’s basically just because we’re doing the same thing to both nodes. I guess it’s technically one line less lol :^)

As for the if thing, there’s a design tactic you can take where you stick any error/exception paths in conditionals, so that the nominal path can be seen just by reading straight down an indent level. It’s also less indented code lol, but you’re right in that they’d be equivalent I think.

**Review by KavinSatheeskumar — DISMISSED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/123)* status: all files reviewed, 1 unresolved discussion (waiting on @jacobdeery)

**Review by jacobdeery — COMMENTED** [review]
I think this is mostly fine overall, just some small comments.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/123#-:-MRrB9eP3Fh-c-o5VoGc:baf1hvg)* status: all files reviewed, 7 unresolved discussions (waiting on @wendi-yu)

___
*[topside/plumbing/node.py, line 2 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/123#-MRp77QhBuqulYeoKRJx:-MRp77QhBuqulYeoKRJy:b5y6ls6) ([raw file](https://github.com/waterloo-rocketry/topside/blob/21ec9166c1e8cbaafca42c61b2d10b377367639a/topside/plumbing/node.py#L2)):*
> ```Python
> from abc import ABC, abstractmethod
> import networkx as nx
> ```

newline before `nx`
___
*[topside/plumbing/node.py, line 8 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/123#-MRqJgpZ3dfTK9SiHPvm:-MRqJgpZ3dfTK9SiHPvn:b-8c6g7r) ([raw file](https://github.com/waterloo-rocketry/topside/blob/21ec9166c1e8cbaafca42c61b2d10b377367639a/topside/plumbing/node.py#L8)):*
> ```Python
> 
> def instantiate_node(type_id=None):
>     """Return the proper child node class depending on provided type_id."""
> ```

What are the expectations on `type_id`?
___
*[topside/plumbing/tests/test_node.py, line 10 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/123#-MRp2BYhDL0OqdPRfq7j:-MRp2BYhDL0OqdPRfq7k:b-dpsk2w) ([raw file](https://github.com/waterloo-rocketry/topside/blob/21ec9166c1e8cbaafca42c61b2d10b377367639a/topside/plumbing/tests/test_node.py#L10)):*
> ```
>     atm_node = top.AtmNode()
>     assert type(expected_atm_node) == type(atm_node)
> ```
you can just do `assert type(expected_atm_node) == top.AtmNode`
___
*[topside/plumbing/tests/test_node.py, line 15 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/123#-MRp2G0i5qPcTS6wOTZ6:-MRp2G0i5qPcTS6wOTZ7:b-5k1cz6) ([raw file](https://github.com/waterloo-rocketry/topside/blob/21ec9166c1e8cbaafca42c61b2d10b377367639a/topside/plumbing/tests/test_node.py#L15)):*
> ```
>     generic_node = top.GenericNode()
>     assert type(expected_generic_node) == type(generic_node)
> ```
same
___
*[topside/plumbing/tests/test_plumbing_engine_creation.py, line 39 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/123#-MRlw4JB6WorSmt9TPBK:-MRlw4JB6WorSmt9TPBL:b-hfpv1m) ([raw file](https://github.com/waterloo-rocketry/topside/blob/af40a6e350c50ac3ae441ce10d54c75f98250c0a/topside/plumbing/tests/test_plumbing_engine_creation.py#L39)):*
> ```Python
> 
> 
> test_open_closed_valves()
> ```

remove?
___
*[topside/plumbing/tests/test_plumbing_engine_editing.py, line 574 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/123#-MRp6jybCy_cI7nyqebJ:-MRp6jybCy_cI7nyqebK:bgemchp) ([raw file](https://github.com/waterloo-rocketry/topside/blob/21ec9166c1e8cbaafca42c61b2d10b377367639a/topside/plumbing/tests/test_plumbing_engine_editing.py#L574)):*
> ```
>     for node in plumb.nodes():
>         print(node[1]['body'])
> ```
remove?

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/123)* status: 3 of 7 files reviewed, 7 unresolved discussions (waiting on @jacobdeery and @KavinSatheeskumar)

___
*[topside/plumbing/node.py, line 2 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/123#-MRp77QhBuqulYeoKRJx:-MRwDnyIEHbskyGZcxq1:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/21ec9166c1e8cbaafca42c61b2d10b377367639a/topside/plumbing/node.py#L2)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

newline before `nx`
</blockquote></details>

Done.
___
*[topside/plumbing/node.py, line 8 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/123#-MRqJgpZ3dfTK9SiHPvm:-MRwEPZN8OhUamKHmRzX:b8nvmbi) ([raw file](https://github.com/waterloo-rocketry/topside/blob/21ec9166c1e8cbaafca42c61b2d10b377367639a/topside/plumbing/node.py#L8)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

What are the expectations on `type_id`?
</blockquote></details>

Added more details into the docstring
___
*[topside/plumbing/tests/test_node.py, line 10 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/123#-MRp2BYhDL0OqdPRfq7j:-MRwEvRw5A01hhFugkwc:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/21ec9166c1e8cbaafca42c61b2d10b377367639a/topside/plumbing/tests/test_node.py#L10)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>     atm_node = top.AtmNode()
>     assert type(expected_atm_node) == type(atm_node)
> ```
you can just do `assert type(expected_atm_node) == top.AtmNode`
</blockquote></details>

Done.
___
*[topside/plumbing/tests/test_node.py, line 15 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/123#-MRp2G0i5qPcTS6wOTZ6:-MRwEx5-7wLVtVFZqM9_:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/21ec9166c1e8cbaafca42c61b2d10b377367639a/topside/plumbing/tests/test_node.py#L15)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>     generic_node = top.GenericNode()
>     assert type(expected_generic_node) == type(generic_node)
> ```
same
</blockquote></details>

Done.
___
*[topside/plumbing/tests/test_plumbing_engine_creation.py, line 39 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/123#-MRlw4JB6WorSmt9TPBK:-MRwF11m3vbOgnWcukvJ:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/af40a6e350c50ac3ae441ce10d54c75f98250c0a/topside/plumbing/tests/test_plumbing_engine_creation.py#L39)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

remove?
</blockquote></details>

Done.
___
*[topside/plumbing/tests/test_plumbing_engine_editing.py, line 574 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/123#-MRp6jybCy_cI7nyqebJ:-MRwFKGG7ZFNOTaTM4LO:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/21ec9166c1e8cbaafca42c61b2d10b377367639a/topside/plumbing/tests/test_plumbing_engine_editing.py#L574)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>     for node in plumb.nodes():
>         print(node[1]['body'])
> ```
remove?
</blockquote></details>

Done.

**Review by jacobdeery — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/123)* status: 3 of 7 files reviewed, all discussions resolved (waiting on @KavinSatheeskumar)

**Pull request merged**
