### PR TITLE
Add the ability to jump to a specific procedure step

### PR DESCRIPTION
**Pull request by James020118**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/124)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
Cool, I tried this out and it seems to work pretty well! I've left a few comments regarding the implementation, but I would also like to see unit tests added for the new function. Try to add tests for the nominal case and for edge cases as well (jump to the current step, jump to a step in the past, jump to a step that doesn't exist, etc.)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/124#-:-MU1ECPh85izJNMaCvO0:bw0obdk)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @James020118 and @wendi-yu)

___
*[application/procedures_bridge.py, line 111 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/124#-MU15zP92BoACDGagnqa:-MU15zP92BoACDGagnqb:b-r23lkg) ([raw file](https://github.com/waterloo-rocketry/topside/blob/7b2fbf336c98c4659b44084aa797a035fd41604f/application/procedures_bridge.py#L111)):*
> ```Python
>     @Slot(int)
>     def procJump(self, step_id):
>         while int(self._proc_eng.current_step.step_id) < step_id and len(self._proc_eng.current_step.conditions) > 0:
> ```

A few comments here:

- We should probably add some sort of timeout to guard against getting stuck forever; maybe an upper bound on simulation time or on wall time?
- Converting step IDs to int and comparing will work for the procedures we currently use, but a step ID can technically be any alphanumeric string. A more robust comparison is to use the procedure `index_of` function and compare the step indices directly.
- We should check that the target step ID actually exists in the procedure; if the user enters an invalid ID this function will get stuck.
- Right now, this will only work if we're jumping to a step in the same procedure; it won't work for jumping to abort procedures, for example. That's ok for the first implementation - just wanted to make a note of it.
___
*[application/procedures_bridge.py, line 113 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/124#-MU17LOe1DSWuNB8yz1T:-MU17LOe1DSWuNB8yz1U:b-3j7khx) ([raw file](https://github.com/waterloo-rocketry/topside/blob/7b2fbf336c98c4659b44084aa797a035fd41604f/application/procedures_bridge.py#L113)):*
> ```
> int(self._proc_eng.current_step.step_id) == 1
> ```
Instead of just checking for the first step, we can modify this to handle the general case where we call this function from a pre-node:

```
if self._proc_eng.step_position = top.StepPosition.Before:
    self._proc_eng.execute_current()
if self._proc_eng.ready_to_proceed():
    self._proc_eng.next_step()
```

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/124)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @jacobdeery and @James020118)

___
*[application/procedures_bridge.py, line 118 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/124#-MURRJ73DtT9kdGheoey:-MURRJ741qjID52Q7UPO:bxu6m67) ([raw file](https://github.com/waterloo-rocketry/topside/blob/9f1d29584856dc10958d14b264492c3c0e8f2326/application/procedures_bridge.py#L118)):*
> ```Python
>             return
>         dest_index = current_proc.index_of(step_id)
>         while current_proc.index_of(self._proc_eng.current_step.step_id) < dest_index and len(self._proc_eng.current_step.conditions) > 0 and self._proc_eng._plumb.time < top.s_to_micros(200):
> ```

We should probably avoid hardcoding in the upper time limit - we can add it to a constants or config file and import it for the sake of consistency. There might be one already in the plumbing engine folder, since we watch for timeouts there too iirc

**Review by James020118 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/124)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jacobdeery)

___
*[application/procedures_bridge.py, line 111 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/124#-MU15zP92BoACDGagnqa:-MU_A1w35SVVPzQ_Zfc-:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/7b2fbf336c98c4659b44084aa797a035fd41604f/application/procedures_bridge.py#L111)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

A few comments here:

- We should probably add some sort of timeout to guard against getting stuck forever; maybe an upper bound on simulation time or on wall time?
- Converting step IDs to int and comparing will work for the procedures we currently use, but a step ID can technically be any alphanumeric string. A more robust comparison is to use the procedure `index_of` function and compare the step indices directly.
- We should check that the target step ID actually exists in the procedure; if the user enters an invalid ID this function will get stuck.
- Right now, this will only work if we're jumping to a step in the same procedure; it won't work for jumping to abort procedures, for example. That's ok for the first implementation - just wanted to make a note of it.
</blockquote></details>

Done.
___
*[application/procedures_bridge.py, line 113 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/124#-MU17LOe1DSWuNB8yz1T:-MU_A4a17AIGnhGN5bh_:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/7b2fbf336c98c4659b44084aa797a035fd41604f/application/procedures_bridge.py#L113)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> int(self._proc_eng.current_step.step_id) == 1
> ```
Instead of just checking for the first step, we can modify this to handle the general case where we call this function from a pre-node:

```
if self._proc_eng.step_position = top.StepPosition.Before:
    self._proc_eng.execute_current()
if self._proc_eng.ready_to_proceed():
    self._proc_eng.next_step()
```
</blockquote></details>

Done.

**Review by wendi-yu — COMMENTED** [review]
Cool, LGTM for my comments. I'll let Jacob take a look at his and after we should be good to merge

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/124#-:-MU_l_5AB1_t_-U2iERh:bgte5dw)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jacobdeery)

**Review by jacobdeery — APPROVED** [review]
Looks great!

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/124#-:-MUdvCqnCQMXIa0ckurj:b9bkkp1)* status: 0 of 4 files reviewed, all discussions resolved

**Pull request merged**
